console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('  BROWSER CONSOLE TEST - Copy & Paste This');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('');
console.log('1. Sign in at http://localhost:3001');
console.log('2. After redirect to dashboard (port 3003)');
console.log('3. Open DevTools (F12) → Console');
console.log('4. Paste this code and press Enter:');
console.log('');
console.log('─────────────────────────────────────────────────────────────');
console.log('');
console.log('(async () => {');
console.log('  const { Client, Account, Databases, Query } = await import("https://cdn.jsdelivr.net/npm/appwrite@15.0.0/+esm");');
console.log('  const client = new Client().setEndpoint("https://syd.cloud.appwrite.io/v1").setProject("68f23b11000d25eb3664");');
console.log('  const account = new Account(client);');
console.log('  const databases = new Databases(client);');
console.log('  ');
console.log('  console.log("🔍 Getting current user...");');
console.log('  const user = await account.get();');
console.log('  console.log("✅ User ID:", user.$id);');
console.log('  console.log("✅ Email:", user.email);');
console.log('  ');
console.log('  console.log("\\n🔍 Querying therapists collection...");');
console.log('  try {');
console.log('    const result = await databases.listDocuments(');
console.log('      "68f76ee1000e64ca8d05",');
console.log('      "therapists_collection_id",');
console.log('      [Query.equal("email", user.email)]');
console.log('    );');
console.log('    console.log("✅ Found:", result.documents.length, "therapist(s)");');
console.log('    if (result.documents.length > 0) {');
console.log('      const t = result.documents[0];');
console.log('      console.log("📋 Profile:", t.name);');
console.log('      console.log("📋 Profile agentId:", t.agentId);');
console.log('      console.log("📋 User ID:", user.$id);');
console.log('      console.log("📋 Match:", t.agentId === user.$id ? "✅ YES" : "❌ NO - THIS IS THE PROBLEM!");');
console.log('      if (t.agentId !== user.$id) {');
console.log('        console.log("\\n💡 COPY THIS COMMAND:");');
console.log('        console.log(`node fix-agent-id.cjs ${user.$id}`);');
console.log('      }');
console.log('    }');
console.log('  } catch (err) {');
console.log('    console.error("❌ ERROR:", err.message);');
console.log('    console.error("❌ Type:", err.type);');
console.log('    console.error("❌ Code:", err.code);');
console.log('    if (err.code === 401) {');
console.log('      console.error("\\n🔐 PERMISSION ERROR!");');
console.log('      console.error("Users role does NOT have READ permission on therapists_collection_id");');
console.log('    }');
console.log('  }');
console.log('})();');
console.log('');
console.log('─────────────────────────────────────────────────────────────');
console.log('');
console.log('5. Send me the output from the browser console');
console.log('');
