
export const COUNTRIES = [
    { name: "Indonesia", code: "ID", dial_code: "+62" },
    { name: "Malaysia", code: "MY", dial_code: "+60" },
    { name: "Singapore", code: "SG", dial_code: "+65" },
    { name: "Australia", code: "AU", dial_code: "+61" },
    { name: "United Kingdom", code: "GB", dial_code: "+44" },
    { name: "United States", code: "US", dial_code: "+1" },
    { name: "Afghanistan", code: "AF", dial_code: "+93" },
    { name: "Albania", code: "AL", dial_code: "+355" },
    { name: "Algeria", code: "DZ", dial_code: "+213" },
    { name: "American Samoa", code: "AS", dial_code: "+1684" },
    { name: "Andorra", code: "AD", dial_code: "+376" },
    { name: "Angola", code: "AO", dial_code: "+244" },
    { name: "Argentina", code: "AR", dial_code: "+54" },
    { name: "Brazil", code: "BR", dial_code: "+55" },
    { name: "Canada", code: "CA", dial_code: "+1" },
    { name: "China", code: "CN", dial_code: "+86" },
    { name: "France", code: "FR", dial_code: "+33" },
    { name: "Germany", code: "DE", dial_code: "+49" },
    { name: "India", code: "IN", dial_code: "+91" },
    { name: "Italy", code: "IT", dial_code: "+39" },
    { name: "Japan", code: "JP", dial_code: "+81" },
    { name: "Mexico", code: "MX", dial_code: "+52" },
    { name: "Russia", code: "RU", dial_code: "+7" },
    { name: "South Korea", code: "KR", dial_code: "+82" },
    { name: "Spain", code: "ES", dial_code: "+34" },
];
