
export const locations = [
    { province: 'Aceh', cities: ['Banda Aceh', 'Lhokseumawe', 'Sabang', 'Subulussalam'] },
    { province: 'Bali', cities: ['Denpasar'] },
    { province: 'Bangka Belitung Islands', cities: ['Pangkalpinang'] },
    { province: 'Banten', cities: ['Cilegon', 'Serang', 'Tangerang', 'South Tangerang'] },
    { province: 'Bengkulu', cities: ['Bengkulu'] },
    { province: 'Central Java', cities: ['Magelang', 'Pekalongan', 'Salatiga', 'Semarang', 'Surakarta (Solo)', 'Tegal'] },
    { province: 'Central Kalimantan', cities: ['Palangka Raya'] },
    { province: 'Central Papua', cities: ['Nabire'] },
    { province: 'Central Sulawesi', cities: ['Palu'] },
    { province: 'East Java', cities: ['Banyuwangi', 'Blitar', 'Jember', 'Kediri', 'Madiun', 'Malang', 'Mojokerto', 'Pasuruan', 'Probolinggo', 'Surabaya'] },
    { province: 'East Kalimantan', cities: ['Balikpapan', 'Samarinda'] },
    { province: 'East Nusa Tenggara', cities: ['Kupang'] },
    { province: 'Gorontalo', cities: ['Gorontalo'] },
    { province: 'Highland Papua', cities: ['Wamena'] },
    { province: 'Jakarta (Special Capital Region)', cities: ['Jakarta'] },
    { province: 'Jambi', cities: ['Jambi'] },
    { province: 'Lampung', cities: ['Bandar Lampung', 'Metro'] },
    { province: 'Maluku', cities: ['Ambon', 'Tual'] },
    { province: 'North Kalimantan', cities: ['Tarakan'] },
    { province: 'North Maluku', cities: ['Ternate', 'Tidore Islands'] },
    { province: 'North Sulawesi', cities: ['Bitung', 'Kotamobagu', 'Manado', 'Tomohon'] },
    { province: 'North Sumatra', cities: ['Medan', 'Binjai', 'Gunungsitoli', 'Padang Sidempuan', 'Pematangsiantar', 'Sibolga', 'Tanjungbalai', 'Tebing Tinggi'] },
    { province: 'Papua', cities: ['Jayapura'] },
    { province: 'Riau', cities: ['Dumai', 'Pekanbaru'] },
    { province: 'Riau Islands', cities: ['Batam', 'Tanjung Pinang'] },
    { province: 'South Kalimantan', cities: ['Banjarbaru', 'Banjarmasin'] },
    { province: 'South Papua', cities: ['Merauke'] },
    { province: 'South Sulawesi', cities: ['Makassar', 'Palopo', 'Parepare'] },
    { province: 'South Sumatra', cities: ['Lubuklinggau', 'Palembang', 'Pagar Alam', 'Prabumulih'] },
    { province: 'Southeast Sulawesi', cities: ['Baubau', 'Kendari'] },
    { province: 'Southwest Papua', cities: ['Sorong'] },
    { province: 'West Java', cities: ['Bandung', 'Bekasi', 'Bogor', 'Cimahi', 'Cirebon', 'Depok', 'Sukabumi', 'Tasikmalaya'] },
    { province: 'West Kalimantan', cities: ['Pontianak', 'Singkawang'] },
    { province: 'West Nusa Tenggara', cities: ['Mataram'] },
    { province: 'West Papua', cities: ['Manokwari'] },
    { province: 'West Sulawesi', cities: ['Mamuju'] },
    { province: 'West Sumatra', cities: ['Padang', 'Padang Panjang', 'Payakumbuh', 'Pariaman', 'Sawahlunto', 'Solok', 'Bukittinggi'] },
    { province: 'Special Region of Yogyakarta', cities: ['Yogyakarta'] },
];
