
// INDONESIA LOCATIONS
export const locations = [
    { province: 'Aceh', cities: ['Banda Aceh', 'Lhokseumawe', 'Sabang', 'Subulussalam'], country: 'Indonesia' },
    { province: 'Bali', cities: ['Denpasar', 'Canggu', 'Seminyak', 'Kuta', 'Ubud', 'Sanur', 'Nusa Dua', 'Jimbaran'], country: 'Indonesia' },
    { province: 'Bangka Belitung Islands', cities: ['Pangkalpinang'], country: 'Indonesia' },
    { province: 'Banten', cities: ['Cilegon', 'Serang', 'Tangerang', 'South Tangerang'], country: 'Indonesia' },
    { province: 'Bengkulu', cities: ['Bengkulu'], country: 'Indonesia' },
    { province: 'Central Java', cities: ['Magelang', 'Pekalongan', 'Salatiga', 'Semarang', 'Surakarta (Solo)', 'Tegal'], country: 'Indonesia' },
    { province: 'Central Kalimantan', cities: ['Palangka Raya'], country: 'Indonesia' },
    { province: 'Central Papua', cities: ['Nabire'], country: 'Indonesia' },
    { province: 'Central Sulawesi', cities: ['Palu'], country: 'Indonesia' },
    { province: 'East Java', cities: ['Banyuwangi', 'Blitar', 'Jember', 'Kediri', 'Madiun', 'Malang', 'Mojokerto', 'Pasuruan', 'Probolinggo', 'Surabaya'], country: 'Indonesia' },
    { province: 'East Kalimantan', cities: ['Balikpapan', 'Samarinda'], country: 'Indonesia' },
    { province: 'East Nusa Tenggara', cities: ['Kupang'], country: 'Indonesia' },
    { province: 'Gorontalo', cities: ['Gorontalo'], country: 'Indonesia' },
    { province: 'Highland Papua', cities: ['Wamena'], country: 'Indonesia' },
    { province: 'Jakarta (Special Capital Region)', cities: ['Jakarta'], country: 'Indonesia' },
    { province: 'Jambi', cities: ['Jambi'], country: 'Indonesia' },
    { province: 'Lampung', cities: ['Bandar Lampung', 'Metro'], country: 'Indonesia' },
    { province: 'Maluku', cities: ['Ambon', 'Tual'], country: 'Indonesia' },
    { province: 'North Kalimantan', cities: ['Tarakan'], country: 'Indonesia' },
    { province: 'North Maluku', cities: ['Ternate', 'Tidore Islands'], country: 'Indonesia' },
    { province: 'North Sulawesi', cities: ['Bitung', 'Kotamobagu', 'Manado', 'Tomohon'], country: 'Indonesia' },
    { province: 'North Sumatra', cities: ['Medan', 'Binjai', 'Gunungsitoli', 'Padang Sidempuan', 'Pematangsiantar', 'Sibolga', 'Tanjungbalai', 'Tebing Tinggi'], country: 'Indonesia' },
    { province: 'Papua', cities: ['Jayapura'], country: 'Indonesia' },
    { province: 'Riau', cities: ['Dumai', 'Pekanbaru'], country: 'Indonesia' },
    { province: 'Riau Islands', cities: ['Batam', 'Tanjung Pinang'], country: 'Indonesia' },
    { province: 'South Kalimantan', cities: ['Banjarbaru', 'Banjarmasin'], country: 'Indonesia' },
    { province: 'South Papua', cities: ['Merauke'], country: 'Indonesia' },
    { province: 'South Sulawesi', cities: ['Makassar', 'Palopo', 'Parepare'], country: 'Indonesia' },
    { province: 'South Sumatra', cities: ['Lubuklinggau', 'Palembang', 'Pagar Alam', 'Prabumulih'], country: 'Indonesia' },
    { province: 'Southeast Sulawesi', cities: ['Baubau', 'Kendari'], country: 'Indonesia' },
    { province: 'Southwest Papua', cities: ['Sorong'], country: 'Indonesia' },
    { province: 'West Java', cities: ['Bandung', 'Bekasi', 'Bogor', 'Cimahi', 'Cirebon', 'Depok', 'Sukabumi', 'Tasikmalaya'], country: 'Indonesia' },
    { province: 'West Kalimantan', cities: ['Pontianak', 'Singkawang'], country: 'Indonesia' },
    { province: 'West Nusa Tenggara', cities: ['Mataram'], country: 'Indonesia' },
    { province: 'West Papua', cities: ['Manokwari'], country: 'Indonesia' },
    { province: 'West Sulawesi', cities: ['Mamuju'], country: 'Indonesia' },
    { province: 'West Sumatra', cities: ['Padang', 'Padang Panjang', 'Payakumbuh', 'Pariaman', 'Sawahlunto', 'Solok', 'Bukittinggi'], country: 'Indonesia' },
    { province: 'Special Region of Yogyakarta', cities: ['Yogyakarta'], country: 'Indonesia' },
    
    // MALAYSIA LOCATIONS
    { province: 'Federal Territory', cities: ['Kuala Lumpur', 'Putrajaya'], country: 'Malaysia' },
    { province: 'Selangor', cities: ['Shah Alam', 'Petaling Jaya', 'Subang Jaya', 'Klang'], country: 'Malaysia' },
    { province: 'Penang', cities: ['Penang', 'Georgetown'], country: 'Malaysia' },
    { province: 'Johor', cities: ['Johor Bahru', 'Iskandar Puteri'], country: 'Malaysia' },
    { province: 'Malacca', cities: ['Malacca City'], country: 'Malaysia' },
    { province: 'Negeri Sembilan', cities: ['Seremban'], country: 'Malaysia' },
    { province: 'Pahang', cities: ['Kuantan'], country: 'Malaysia' },
    { province: 'Perak', cities: ['Ipoh'], country: 'Malaysia' },
    { province: 'Sabah', cities: ['Kota Kinabalu'], country: 'Malaysia' },
    { province: 'Sarawak', cities: ['Kuching'], country: 'Malaysia' },
    
    // THAILAND LOCATIONS
    { province: 'Bangkok', cities: ['Bangkok'], country: 'Thailand' },
    { province: 'Phuket', cities: ['Phuket'], country: 'Thailand' },
    { province: 'Chiang Mai', cities: ['Chiang Mai'], country: 'Thailand' },
    { province: 'Chonburi', cities: ['Pattaya'], country: 'Thailand' },
    { province: 'Krabi', cities: ['Krabi Town'], country: 'Thailand' },
    { province: 'Surat Thani', cities: ['Koh Samui'], country: 'Thailand' },
    { province: 'Chiang Rai', cities: ['Chiang Rai'], country: 'Thailand' },
    { province: 'Hua Hin', cities: ['Hua Hin'], country: 'Thailand' },
    
    // PHILIPPINES LOCATIONS
    { province: 'Metro Manila', cities: ['Manila', 'Quezon City', 'Makati', 'Pasig', 'Taguig'], country: 'Philippines' },
    { province: 'Cebu', cities: ['Cebu', 'Mandaue', 'Lapu-Lapu'], country: 'Philippines' },
    { province: 'Davao del Sur', cities: ['Davao City'], country: 'Philippines' },
    { province: 'Aklan', cities: ['Boracay'], country: 'Philippines' },
    { province: 'Palawan', cities: ['Puerto Princesa'], country: 'Philippines' },
    { province: 'Baguio', cities: ['Baguio City'], country: 'Philippines' },
    { province: 'Iloilo', cities: ['Iloilo City'], country: 'Philippines' },
    
    // VIETNAM LOCATIONS
    { province: 'Ho Chi Minh', cities: ['Ho Chi Minh City'], country: 'Vietnam' },
    { province: 'Hanoi', cities: ['Hanoi'], country: 'Vietnam' },
    { province: 'Da Nang', cities: ['Da Nang'], country: 'Vietnam' },
    { province: 'Khanh Hoa', cities: ['Nha Trang'], country: 'Vietnam' },
    { province: 'Ba Ria-Vung Tau', cities: ['Vung Tau'], country: 'Vietnam' },
    { province: 'Quang Nam', cities: ['Hoi An'], country: 'Vietnam' },
    { province: 'Lam Dong', cities: ['Da Lat'], country: 'Vietnam' },
    { province: 'Thua Thien-Hue', cities: ['Hue'], country: 'Vietnam' },
    
    // SINGAPORE LOCATIONS
    { province: 'Singapore', cities: ['Singapore'], country: 'Singapore' },
];
