
// INDONESIA LOCATIONS
export const locations = [
    { province: 'Aceh', cities: ['Banda Aceh', 'Lhokseumawe', 'Sabang', 'Subulussalam'], country: 'Indonesia' },
    { province: 'Bali', cities: ['Denpasar', 'Canggu', 'Seminyak', 'Kuta', 'Ubud', 'Sanur', 'Nusa Dua', 'Jimbaran'], country: 'Indonesia' },
    { province: 'Bangka Belitung Islands', cities: ['Pangkalpinang'], country: 'Indonesia' },
    { province: 'Banten', cities: ['Cilegon', 'Serang', 'Tangerang', 'South Tangerang'], country: 'Indonesia' },
    { province: 'Bengkulu', cities: ['Bengkulu'], country: 'Indonesia' },
    { province: 'Central Java', cities: ['Magelang', 'Pekalongan', 'Salatiga', 'Semarang', 'Surakarta (Solo)', 'Tegal'], country: 'Indonesia' },
    { province: 'Central Kalimantan', cities: ['Palangka Raya'], country: 'Indonesia' },
    { province: 'Central Papua', cities: ['Nabire'], country: 'Indonesia' },
    { province: 'Central Sulawesi', cities: ['Palu'], country: 'Indonesia' },
    { province: 'East Java', cities: ['Banyuwangi', 'Blitar', 'Jember', 'Kediri', 'Madiun', 'Malang', 'Mojokerto', 'Pasuruan', 'Probolinggo', 'Surabaya'], country: 'Indonesia' },
    { province: 'East Kalimantan', cities: ['Balikpapan', 'Samarinda'], country: 'Indonesia' },
    { province: 'East Nusa Tenggara', cities: ['Kupang'], country: 'Indonesia' },
    { province: 'Gorontalo', cities: ['Gorontalo'], country: 'Indonesia' },
    { province: 'Highland Papua', cities: ['Wamena'], country: 'Indonesia' },
    { province: 'Jakarta (Special Capital Region)', cities: ['Jakarta'], country: 'Indonesia' },
    { province: 'Jambi', cities: ['Jambi'], country: 'Indonesia' },
    { province: 'Lampung', cities: ['Bandar Lampung', 'Metro'], country: 'Indonesia' },
    { province: 'Maluku', cities: ['Ambon', 'Tual'], country: 'Indonesia' },
    { province: 'North Kalimantan', cities: ['Tarakan'], country: 'Indonesia' },
    { province: 'North Maluku', cities: ['Ternate', 'Tidore Islands'], country: 'Indonesia' },
    { province: 'North Sulawesi', cities: ['Bitung', 'Kotamobagu', 'Manado', 'Tomohon'], country: 'Indonesia' },
    { province: 'North Sumatra', cities: ['Medan', 'Binjai', 'Gunungsitoli', 'Padang Sidempuan', 'Pematangsiantar', 'Sibolga', 'Tanjungbalai', 'Tebing Tinggi'], country: 'Indonesia' },
    { province: 'Papua', cities: ['Jayapura'], country: 'Indonesia' },
    { province: 'Riau', cities: ['Dumai', 'Pekanbaru'], country: 'Indonesia' },
    { province: 'Riau Islands', cities: ['Batam', 'Tanjung Pinang'], country: 'Indonesia' },
    { province: 'South Kalimantan', cities: ['Banjarbaru', 'Banjarmasin'], country: 'Indonesia' },
    { province: 'South Papua', cities: ['Merauke'], country: 'Indonesia' },
    { province: 'South Sulawesi', cities: ['Makassar', 'Palopo', 'Parepare'], country: 'Indonesia' },
    { province: 'South Sumatra', cities: ['Lubuklinggau', 'Palembang', 'Pagar Alam', 'Prabumulih'], country: 'Indonesia' },
    { province: 'Southeast Sulawesi', cities: ['Baubau', 'Kendari'], country: 'Indonesia' },
    { province: 'Southwest Papua', cities: ['Sorong'], country: 'Indonesia' },
    { province: 'West Java', cities: ['Bandung', 'Bekasi', 'Bogor', 'Cimahi', 'Cirebon', 'Depok', 'Sukabumi', 'Tasikmalaya'], country: 'Indonesia' },
    { province: 'West Kalimantan', cities: ['Pontianak', 'Singkawang'], country: 'Indonesia' },
    { province: 'West Nusa Tenggara', cities: ['Mataram'], country: 'Indonesia' },
    { province: 'West Papua', cities: ['Manokwari'], country: 'Indonesia' },
    { province: 'West Sulawesi', cities: ['Mamuju'], country: 'Indonesia' },
    { province: 'West Sumatra', cities: ['Padang', 'Padang Panjang', 'Payakumbuh', 'Pariaman', 'Sawahlunto', 'Solok', 'Bukittinggi'], country: 'Indonesia' },
    { province: 'Special Region of Yogyakarta', cities: ['Yogyakarta'], country: 'Indonesia' },
    
    // PHILIPPINES LOCATIONS
    { province: 'Metro Manila', cities: ['Manila', 'Quezon City', 'Makati', 'Pasig', 'Taguig', 'Mandaluyong', 'Pasay', 'Parañaque', 'Las Piñas', 'Muntinlupa', 'Caloocan', 'Malabon', 'Navotas', 'Valenzuela', 'Marikina', 'San Juan'], country: 'Philippines' },
    { province: 'Cebu', cities: ['Cebu City', 'Mandaue', 'Lapu-Lapu', 'Talisay', 'Toledo', 'Carcar', 'Naga', 'Danao'], country: 'Philippines' },
    { province: 'Davao del Sur', cities: ['Davao City', 'Digos'], country: 'Philippines' },
    { province: 'Aklan', cities: ['Boracay', 'Kalibo'], country: 'Philippines' },
    { province: 'Palawan', cities: ['Puerto Princesa', 'Coron', 'El Nido'], country: 'Philippines' },
    { province: 'Benguet', cities: ['Baguio City'], country: 'Philippines' },
    { province: 'Iloilo', cities: ['Iloilo City', 'Passi'], country: 'Philippines' },
    { province: 'Laguna', cities: ['Calamba', 'San Pablo', 'Biñan', 'Santa Rosa', 'Cabuyao'], country: 'Philippines' },
    { province: 'Cavite', cities: ['Bacoor', 'Dasmariñas', 'Imus', 'Cavite City', 'Tagaytay'], country: 'Philippines' },
    { province: 'Bulacan', cities: ['Malolos', 'Meycauayan', 'San Jose del Monte'], country: 'Philippines' },
    
    // UNITED KINGDOM LOCATIONS
    { province: 'Greater London', cities: ['London', 'Westminster', 'Camden', 'Kensington', 'Chelsea', 'Islington', 'Hackney', 'Tower Hamlets', 'Newham', 'Barking and Dagenham', 'Redbridge', 'Havering', 'Bexley', 'Greenwich', 'Lewisham', 'Southwark', 'Lambeth', 'Wandsworth', 'Hammersmith and Fulham', 'Ealing', 'Hounslow', 'Richmond', 'Kingston', 'Merton', 'Sutton', 'Croydon', 'Bromley', 'Brent', 'Harrow', 'Hillingdon', 'Barnet', 'Enfield', 'Haringey', 'Waltham Forest'], country: 'United Kingdom' },
    { province: 'Greater Manchester', cities: ['Manchester', 'Salford', 'Bolton', 'Bury', 'Oldham', 'Rochdale', 'Stockport', 'Tameside', 'Trafford', 'Wigan'], country: 'United Kingdom' },
    { province: 'West Midlands', cities: ['Birmingham', 'Coventry', 'Wolverhampton', 'Solihull', 'Walsall', 'Dudley', 'Sandwell'], country: 'United Kingdom' },
    { province: 'Merseyside', cities: ['Liverpool', 'Wirral', 'Sefton', 'St Helens', 'Knowsley'], country: 'United Kingdom' },
    { province: 'West Yorkshire', cities: ['Leeds', 'Bradford', 'Wakefield', 'Huddersfield', 'Halifax'], country: 'United Kingdom' },
    { province: 'Scotland', cities: ['Glasgow', 'Edinburgh', 'Aberdeen', 'Dundee', 'Inverness', 'Stirling', 'Perth'], country: 'United Kingdom' },
    { province: 'South West England', cities: ['Bristol', 'Plymouth', 'Exeter', 'Bournemouth', 'Poole', 'Swindon'], country: 'United Kingdom' },
    { province: 'Tyne and Wear', cities: ['Newcastle', 'Sunderland', 'Gateshead', 'South Shields'], country: 'United Kingdom' },
    { province: 'Wales', cities: ['Cardiff', 'Swansea', 'Newport', 'Wrexham'], country: 'United Kingdom' },
    { province: 'East Sussex', cities: ['Brighton', 'Eastbourne', 'Hastings'], country: 'United Kingdom' },
    { province: 'Oxfordshire', cities: ['Oxford'], country: 'United Kingdom' },
    { province: 'Cambridgeshire', cities: ['Cambridge', 'Peterborough'], country: 'United Kingdom' },
    { province: 'Nottinghamshire', cities: ['Nottingham'], country: 'United Kingdom' },
    { province: 'South Yorkshire', cities: ['Sheffield', 'Doncaster', 'Rotherham', 'Barnsley'], country: 'United Kingdom' },
    
    // UNITED STATES LOCATIONS
    { province: 'New York', cities: ['New York City', 'Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island', 'Buffalo', 'Rochester', 'Syracuse', 'Albany'], country: 'United States' },
    { province: 'California', cities: ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento', 'Oakland', 'Santa Monica', 'Beverly Hills', 'Long Beach', 'Anaheim', 'Pasadena', 'Riverside', 'Irvine', 'Fremont'], country: 'United States' },
    { province: 'Illinois', cities: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford'], country: 'United States' },
    { province: 'Texas', cities: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano'], country: 'United States' },
    { province: 'Arizona', cities: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Tempe'], country: 'United States' },
    { province: 'Pennsylvania', cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie'], country: 'United States' },
    { province: 'Washington', cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'], country: 'United States' },
    { province: 'Colorado', cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Boulder'], country: 'United States' },
    { province: 'District of Columbia', cities: ['Washington DC'], country: 'United States' },
    { province: 'Massachusetts', cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'], country: 'United States' },
    { province: 'Nevada', cities: ['Las Vegas', 'Reno', 'Henderson'], country: 'United States' },
    { province: 'Florida', cities: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale', 'St. Petersburg', 'Tallahassee', 'Cape Coral'], country: 'United States' },
    { province: 'Georgia', cities: ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Athens'], country: 'United States' },
    { province: 'Oregon', cities: ['Portland', 'Eugene', 'Salem', 'Gresham'], country: 'United States' },
    { province: 'Tennessee', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'], country: 'United States' },
    { province: 'Louisiana', cities: ['New Orleans', 'Baton Rouge', 'Shreveport'], country: 'United States' },
    
    // AUSTRALIA LOCATIONS
    { province: 'New South Wales', cities: ['Sydney', 'CBD Sydney', 'Bondi', 'Manly', 'Parramatta', 'Newcastle', 'Wollongong', 'Central Coast', 'Penrith', 'Liverpool', 'Blacktown', 'Sutherland', 'Randwick', 'North Sydney'], country: 'Australia' },
    { province: 'Victoria', cities: ['Melbourne', 'CBD Melbourne', 'St Kilda', 'Fitzroy', 'Richmond', 'South Yarra', 'Carlton', 'Prahran', 'Geelong', 'Ballarat', 'Bendigo'], country: 'Australia' },
    { province: 'Queensland', cities: ['Brisbane', 'Gold Coast', 'Cairns', 'Townsville', 'Sunshine Coast', 'Toowoomba', 'Mackay', 'Rockhampton'], country: 'Australia' },
    { province: 'Western Australia', cities: ['Perth', 'Fremantle', 'Mandurah', 'Bunbury', 'Rockingham', 'Kalgoorlie'], country: 'Australia' },
    { province: 'South Australia', cities: ['Adelaide', 'Mount Gambier', 'Whyalla', 'Murray Bridge'], country: 'Australia' },
    { province: 'Australian Capital Territory', cities: ['Canberra'], country: 'Australia' },
    { province: 'Tasmania', cities: ['Hobart', 'Launceston', 'Burnie', 'Devonport'], country: 'Australia' },
    { province: 'Northern Territory', cities: ['Darwin', 'Alice Springs', 'Palmerston'], country: 'Australia' },
    
    // GERMANY LOCATIONS
    { province: 'Berlin', cities: ['Berlin', 'Mitte', 'Kreuzberg', 'Friedrichshain', 'Charlottenburg', 'Prenzlauer Berg', 'Neukölln', 'Tempelhof', 'Schöneberg', 'Wedding'], country: 'Germany' },
    { province: 'Bavaria', cities: ['Munich', 'Nuremberg', 'Augsburg', 'Regensburg', 'Würzburg', 'Ingolstadt', 'Erlangen', 'Fürth'], country: 'Germany' },
    { province: 'Hamburg', cities: ['Hamburg', 'Altona', 'Eimsbüttel', 'Wandsbek', 'Harburg'], country: 'Germany' },
    { province: 'Hesse', cities: ['Frankfurt', 'Wiesbaden', 'Kassel', 'Darmstadt', 'Offenbach', 'Hanau'], country: 'Germany' },
    { province: 'North Rhine-Westphalia', cities: ['Cologne', 'Düsseldorf', 'Dortmund', 'Essen', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Münster', 'Mönchengladbach', 'Gelsenkirchen', 'Aachen'], country: 'Germany' },
    { province: 'Baden-Württemberg', cities: ['Stuttgart', 'Mannheim', 'Karlsruhe', 'Freiburg', 'Heidelberg', 'Ulm', 'Heilbronn', 'Pforzheim'], country: 'Germany' },
    { province: 'Saxony', cities: ['Leipzig', 'Dresden', 'Chemnitz', 'Zwickau'], country: 'Germany' },
    { province: 'Lower Saxony', cities: ['Hanover', 'Braunschweig', 'Oldenburg', 'Osnabrück', 'Wolfsburg', 'Göttingen'], country: 'Germany' },
    { province: 'Bremen', cities: ['Bremen', 'Bremerhaven'], country: 'Germany' },
];
