/**
 * Page Type Definitions
 * All possible pages/routes in the application
 */

export type Page = 
    | 'landing' 
    | 'auth' 
    | 'home' 
    | 'joinIndastreet'
    | 'detail' 
    | 'massagePlaceProfile' 
    | 'facialProviders'
    | 'facialPlaceProfile'
    | 'facialPlaceDashboard'
    | 'facialPortal'
    | 'facialMemberDashboard'
    | 'facialTypes'
    | 'registrationChoice' 
    | 'providerAuth' 
    | 'therapistStatus' 
    | 'therapistPortal'
    | 'therapistProfile' // 🎯 NEW: Customer-facing therapist profile page 
    | 'profile' // 🎯 NEW: Guest profile page for non-registered users
    | 'qr-code' // QR Code sharing page
    | 'membership-select'
    | 'lead-accept'
    | 'lead-decline'
    | 'membership-terms'
    | 'placeDashboard' 
    | 'serviceTerms' 
    | 'placeTerms' 
    | 'placeDiscountBadge' 
    | 'privacy' 
    | 'cookies-policy' 
    | 'membership' 
    | 'booking' 
    | 'bookings' 
    | 'notifications' 
    | 'massageTypes' 
    | 'unifiedLogin' 
    | 'therapistLogin' 
    | 'massagePlaceLogin' 
    | 'provider-portals'
    | 'employerJobPosting' 
    | 'jobPostingPayment' 
    | 'browseJobs' 
    | 'massageJobs' 
    | 'therapistJobs' 
    | 'therapistJobRegistration' 
    | 'jobUnlockPayment' 
    | 'chatList' 
    | 'about' 
    | 'about-us'
    | 'how-it-works' 
    | 'massage-bali' 
    | 'blog' 
    | 'blog/bali-spa-industry-trends-2025' 
    | 'blog/top-10-massage-techniques' 
    | 'blog/massage-career-indonesia' 
    | 'blog/benefits-regular-massage-therapy' 
    | 'blog/hiring-massage-therapists-guide' 
    | 'blog/traditional-balinese-massage' 
    | 'blog/spa-tourism-indonesia' 
    | 'blog/aromatherapy-massage-oils' 
    | 'blog/pricing-guide-massage-therapists' 
    | 'blog/deep-tissue-vs-swedish-massage' 
    | 'blog/online-presence-massage-therapist' 
    | 'blog/wellness-tourism-ubud'
    | 'blog-spa-tourism-indonesia'
    | 'blog-aromatherapy-massage-oils'
    | 'blog-pricing-guide-therapists'
    | 'blog-deep-tissue-vs-swedish'
    | 'blog-online-presence-therapist'
    | 'blog-wellness-tourism-ubud'
    | 'blog-hiring-massage-therapists'
    | 'blog-traditional-balinese-massage'
    | 'blog-bali-spa-trends-2025'
    | 'blog-top-10-massage-techniques'
    | 'blog-massage-career-indonesia'
    | 'blog-benefits-regular-massage'
    | 'guestAlerts'
    | 'rewardBannersTest'
    | 'todaysDiscounts' 
    | 'faq' 
    | 'indastreet-partners'
    | 'partnership-application'
    | 'balinese-massage' 
    | 'deep-tissue-massage' 
    | 'swedish-massage'
    | 'hot-stone-massage'
    | 'aromatherapy-massage'
    | 'thai-massage'
    | 'reflexology-massage'
    | 'shiatsu-massage'
    | 'sports-massage'
    | 'pregnancy-massage'
    | 'reviews-testimonials'
    | 'contact' 
    | 'quick-support' 
    | 'partnership-inquiries' 
    | 'press-media' 
    | 'career-opportunities' 
    | 'therapist-info' 
    | 'hotel-info' 
    | 'employer-info' 
    | 'payment-info' 
    | 'adminShopManagement'
    | 'coin-history' 
    | 'coinHistory' // Added camelCase variant used in navigation handlers
    | 'coin-shop' // Added hyphenated coin shop page id
    | 'hotelVillaMenu' // Added live hotel/villa menu page id
    | 'coinSystemTest'
    | 'coin-test' 
    | 'website-management'
    | 'partner-settings-hotel'
    | 'partner-settings-villa'
    | 'join-indastreet-partners'
    | 'todays-discounts'
    | 'hotel-login'
    | 'placeLogin'
    | 'customerAuth'
    | 'adminLogin'
    | 'villaDashboard'
    | 'hotelDashboard'
    | 'customerDashboard'
    | 'adminDashboard'
    | 'agentPortal'
    | 'customerPortal'
    | 'massagePlacePortal'
    | 'termsOfService'
    | 'privacyPolicy'
    | 'agentDashboard'
    | 'therapistDashboard'
    | 'agentTerms'
    | 'accept-booking'
    | 'decline-booking'
    | 'verifiedProBadge'
    | 'mobileTherapistStandards'
    | 'customerProviders'
    | 'customerReviews'
    | 'customerSupport';

export type Language = 'en' | 'id' | 'gb';

export type LoggedInProvider = { 
    id: number | string; 
    type: 'therapist' | 'place' 
};

export type LoggedInUser = { 
    id: string; 
    type: 'admin' | 'hotel' | 'villa' | 'agent'
};
