/**
 * Page Type Definitions
 * All possible pages/routes in the application
 */

export type Page = 
    | 'landing' 
    | 'auth' 
    | 'home' 
    | 'detail' 
    | 'massagePlaceProfile' 
    | 'adminLogin' 
    | 'adminDashboard' 
    | 'registrationChoice' 
    | 'providerAuth' 
    | 'therapistStatus' 
    | 'therapistDashboard' 
    | 'placeDashboard' 
    | 'agent' 
    | 'agentAuth' 
    | 'agentDashboard' 
    | 'agentTerms' 
    | 'serviceTerms' 
    | 'privacy' 
    | 'cookies-policy' 
    | 'membership' 
    | 'booking' 
    | 'bookings' 
    | 'notifications' 
    | 'massageTypes' 
    | 'hotelLogin' 
    | 'hotelDashboard' 
    | 'villaLogin' 
    | 'villaDashboard' 
    | 'unifiedLogin' 
    | 'therapistLogin' 
    | 'massagePlaceLogin' 
    | 'hotelVillaMenu' 
    | 'employerJobPosting' 
    | 'jobPostingPayment' 
    | 'browseJobs' 
    | 'massageJobs' 
    | 'therapistJobs' 
    | 'therapistJobRegistration' 
    | 'jobUnlockPayment' 
    | 'adminBankSettings' 
    | 'customerAuth' 
    | 'customerDashboard' 
    | 'chatList' 
    | 'about' 
    | 'how-it-works' 
    | 'massage-bali' 
    | 'blog' 
    | 'blog/bali-spa-industry-trends-2025' 
    | 'blog/top-10-massage-techniques' 
    | 'blog/massage-career-indonesia' 
    | 'blog/benefits-regular-massage-therapy' 
    | 'blog/hiring-massage-therapists-guide' 
    | 'blog/traditional-balinese-massage' 
    | 'blog/spa-tourism-indonesia' 
    | 'blog/aromatherapy-massage-oils' 
    | 'blog/pricing-guide-massage-therapists' 
    | 'blog/deep-tissue-vs-swedish-massage' 
    | 'blog/online-presence-massage-therapist' 
    | 'blog/wellness-tourism-ubud' 
    | 'faq' 
    | 'balinese-massage' 
    | 'deep-tissue-massage' 
    | 'contact' 
    | 'quick-support' 
    | 'partnership-inquiries' 
    | 'press-media' 
    | 'career-opportunities' 
    | 'therapist-info' 
    | 'hotel-info' 
    | 'employer-info' 
    | 'payment-info' 
    | 'coin-shop' 
    | 'admin-shop-management' 
    | 'reward-banners-test' 
    | 'referral' 
    | 'coin-history' 
    | 'coin-test' 
    | 'todays-discounts';

export type Language = 'en' | 'id';

export type LoggedInProvider = { 
    id: number | string; 
    type: 'therapist' | 'place' 
};

export type LoggedInUser = { 
    id: string; 
    type: 'admin' | 'hotel' | 'villa' | 'agent' 
};
