/**
 * Therapeutic & Clinical Massage directory entries for dashboard (massage home service & massage city places).
 * Each entry appears in the Massage Types Directory; full content is shown in the (i) description
 * popup on the live site when the member has added the type to their menu price slider.
 */

export interface TherapeuticMassageDirectoryEntry {
  name: string;
  shortDescription: string;
  recommendedDuration: string;
  pressureLevel: string;
  focusAreas: string;
  idealFor: string;
  suggestedFrequency: string;
  techniqueStyle: string;
  postTreatmentNotes: string;
  recommendedAddOns: string;
  whatToExpect: string;
  imageThumbnail: string;
}

export function getTherapeuticMassagePopupContent(serviceName: string): string | null {
  const entry = THERAPEUTIC_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (serviceName || '').toLowerCase().trim()
  );
  if (!entry) return null;
  const parts: string[] = [
    'What to Expect:',
    entry.whatToExpect,
    '',
    `Recommended Duration: ${entry.recommendedDuration}`,
    `Pressure Level: ${entry.pressureLevel}`,
    `Focus Areas: ${entry.focusAreas}`,
    `Ideal For: ${entry.idealFor}`,
    `Suggested Frequency: ${entry.suggestedFrequency}`,
    `Technique Style: ${entry.techniqueStyle}`,
    `Post-Treatment Notes: ${entry.postTreatmentNotes}`,
    `Recommended Add-Ons: ${entry.recommendedAddOns}`,
  ];
  return parts.join('\n');
}

export function getTherapeuticMassageEntry(name: string): TherapeuticMassageDirectoryEntry | undefined {
  return THERAPEUTIC_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (name || '').toLowerCase().trim()
  );
}

export const THERAPEUTIC_MASSAGE_DIRECTORY_NAMES = [
  'Deep Tissue Therapy Massage',
  'Trigger Point Release Therapy',
  'Myofascial Release Therapy',
  'Neuromuscular Therapy',
  'Orthopedic Recovery Massage',
  'Injury Rehabilitation Massage',
  'Chronic Pain Relief Therapy',
  'Sciatica Support Massage',
  'Frozen Shoulder Mobility Therapy',
  'Lower Back Relief Therapy',
  'Neck & Cervical Release Therapy',
  'TMJ Jaw Relief Therapy',
  'Migraine Support Massage',
  'Postural Alignment Therapy',
  'Scar Tissue Release Therapy',
  'Tendon Support Therapy',
  'Carpal Tunnel Relief Therapy',
  'Plantar Fascia Support Massage',
  'IT Band Release Therapy',
  'Hip Mobility Restoration',
  'Rotator Cuff Support Therapy',
  'Whiplash Recovery Therapy',
  'Post-Surgery Recovery Massage',
  'Clinical Lymphatic Drainage',
  'Fibromyalgia Comfort Therapy',
  'Arthritis Support Therapy',
  'Muscle Imbalance Correction',
  'Occupational Strain Relief Massage',
  'Repetitive Strain Therapy',
  'Mobility Restoration Therapy',
  'Nerve Compression Relief Therapy',
  'Fascia Realignment Therapy',
  'Deep Muscle Reset Therapy',
  'Body Alignment Therapy',
  'Corrective Movement Massage',
  'Functional Recovery Therapy',
  'Advanced Pain Management Massage',
  'Soft Tissue Rehabilitation Therapy',
  'Compression Therapy Massage',
  'Active Release Therapy',
  'Joint Mobilization Therapy',
  'Myoskeletal Alignment Therapy',
  'Clinical Trigger Release Therapy',
  'Therapeutic Full Body Reset',
  'Corrective Posture Massage',
  'Advanced Deep Tissue Therapy',
  'Rehabilitation Maintenance Massage',
  'Precision Pain Relief Therapy',
  'Corrective Soft Tissue Therapy',
  'Structural Balance Therapy',
] as const;

export const THERAPEUTIC_MASSAGE_DIRECTORY_ENTRIES: TherapeuticMassageDirectoryEntry[] = [
  {
    name: 'Deep Tissue Therapy Massage',
    shortDescription: 'A slow, focused session designed to release deep muscle tension and chronic tightness. Sustained pressure and controlled strokes target deeper layers of muscle and connective tissue to reduce stiffness and improve mobility.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Back, shoulders, hips, legs',
    idealFor: 'Chronic tension, stiffness, postural strain',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Slow deep pressure with muscle stripping',
    postTreatmentNotes: 'Mild soreness may occur; hydration recommended.',
    recommendedAddOns: 'Cupping therapy, stretch therapy',
    whatToExpect:
      'A slow, focused session designed to release deep muscle tension and chronic tightness. Sustained pressure and controlled strokes target deeper layers of muscle and connective tissue to reduce stiffness and improve mobility.',
    imageThumbnail: '',
  },
  {
    name: 'Trigger Point Release Therapy',
    shortDescription: 'A targeted session focused on releasing tight muscle knots that refer pain to other areas. Direct pressure is applied to specific points to restore muscle function and reduce discomfort.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Localized muscle knots',
    idealFor: 'Referred pain, muscle tightness',
    suggestedFrequency: 'Weekly until relief',
    techniqueStyle: 'Static pressure and targeted release',
    postTreatmentNotes: 'Temporary tenderness possible.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'A targeted session focused on releasing tight muscle knots that refer pain to other areas. Direct pressure is applied to specific points to restore muscle function and reduce discomfort.',
    imageThumbnail: '',
  },
  {
    name: 'Myofascial Release Therapy',
    shortDescription: 'A slow, stretching-based therapy designed to release fascial restrictions and improve flexibility. Gentle sustained pressure helps restore natural movement patterns.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body or restricted areas',
    idealFor: 'Mobility limitation, fascia tightness',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Sustained fascial stretching',
    postTreatmentNotes: 'Increased flexibility expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A slow, stretching-based therapy designed to release fascial restrictions and improve flexibility. Gentle sustained pressure helps restore natural movement patterns.',
    imageThumbnail: '',
  },
  {
    name: 'Neuromuscular Therapy',
    shortDescription: 'A clinical approach combining deep pressure and nerve pathway work to reduce muscular dysfunction and pain patterns.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Targeted muscle groups',
    idealFor: 'Chronic pain, nerve compression',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Trigger point with nerve pathway focus',
    postTreatmentNotes: 'Improved muscle activation.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'A clinical approach combining deep pressure and nerve pathway work to reduce muscular dysfunction and pain patterns.',
    imageThumbnail: '',
  },
  {
    name: 'Orthopedic Recovery Massage',
    shortDescription: 'A structured therapy session focused on musculoskeletal injuries and corrective alignment. Techniques aim to restore proper movement and reduce discomfort.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Injury-specific regions',
    idealFor: 'Rehabilitation, joint dysfunction',
    suggestedFrequency: 'Weekly during recovery',
    techniqueStyle: 'Clinical corrective therapy',
    postTreatmentNotes: 'Gradual mobility improvement expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A structured therapy session focused on musculoskeletal injuries and corrective alignment. Techniques aim to restore proper movement and reduce discomfort.',
    imageThumbnail: '',
  },
  {
    name: 'Injury Rehabilitation Massage',
    shortDescription: 'A recovery-focused session designed to support healing after muscle strain or minor injury. Controlled pressure and mobility work assist tissue repair and restore range of motion.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Injury-specific area',
    idealFor: 'Muscle strains, minor injuries',
    suggestedFrequency: 'Weekly during recovery',
    techniqueStyle: 'Corrective soft tissue therapy',
    postTreatmentNotes: 'Gradual functional improvement expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A recovery-focused session designed to support healing after muscle strain or minor injury. Controlled pressure and mobility work assist tissue repair and restore range of motion.',
    imageThumbnail: '',
  },
  {
    name: 'Chronic Pain Relief Therapy',
    shortDescription: 'A structured session targeting long-term muscular discomfort. Techniques aim to reduce tension build-up and improve daily comfort.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Pain-dominant regions',
    idealFor: 'Persistent muscular discomfort',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Therapeutic tension release',
    postTreatmentNotes: 'Relief may increase over multiple sessions.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'A structured session targeting long-term muscular discomfort. Techniques aim to reduce tension build-up and improve daily comfort.',
    imageThumbnail: '',
  },
  {
    name: 'Sciatica Support Massage',
    shortDescription: 'Focused work on lower back and gluteal muscles to reduce nerve compression and improve mobility.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Lower back, glutes',
    idealFor: 'Sciatic discomfort',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted compression and stretching',
    postTreatmentNotes: 'Improved leg comfort expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused work on lower back and gluteal muscles to reduce nerve compression and improve mobility.',
    imageThumbnail: '',
  },
  {
    name: 'Frozen Shoulder Mobility Therapy',
    shortDescription: 'Gentle yet structured mobilization techniques to improve shoulder range and reduce stiffness.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Shoulder joint',
    idealFor: 'Restricted shoulder movement',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Mobility-based therapeutic work',
    postTreatmentNotes: 'Gradual range improvement expected.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'Gentle yet structured mobilization techniques to improve shoulder range and reduce stiffness.',
    imageThumbnail: '',
  },
  {
    name: 'Lower Back Relief Therapy',
    shortDescription: 'Targets lumbar tension and muscular imbalance to support spinal comfort and posture.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Lower back',
    idealFor: 'Desk workers, manual laborers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep muscle tension release',
    postTreatmentNotes: 'Reduced stiffness expected.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'Targets lumbar tension and muscular imbalance to support spinal comfort and posture.',
    imageThumbnail: '',
  },
  {
    name: 'Neck & Cervical Release Therapy',
    shortDescription: 'Focused relief for upper spine tension and postural strain from prolonged sitting.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Neck, upper back',
    idealFor: 'Tech users, office workers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured cervical muscle release',
    postTreatmentNotes: 'Improved neck mobility expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused relief for upper spine tension and postural strain from prolonged sitting.',
    imageThumbnail: '',
  },
  {
    name: 'TMJ Jaw Relief Therapy',
    shortDescription: 'Specialized work addressing jaw tension and facial muscle tightness.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Jaw, temples',
    idealFor: 'Teeth grinding, jaw tension',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Targeted facial muscle release',
    postTreatmentNotes: 'Reduced jaw tightness.',
    recommendedAddOns: 'Relaxation therapy',
    whatToExpect:
      'Specialized work addressing jaw tension and facial muscle tightness.',
    imageThumbnail: '',
  },
  {
    name: 'Migraine Support Massage',
    shortDescription: 'A calming yet therapeutic session reducing tension patterns contributing to headaches.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Head, neck, shoulders',
    idealFor: 'Tension headaches',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Trigger point and relaxation blend',
    postTreatmentNotes: 'Reduced head pressure expected.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A calming yet therapeutic session reducing tension patterns contributing to headaches.',
    imageThumbnail: '',
  },
  {
    name: 'Postural Alignment Therapy',
    shortDescription: 'Corrective therapy aimed at improving muscular balance and posture.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back, hips, shoulders',
    idealFor: 'Postural imbalance',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structural muscle balancing',
    postTreatmentNotes: 'Improved posture awareness.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Corrective therapy aimed at improving muscular balance and posture.',
    imageThumbnail: '',
  },
  {
    name: 'Scar Tissue Release Therapy',
    shortDescription: 'Focused manual work designed to improve tissue flexibility around healed scars.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Scar region',
    idealFor: 'Post-surgical clients',
    suggestedFrequency: 'As needed',
    techniqueStyle: 'Controlled tissue mobilization',
    postTreatmentNotes: 'Gradual flexibility improvement.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'Focused manual work designed to improve tissue flexibility around healed scars.',
    imageThumbnail: '',
  },
  {
    name: 'Tendon Support Therapy',
    shortDescription: 'A focused treatment designed to reduce tension around irritated tendons and improve surrounding muscle balance.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Affected tendon region',
    idealFor: 'Overuse strain',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Controlled soft tissue therapy',
    postTreatmentNotes: 'Gradual comfort improvement expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A focused treatment designed to reduce tension around irritated tendons and improve surrounding muscle balance.',
    imageThumbnail: '',
  },
  {
    name: 'Carpal Tunnel Relief Therapy',
    shortDescription: 'Targets forearm and wrist tension contributing to nerve compression discomfort.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Wrist, forearm',
    idealFor: 'Repetitive strain',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted compression therapy',
    postTreatmentNotes: 'Reduced wrist stiffness.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Targets forearm and wrist tension contributing to nerve compression discomfort.',
    imageThumbnail: '',
  },
  {
    name: 'Plantar Fascia Support Massage',
    shortDescription: 'Focused release for foot arch tension to improve walking comfort.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Feet, calves',
    idealFor: 'Heel discomfort',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep tissue foot therapy',
    postTreatmentNotes: 'Increased foot mobility expected.',
    recommendedAddOns: 'Foot therapy',
    whatToExpect:
      'Focused release for foot arch tension to improve walking comfort.',
    imageThumbnail: '',
  },
  {
    name: 'IT Band Release Therapy',
    shortDescription: 'Targets lateral thigh tightness to improve leg alignment and reduce discomfort.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Outer thigh',
    idealFor: 'Runners, cyclists',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep myofascial release',
    postTreatmentNotes: 'Improved stride comfort.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Targets lateral thigh tightness to improve leg alignment and reduce discomfort.',
    imageThumbnail: '',
  },
  {
    name: 'Hip Mobility Restoration',
    shortDescription: 'Structured session improving hip flexibility and reducing muscular imbalance.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Hips, glutes',
    idealFor: 'Restricted mobility',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Mobility-based therapy',
    postTreatmentNotes: 'Improved range of motion.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Structured session improving hip flexibility and reducing muscular imbalance.',
    imageThumbnail: '',
  },
  {
    name: 'Rotator Cuff Support Therapy',
    shortDescription: 'Targets shoulder stability muscles to improve joint function and reduce strain.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Shoulder complex',
    idealFor: 'Shoulder fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted muscular balancing',
    postTreatmentNotes: 'Enhanced shoulder mobility.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'Targets shoulder stability muscles to improve joint function and reduce strain.',
    imageThumbnail: '',
  },
  {
    name: 'Whiplash Recovery Therapy',
    shortDescription: 'Gentle therapeutic approach addressing cervical muscle stiffness.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Neck, upper back',
    idealFor: 'Post-accident stiffness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Controlled tension release',
    postTreatmentNotes: 'Gradual neck mobility improvement.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'Gentle therapeutic approach addressing cervical muscle stiffness.',
    imageThumbnail: '',
  },
  {
    name: 'Post-Surgery Recovery Massage',
    shortDescription: 'A cautious and structured session supporting tissue recovery after healing phase.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light–Medium ★★☆',
    focusAreas: 'Surgery-adjacent area',
    idealFor: 'Recovery phase clients',
    suggestedFrequency: 'As advised',
    techniqueStyle: 'Gentle mobilization therapy',
    postTreatmentNotes: 'Increased tissue flexibility.',
    recommendedAddOns: 'Lymphatic support',
    whatToExpect:
      'A cautious and structured session supporting tissue recovery after healing phase.',
    imageThumbnail: '',
  },
  {
    name: 'Clinical Lymphatic Drainage',
    shortDescription: 'A gentle rhythmic session encouraging fluid movement and reducing swelling.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Swelling-prone areas',
    idealFor: 'Fluid retention',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Manual lymphatic technique',
    postTreatmentNotes: 'Increased lightness expected.',
    recommendedAddOns: 'Detox therapy',
    whatToExpect:
      'A gentle rhythmic session encouraging fluid movement and reducing swelling.',
    imageThumbnail: '',
  },
  {
    name: 'Fibromyalgia Comfort Therapy',
    shortDescription: 'A gentle, calming approach reducing widespread muscular sensitivity.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light–Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive muscle conditions',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Gentle therapeutic massage',
    postTreatmentNotes: 'Relaxation and comfort expected.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A gentle, calming approach reducing widespread muscular sensitivity.',
    imageThumbnail: '',
  },
  {
    name: 'Arthritis Support Therapy',
    shortDescription: 'Improves joint mobility and reduces surrounding muscle tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light–Medium ★★☆',
    focusAreas: 'Affected joints',
    idealFor: 'Joint stiffness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Gentle mobility therapy',
    postTreatmentNotes: 'Increased joint flexibility.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'Improves joint mobility and reduces surrounding muscle tension.',
    imageThumbnail: '',
  },
  {
    name: 'Muscle Imbalance Correction',
    shortDescription: 'Identifies and releases overactive muscles to restore balanced posture.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Postural muscles',
    idealFor: 'Desk workers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structural balancing therapy',
    postTreatmentNotes: 'Improved posture alignment.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Identifies and releases overactive muscles to restore balanced posture.',
    imageThumbnail: '',
  },
  {
    name: 'Occupational Strain Relief Massage',
    shortDescription: 'Designed for repetitive work strain affecting specific muscle groups.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Work-stressed areas',
    idealFor: 'Manual labor, office workers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Tension release therapy',
    postTreatmentNotes: 'Reduced daily discomfort.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'Designed for repetitive work strain affecting specific muscle groups.',
    imageThumbnail: '',
  },
  {
    name: 'Repetitive Strain Therapy',
    shortDescription: 'Focused treatment reducing chronic overuse patterns.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Repetitive use areas',
    idealFor: 'Athletes, workers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted trigger release',
    postTreatmentNotes: 'Improved function expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused treatment reducing chronic overuse patterns.',
    imageThumbnail: '',
  },
  {
    name: 'Mobility Restoration Therapy',
    shortDescription: 'A structured program designed to improve range of motion and flexibility.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Restricted joints',
    idealFor: 'Limited flexibility',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Assisted stretching therapy',
    postTreatmentNotes: 'Increased fluid movement.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'A structured program designed to improve range of motion and flexibility.',
    imageThumbnail: '',
  },
  {
    name: 'Nerve Compression Relief Therapy',
    shortDescription: 'Focused muscular release to reduce surrounding nerve tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Compression zones',
    idealFor: 'Radiating discomfort',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Neuromuscular release',
    postTreatmentNotes: 'Reduced nerve irritation.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused muscular release to reduce surrounding nerve tension.',
    imageThumbnail: '',
  },
  {
    name: 'Fascia Realignment Therapy',
    shortDescription: 'Targets connective tissue restrictions affecting movement patterns.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Mobility issues',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Myofascial therapy',
    postTreatmentNotes: 'Improved alignment.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Targets connective tissue restrictions affecting movement patterns.',
    imageThumbnail: '',
  },
  {
    name: 'Deep Muscle Reset Therapy',
    shortDescription: 'A comprehensive deep-pressure session addressing chronic tightness.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Very Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Long-term muscle tension',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Advanced deep tissue',
    postTreatmentNotes: 'Mild soreness possible.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'A comprehensive deep-pressure session addressing chronic tightness.',
    imageThumbnail: '',
  },
  {
    name: 'Body Alignment Therapy',
    shortDescription: 'Corrective session focused on muscle balance and posture improvement.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back, hips',
    idealFor: 'Postural correction',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structural therapy',
    postTreatmentNotes: 'Improved symmetry.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Corrective session focused on muscle balance and posture improvement.',
    imageThumbnail: '',
  },
  {
    name: 'Corrective Movement Massage',
    shortDescription: 'Combines massage with guided mobility patterns.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Functional areas',
    idealFor: 'Movement restriction',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Functional therapeutic work',
    postTreatmentNotes: 'Improved coordination.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Combines massage with guided mobility patterns.',
    imageThumbnail: '',
  },
  {
    name: 'Functional Recovery Therapy',
    shortDescription: 'Structured session supporting return to daily activity after strain.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Affected regions',
    idealFor: 'Mild injury recovery',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Rehabilitation therapy',
    postTreatmentNotes: 'Increased functional comfort.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'Structured session supporting return to daily activity after strain.',
    imageThumbnail: '',
  },
  {
    name: 'Advanced Pain Management Massage',
    shortDescription: 'Focused therapy targeting persistent muscular discomfort.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Pain-specific areas',
    idealFor: 'Chronic tension',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Clinical tension release',
    postTreatmentNotes: 'Gradual improvement expected.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Focused therapy targeting persistent muscular discomfort.',
    imageThumbnail: '',
  },
  {
    name: 'Soft Tissue Rehabilitation Therapy',
    shortDescription: 'Encourages tissue healing and flexibility restoration.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Soft tissue injuries',
    idealFor: 'Recovery support',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Controlled soft tissue therapy',
    postTreatmentNotes: 'Improved elasticity.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Encourages tissue healing and flexibility restoration.',
    imageThumbnail: '',
  },
  {
    name: 'Compression Therapy Massage',
    shortDescription: 'Rhythmic compression techniques improving circulation and muscle recovery.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Limbs',
    idealFor: 'Circulation support',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Compression-based therapy',
    postTreatmentNotes: 'Increased blood flow sensation.',
    recommendedAddOns: 'Cold therapy',
    whatToExpect:
      'Rhythmic compression techniques improving circulation and muscle recovery.',
    imageThumbnail: '',
  },
  {
    name: 'Active Release Therapy',
    shortDescription: 'Combines targeted pressure with client movement to release tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Restricted muscles',
    idealFor: 'Athletes, active clients',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Movement-integrated therapy',
    postTreatmentNotes: 'Improved functional movement.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Combines targeted pressure with client movement to release tension.',
    imageThumbnail: '',
  },
  {
    name: 'Joint Mobilization Therapy',
    shortDescription: 'Improves joint flexibility through controlled manual techniques.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light–Medium ★★☆',
    focusAreas: 'Specific joints',
    idealFor: 'Joint stiffness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Gentle mobilization',
    postTreatmentNotes: 'Increased joint range.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Improves joint flexibility through controlled manual techniques.',
    imageThumbnail: '',
  },
  {
    name: 'Myoskeletal Alignment Therapy',
    shortDescription: 'Addresses muscular imbalance influencing skeletal alignment.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Structural imbalance',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Alignment-focused therapy',
    postTreatmentNotes: 'Postural improvement expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Addresses muscular imbalance influencing skeletal alignment.',
    imageThumbnail: '',
  },
  {
    name: 'Clinical Trigger Release Therapy',
    shortDescription: 'Precise work targeting specific pain points and muscular knots.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Trigger points',
    idealFor: 'Muscle tightness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Direct pressure release',
    postTreatmentNotes: 'Temporary tenderness possible.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'Precise work targeting specific pain points and muscular knots.',
    imageThumbnail: '',
  },
  {
    name: 'Therapeutic Full Body Reset',
    shortDescription: 'Comprehensive therapeutic session improving muscular balance and comfort.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'General muscular fatigue',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Structured therapeutic massage',
    postTreatmentNotes: 'Deep relaxation expected.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Comprehensive therapeutic session improving muscular balance and comfort.',
    imageThumbnail: '',
  },
  {
    name: 'Corrective Posture Massage',
    shortDescription: 'Improves muscle tension patterns contributing to poor posture.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back, shoulders',
    idealFor: 'Slouching posture',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Postural corrective therapy',
    postTreatmentNotes: 'Improved alignment awareness.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Improves muscle tension patterns contributing to poor posture.',
    imageThumbnail: '',
  },
  {
    name: 'Advanced Deep Tissue Therapy',
    shortDescription: 'Intensive session addressing deep chronic tension patterns.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Very Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Severe muscle tightness',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Advanced deep tissue techniques',
    postTreatmentNotes: 'Soreness possible for 24–48 hours.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Intensive session addressing deep chronic tension patterns.',
    imageThumbnail: '',
  },
  {
    name: 'Rehabilitation Maintenance Massage',
    shortDescription: 'Ongoing supportive therapy maintaining recovery progress.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Previously injured area',
    idealFor: 'Long-term recovery',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Maintenance therapy',
    postTreatmentNotes: 'Sustained mobility expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Ongoing supportive therapy maintaining recovery progress.',
    imageThumbnail: '',
  },
  {
    name: 'Precision Pain Relief Therapy',
    shortDescription: 'Highly focused work addressing localized discomfort.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Specific pain zones',
    idealFor: 'Targeted muscular pain',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Clinical targeted therapy',
    postTreatmentNotes: 'Gradual pain reduction.',
    recommendedAddOns: 'Heat therapy',
    whatToExpect:
      'Highly focused work addressing localized discomfort.',
    imageThumbnail: '',
  },
  {
    name: 'Corrective Soft Tissue Therapy',
    shortDescription: 'Improves soft tissue flexibility and functional movement patterns.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Soft tissue structures',
    idealFor: 'Movement restriction',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured corrective therapy',
    postTreatmentNotes: 'Increased flexibility.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Improves soft tissue flexibility and functional movement patterns.',
    imageThumbnail: '',
  },
  {
    name: 'Structural Balance Therapy',
    shortDescription: 'A holistic corrective approach addressing muscular asymmetry.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Long-term posture correction',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Structural integration therapy',
    postTreatmentNotes: 'Improved alignment and balance.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A holistic corrective approach addressing muscular asymmetry.',
    imageThumbnail: '',
  },
];
