/**
 * Head / Scalp Massage directory entries.
 * Display rule: Massage Places Directory and Therapist Home Service (both).
 */

export interface HeadScalpMassageDirectoryEntry {
  name: string;
  shortDescription: string;
  recommendedDuration: string;
  pressureLevel: string;
  focusAreas: string;
  idealFor: string;
  suggestedFrequency: string;
  techniqueStyle: string;
  postTreatmentNotes: string;
  recommendedAddOns: string;
  whatToExpect: string;
  imageThumbnail: string;
}

export function getHeadScalpMassagePopupContent(serviceName: string): string | null {
  const entry = HEAD_SCALP_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (serviceName || '').toLowerCase().trim()
  );
  if (!entry) return null;
  const parts: string[] = [
    'What to Expect:',
    entry.whatToExpect,
    '',
    `Recommended Duration: ${entry.recommendedDuration}`,
    `Pressure Level: ${entry.pressureLevel}`,
    `Focus Areas: ${entry.focusAreas}`,
    `Ideal For: ${entry.idealFor}`,
    `Suggested Frequency: ${entry.suggestedFrequency}`,
    `Technique Style: ${entry.techniqueStyle}`,
    `Post-Treatment Notes: ${entry.postTreatmentNotes}`,
    `Recommended Add-Ons: ${entry.recommendedAddOns}`,
  ];
  return parts.join('\n');
}

export function getHeadScalpMassageEntry(name: string): HeadScalpMassageDirectoryEntry | undefined {
  return HEAD_SCALP_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (name || '').toLowerCase().trim()
  );
}

export const HEAD_SCALP_MASSAGE_DIRECTORY_NAMES = [
  'Serenity Scalp Flow',
  'Tension Release Head Therapy',
  'Mindful Calm Head Massage',
  'Energizing Scalp Revive',
  'Tranquil Crown Massage',
  'Blissful Head Escape',
  'Royal Scalp Ritual',
  'Zen Head & Shoulder Flow',
  'Soothing Mind Release',
  'Vital Energy Head Therapy',
  'Crown Rejuvenation Therapy',
  'Mind Escape Scalp Massage',
  'Energizing Crown Therapy',
  'Tranquil Mind Head Massage',
  'Blissful Crown Escape',
  'Royal Head Revive',
  'Zen Crown & Neck Flow',
  'Soothing Mind Release Therapy',
  'Vital Crown Energy',
  'Mind Clarity Scalp Therapy',
  'Tranquil Crown Escape',
  'Royal Mind Revive',
  'Blissful Crown Therapy',
  'Mindful Crown Flow',
  'Energizing Head Awakening',
  'Soothing Crown Ritual',
  'Crown Clarity Therapy',
  'Tranquil Mind Escape',
  'Blissful Head Flow',
  'Royal Mind Flow',
  'Mindful Crown Therapy',
  'Tranquil Crown Flow',
  'Blissful Mind Release',
  'Royal Crown Relaxation',
  'Mind Clarity Crown Massage',
  'Crown Renewal Therapy',
  'Tranquil Mind Crown',
  'Blissful Crown Awakening',
  'Soothing Crown Flow',
  'Royal Mind Flow Signature',
  'Mindful Head Harmony',
  'Tranquil Crown Relief',
  'Blissful Mind Flow',
  'Royal Head Revival',
  'Crown Calm Therapy',
  'Mind Renewal Head Massage',
  'Tranquil Mind Awakening',
  'Blissful Crown Energy',
  'Soothing Crown Escape',
  'Royal Mind Serenity',
] as const;

export const HEAD_SCALP_MASSAGE_DIRECTORY_ENTRIES: HeadScalpMassageDirectoryEntry[] = [
  {
    name: 'Serenity Scalp Flow',
    shortDescription: 'A gentle, flowing scalp massage to release tension from the head, neck, and shoulders. Improves circulation and promotes deep mental relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Stress relief, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage with gentle kneading and light acupressure',
    postTreatmentNotes: 'Reduced tension, clearer mind, relaxed muscles',
    recommendedAddOns: 'Aromatherapy, warm scalp oil',
    whatToExpect: 'A gentle, flowing scalp massage designed to release tension from the head, neck, and shoulders. Improves circulation and promotes deep mental relaxation. Perfect for reducing stress and calming the mind.',
    imageThumbnail: '',
  },
  {
    name: 'Tension Release Head Therapy',
    shortDescription: 'Targets tension points in the scalp, base of the skull, and temples. Gentle to medium pressure eases headaches and encourages mental clarity.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Headaches, eye strain, stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Acupressure, kneading, light stretches',
    postTreatmentNotes: 'Head feels lighter, reduced tension',
    recommendedAddOns: 'Aromatherapy, warm compress',
    whatToExpect: 'Targets tension points in the scalp, base of the skull, and temples. Gentle to medium pressure melts away knots and eases headaches. Encourages mental clarity and calmness.',
    imageThumbnail: '',
  },
  {
    name: 'Mindful Calm Head Massage',
    shortDescription: 'Relaxing scalp and neck massage with gentle temple strokes. Reduces mental stress and induces a meditative state.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, mental clarity',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Gentle scalp massage, acupressure, aromatherapy',
    postTreatmentNotes: 'Calm mind, reduced tension, refreshed',
    recommendedAddOns: 'Essential oils, eye mask',
    whatToExpect: 'A relaxing scalp and neck massage combined with gentle temple strokes. Reduces mental stress and induces a meditative state. Ideal for high-stress lifestyles.',
    imageThumbnail: '',
  },
  {
    name: 'Energizing Scalp Revive',
    shortDescription: 'Stimulates scalp circulation to invigorate the senses and improve alertness. Medium pressure encourages blood flow while reducing neck and shoulder tension.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders',
    idealFor: 'Fatigue, sluggishness, mental clarity',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage, acupressure points, shoulder kneading',
    postTreatmentNotes: 'Energized, refreshed, lighter head',
    recommendedAddOns: 'Peppermint oil, hot towel compress',
    whatToExpect: 'Stimulates scalp circulation to invigorate the senses and improve alertness. Medium pressure encourages blood flow while reducing neck and shoulder tension.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Crown Massage',
    shortDescription: 'Focuses on the top of the head and temples to relieve built-up stress and tension. Light, soothing strokes enhance relaxation and mental clarity.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Crown, temples, neck',
    idealFor: 'Stress relief, mental relaxation',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage, temple pressure points',
    postTreatmentNotes: 'Relaxed head and neck, reduced headaches',
    recommendedAddOns: 'Aromatherapy, warm scalp oil',
    whatToExpect: 'Focuses on the top of the head and temples to relieve built-up stress and tension. Light, soothing strokes enhance relaxation and mental clarity.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Head Escape',
    shortDescription: 'A calming session focusing on scalp, temples, and upper neck. Perfect for tension headaches or long hours at a computer. Induces deep relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Headaches, stress, eye strain',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Gentle kneading, light acupressure, aromatherapy',
    postTreatmentNotes: 'Clearer mind, relaxed head and shoulders',
    recommendedAddOns: 'Eye mask, warm oil',
    whatToExpect: 'A calming session focusing on scalp, temples, and upper neck. Perfect for clients with tension headaches or long hours at a computer. Induces deep relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Scalp Ritual',
    shortDescription: 'Luxurious scalp massage using warm oils to deeply relax the head, neck, and shoulders. Medium pressure stimulates circulation while soothing tension.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders',
    idealFor: 'Stress relief, hair nourishment, mental clarity',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Hot oil scalp massage, kneading, acupressure',
    postTreatmentNotes: 'Relaxed, calm, refreshed',
    recommendedAddOns: 'Aromatherapy, hot towel wrap',
    whatToExpect: 'Luxurious scalp massage using warm oils to deeply relax the head, neck, and shoulders. Medium pressure stimulates circulation while soothing tension.',
    imageThumbnail: '',
  },
  {
    name: 'Zen Head & Shoulder Flow',
    shortDescription: 'Combines scalp massage with shoulder and upper back techniques. Medium pressure eases tension, relieves headaches, and improves posture.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, upper back',
    idealFor: 'Office workers, tension headaches',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage + shoulder/upper back kneading',
    postTreatmentNotes: 'Relaxed upper body, reduced headaches',
    recommendedAddOns: 'Aromatherapy, warm compress',
    whatToExpect: 'Combines scalp massage with shoulder and upper back techniques. Medium pressure eases tension, relieves headaches, and improves posture.',
    imageThumbnail: '',
  },
  {
    name: 'Soothing Mind Release',
    shortDescription: 'A deeply relaxing head massage targeting key acupressure points. Light strokes relieve tension and stress while calming the nervous system.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp acupressure and gentle kneading',
    postTreatmentNotes: 'Relaxed head, reduced mental fatigue',
    recommendedAddOns: 'Essential oils, warm compress',
    whatToExpect: 'A deeply relaxing head massage that targets key acupressure points. Light strokes relieve tension and stress while calming the nervous system.',
    imageThumbnail: '',
  },
  {
    name: 'Vital Energy Head Therapy',
    shortDescription: 'Stimulates circulation through medium-pressure scalp massage and reflexology points. Ideal for mental fatigue and improving alertness.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Fatigue, stress, sluggishness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp reflexology + shoulder massage',
    postTreatmentNotes: 'Energized, mental clarity improved',
    recommendedAddOns: 'Aromatherapy, peppermint oil',
    whatToExpect: 'Stimulates circulation through medium-pressure scalp massage and reflexology points. Ideal for mental fatigue and improving alertness.',
    imageThumbnail: '',
  },
  {
    name: 'Crown Rejuvenation Therapy',
    shortDescription: 'A nurturing scalp massage that improves circulation, eases tension, and promotes mental clarity. Light to medium strokes relax the head, neck, and shoulders.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress, tension headaches',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage with gentle kneading and acupressure',
    postTreatmentNotes: 'Relaxed head and shoulders, refreshed mind',
    recommendedAddOns: 'Aromatherapy, warm scalp oil',
    whatToExpect: 'A nurturing scalp massage that improves circulation, eases tension, and promotes mental clarity. Light to medium strokes relax the head, neck, and shoulders.',
    imageThumbnail: '',
  },
  {
    name: 'Mind Escape Scalp Massage',
    shortDescription: 'A calming head massage focusing on temples, crown, and neck. Helps release mental fatigue, soothe headaches, and improve relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, mental clarity',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Gentle scalp strokes with acupressure points',
    postTreatmentNotes: 'Calmed mind, reduced tension',
    recommendedAddOns: 'Essential oils, eye mask',
    whatToExpect: 'A calming head massage focusing on temples, crown, and neck. Helps release mental fatigue, soothe headaches, and improve relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Energizing Crown Therapy',
    shortDescription: 'Medium-pressure massage designed to invigorate the scalp and upper neck. Stimulates circulation and reduces mental fatigue.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, temples, shoulders',
    idealFor: 'Fatigue, sluggishness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp acupressure, shoulder kneading',
    postTreatmentNotes: 'Energized and alert',
    recommendedAddOns: 'Peppermint oil, hot towel',
    whatToExpect: 'Medium-pressure massage designed to invigorate the scalp and upper neck. Stimulates circulation and reduces mental fatigue.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Mind Head Massage',
    shortDescription: 'Focuses on reducing tension and stress in the head and neck. Light, flowing strokes encourage deep relaxation and mental calm.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Stress, anxiety, tension headaches',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Gentle scalp massage, temple acupressure',
    postTreatmentNotes: 'Reduced tension, mental clarity',
    recommendedAddOns: 'Aromatherapy, warm compress',
    whatToExpect: 'Focuses on reducing tension and stress in the head and neck. Light, flowing strokes encourage deep relaxation and mental calm.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Crown Escape',
    shortDescription: 'A soothing session targeting scalp and temples with gentle strokes. Relieves headaches and improves relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure',
    postTreatmentNotes: 'Calm mind, relaxed head and shoulders',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'A soothing session targeting scalp and temples with gentle strokes. Relieves headaches and improves relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Head Revive',
    shortDescription: 'A luxurious scalp massage using warm oils and medium pressure. Reduces tension, promotes circulation, and leaves the client feeling refreshed.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders',
    idealFor: 'Stress, headaches, fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Hot oil scalp massage, acupressure',
    postTreatmentNotes: 'Relaxed muscles, energized mind',
    recommendedAddOns: 'Hot towel, essential oils',
    whatToExpect: 'A luxurious scalp massage using warm oils and medium pressure. Reduces tension, promotes circulation, and leaves the client feeling refreshed.',
    imageThumbnail: '',
  },
  {
    name: 'Zen Crown & Neck Flow',
    shortDescription: 'Integrates scalp massage with upper neck and shoulder techniques. Medium pressure relieves tension and promotes circulation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders',
    idealFor: 'Headaches, neck tension, stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage + upper back kneading',
    postTreatmentNotes: 'Relaxed upper body, mental clarity',
    recommendedAddOns: 'Aromatherapy, warm compress',
    whatToExpect: 'Integrates scalp massage with upper neck and shoulder techniques. Medium pressure relieves tension and promotes circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Soothing Mind Release Therapy',
    shortDescription: 'Gentle scalp massage focusing on acupressure points. Calms the nervous system and releases mental tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Acupressure, gentle kneading',
    postTreatmentNotes: 'Relaxed head, reduced fatigue',
    recommendedAddOns: 'Aromatherapy, warm oil',
    whatToExpect: 'Gentle scalp massage focusing on acupressure points. Calms the nervous system and releases mental tension.',
    imageThumbnail: '',
  },
  {
    name: 'Vital Crown Energy',
    shortDescription: 'Medium-pressure scalp massage designed to stimulate circulation and improve alertness. Includes gentle shoulder work.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Mental fatigue, sluggishness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp reflexology + shoulder massage',
    postTreatmentNotes: 'Energized, alert, relaxed',
    recommendedAddOns: 'Peppermint oil, hot towel',
    whatToExpect: 'Medium-pressure scalp massage designed to stimulate circulation and improve alertness. Includes gentle shoulder work.',
    imageThumbnail: '',
  },
  {
    name: 'Mind Clarity Scalp Therapy',
    shortDescription: 'Combines gentle scalp massage and acupressure for tension relief. Encourages calmness, focus, and mental clarity.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Stress, headaches, mental fatigue',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, temple acupressure',
    postTreatmentNotes: 'Relaxed head and shoulders, clear mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Combines gentle scalp massage and acupressure for tension relief. Encourages calmness, focus, and mental clarity.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Crown Escape',
    shortDescription: 'Gentle, flowing strokes targeting the scalp, temples, and neck. Reduces tension headaches and mental fatigue while promoting deep relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, mental clarity',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure',
    postTreatmentNotes: 'Relaxed head and shoulders, calm mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Gentle, flowing strokes targeting the scalp, temples, and neck. Reduces tension headaches and mental fatigue while promoting deep relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Mind Revive',
    shortDescription: 'A luxurious scalp massage with warm oils and medium pressure. Eases tension, improves circulation, and refreshes the mind.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders',
    idealFor: 'Stress, fatigue, headaches',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Hot oil massage, acupressure, gentle kneading',
    postTreatmentNotes: 'Energized, relaxed, mental clarity',
    recommendedAddOns: 'Aromatherapy, hot towel',
    whatToExpect: 'A luxurious scalp massage with warm oils and medium pressure. Eases tension, improves circulation, and refreshes the mind.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Crown Therapy',
    shortDescription: 'Focuses on scalp, temples, and neck to release tension and induce calm. Gentle to medium pressure promotes relaxation and mental clarity.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Stress, headaches',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage, acupressure, gentle stretches',
    postTreatmentNotes: 'Calm, refreshed, relaxed',
    recommendedAddOns: 'Essential oils, eye mask',
    whatToExpect: 'Focuses on scalp, temples, and neck to release tension and induce calm. Gentle to medium pressure promotes relaxation and mental clarity.',
    imageThumbnail: '',
  },
  {
    name: 'Mindful Crown Flow',
    shortDescription: 'Light, rhythmic scalp strokes combined with gentle neck massage. Reduces stress and improves circulation to the head and shoulders.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Stress, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure',
    postTreatmentNotes: 'Relaxed mind, reduced tension',
    recommendedAddOns: 'Aromatherapy, warm compress',
    whatToExpect: 'Light, rhythmic scalp strokes combined with gentle neck massage. Reduces stress and improves circulation to the head and shoulders.',
    imageThumbnail: '',
  },
  {
    name: 'Energizing Head Awakening',
    shortDescription: 'Medium-pressure scalp massage designed to invigorate the senses and improve alertness. Includes upper neck and shoulder stimulation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Fatigue, mental exhaustion',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp reflexology, shoulder kneading',
    postTreatmentNotes: 'Energized, refreshed, mental clarity',
    recommendedAddOns: 'Peppermint oil, hot towel',
    whatToExpect: 'Medium-pressure scalp massage designed to invigorate the senses and improve alertness. Includes upper neck and shoulder stimulation.',
    imageThumbnail: '',
  },
  {
    name: 'Soothing Crown Ritual',
    shortDescription: 'A gentle, nurturing massage focusing on scalp, temples, and neck. Relieves tension and encourages calmness and mental relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Stress relief, headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure, aromatherapy',
    postTreatmentNotes: 'Relaxed, refreshed, calm mind',
    recommendedAddOns: 'Eye mask, warm oil',
    whatToExpect: 'A gentle, nurturing massage focusing on scalp, temples, and neck. Relieves tension and encourages calmness and mental relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Crown Clarity Therapy',
    shortDescription: 'Medium-pressure massage that stimulates scalp circulation, relieves tension, and enhances mental focus. Perfect for mental fatigue or work stress.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, temples, neck, shoulders',
    idealFor: 'Headaches, fatigue, stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage + acupressure + shoulder kneading',
    postTreatmentNotes: 'Clear mind, reduced tension',
    recommendedAddOns: 'Peppermint oil, hot towel',
    whatToExpect: 'Medium-pressure massage that stimulates scalp circulation, relieves tension, and enhances mental focus. Perfect for mental fatigue or work stress.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Mind Escape',
    shortDescription: 'Gentle massage targeting scalp and upper neck. Light strokes ease tension, reduce headaches, and encourage relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Stress, headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure points',
    postTreatmentNotes: 'Relaxed head and neck, mental calm',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Gentle massage targeting scalp and upper neck. Light strokes ease tension, reduce headaches, and encourage relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Head Flow',
    shortDescription: 'Smooth, rhythmic strokes across the scalp and temples. Reduces tension, improves circulation, and promotes a sense of calm and well-being.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress, headaches, fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage, gentle acupressure',
    postTreatmentNotes: 'Relaxed, refreshed, mental clarity',
    recommendedAddOns: 'Aromatherapy, warm compress',
    whatToExpect: 'Smooth, rhythmic strokes across the scalp and temples. Reduces tension, improves circulation, and promotes a sense of calm and well-being.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Mind Flow',
    shortDescription: 'Luxurious medium-pressure massage targeting scalp, neck, and shoulders. Relieves tension, improves circulation, and leaves the client feeling energized.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Stress relief, headaches, mental fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Hot oil scalp massage, acupressure, shoulder kneading',
    postTreatmentNotes: 'Relaxed body, refreshed mind',
    recommendedAddOns: 'Aromatherapy, hot towel wrap',
    whatToExpect: 'Luxurious medium-pressure massage targeting scalp, neck, and shoulders. Relieves tension, improves circulation, and leaves the client feeling energized.',
    imageThumbnail: '',
  },
  {
    name: 'Mindful Crown Therapy',
    shortDescription: 'Gentle scalp massage with light pressure, focusing on temples, crown, and neck. Reduces tension and promotes mental clarity and relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage with acupressure points',
    postTreatmentNotes: 'Relaxed head, calm mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Gentle scalp massage with light pressure, focusing on temples, crown, and neck. Reduces tension and promotes mental clarity and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Crown Flow',
    shortDescription: 'A soothing scalp and neck massage designed to melt away stress and mental fatigue. Medium pressure promotes circulation and relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, temples, shoulders',
    idealFor: 'Headaches, fatigue, stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp kneading, acupressure, shoulder massage',
    postTreatmentNotes: 'Clear mind, reduced tension',
    recommendedAddOns: 'Peppermint oil, hot towel',
    whatToExpect: 'A soothing scalp and neck massage designed to melt away stress and mental fatigue. Medium pressure promotes circulation and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Mind Release',
    shortDescription: 'Soft, flowing strokes across the scalp, temples, and neck. Encourages mental calm, reduces stress, and alleviates tension headaches.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress, mental fatigue, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure',
    postTreatmentNotes: 'Relaxed head and shoulders, mental clarity',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Soft, flowing strokes across the scalp, temples, and neck. Encourages mental calm, reduces stress, and alleviates tension headaches.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Crown Relaxation',
    shortDescription: 'Medium-pressure scalp massage with warm oils. Reduces tension in the head, neck, and shoulders while enhancing mental clarity.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders',
    idealFor: 'Stress relief, fatigue, headaches',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Hot oil massage, acupressure, gentle kneading',
    postTreatmentNotes: 'Relaxed, energized, refreshed mind',
    recommendedAddOns: 'Aromatherapy, hot towel',
    whatToExpect: 'Medium-pressure scalp massage with warm oils. Reduces tension in the head, neck, and shoulders while enhancing mental clarity.',
    imageThumbnail: '',
  },
  {
    name: 'Mind Clarity Crown Massage',
    shortDescription: 'A gentle scalp massage combined with acupressure on temples and neck. Eases tension, improves focus, and calms the mind.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress, headaches, mental fatigue',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage and temple acupressure',
    postTreatmentNotes: 'Relaxed head, calm mind',
    recommendedAddOns: 'Aromatherapy, warm compress',
    whatToExpect: 'A gentle scalp massage combined with acupressure on temples and neck. Eases tension, improves focus, and calms the mind.',
    imageThumbnail: '',
  },
  {
    name: 'Crown Renewal Therapy',
    shortDescription: 'Medium-pressure scalp massage focusing on tension points in the crown, temples, and neck. Stimulates circulation and mental clarity.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, temples, neck, shoulders',
    idealFor: 'Fatigue, tension, stress relief',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage, acupressure, shoulder kneading',
    postTreatmentNotes: 'Energized, relaxed, mental clarity improved',
    recommendedAddOns: 'Peppermint oil, hot towel',
    whatToExpect: 'Medium-pressure scalp massage focusing on tension points in the crown, temples, and neck. Stimulates circulation and mental clarity.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Mind Crown',
    shortDescription: 'Light, flowing strokes across the scalp and temples to relieve tension headaches and mental stress. Ideal for relaxation and mental balance.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage with acupressure',
    postTreatmentNotes: 'Relaxed head, calm mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Light, flowing strokes across the scalp and temples to relieve tension headaches and mental stress. Ideal for relaxation and mental balance.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Crown Awakening',
    shortDescription: 'Medium-pressure scalp massage that energizes and refreshes the mind. Focused on reducing tension and stimulating circulation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, temples, shoulders',
    idealFor: 'Fatigue, stress, mental clarity',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp reflexology + shoulder massage',
    postTreatmentNotes: 'Energized, clear-headed, relaxed',
    recommendedAddOns: 'Peppermint oil, hot towel',
    whatToExpect: 'Medium-pressure scalp massage that energizes and refreshes the mind. Focused on reducing tension and stimulating circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Soothing Crown Flow',
    shortDescription: 'Gentle scalp and neck massage that relieves tension and reduces headaches. Encourages mental calm and relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, neck, temples',
    idealFor: 'Stress, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure',
    postTreatmentNotes: 'Relaxed, calm mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Gentle scalp and neck massage that relieves tension and reduces headaches. Encourages mental calm and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Mind Flow Signature',
    shortDescription: 'Luxurious medium-pressure scalp massage combined with shoulder and neck kneading. Relieves tension, improves circulation, and promotes mental clarity.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Stress, headaches, mental fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Hot oil massage, acupressure, shoulder kneading',
    postTreatmentNotes: 'Relaxed, refreshed, energized',
    recommendedAddOns: 'Aromatherapy, hot towel',
    whatToExpect: 'Luxurious medium-pressure scalp massage combined with shoulder and neck kneading. Relieves tension, improves circulation, and promotes mental clarity.',
    imageThumbnail: '',
  },
  {
    name: 'Mindful Head Harmony',
    shortDescription: 'Gentle, flowing strokes across the scalp, temples, and neck. Reduces stress and tension while promoting mental clarity and relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage with acupressure points',
    postTreatmentNotes: 'Relaxed head, calm mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Gentle, flowing strokes across the scalp, temples, and neck. Reduces stress and tension while promoting mental clarity and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Crown Relief',
    shortDescription: 'Medium-pressure massage focusing on scalp and upper neck. Relieves tension, reduces headaches, and improves circulation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders',
    idealFor: 'Tension headaches, stress, fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage + shoulder kneading',
    postTreatmentNotes: 'Relaxed, energized, reduced tension',
    recommendedAddOns: 'Peppermint oil, warm towel',
    whatToExpect: 'Medium-pressure massage focusing on scalp and upper neck. Relieves tension, reduces headaches, and improves circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Mind Flow',
    shortDescription: 'Soft scalp massage combined with light acupressure on temples and neck. Promotes calm, reduces stress, and improves mental clarity.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Gentle kneading, acupressure',
    postTreatmentNotes: 'Relaxed head, clear mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Soft scalp massage combined with light acupressure on temples and neck. Promotes calm, reduces stress, and improves mental clarity.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Head Revival',
    shortDescription: 'Luxurious medium-pressure scalp massage with warm oils. Reduces tension, stimulates circulation, and refreshes the mind and shoulders.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Stress relief, fatigue, headaches',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Hot oil massage, acupressure, shoulder kneading',
    postTreatmentNotes: 'Relaxed, energized, refreshed',
    recommendedAddOns: 'Aromatherapy, hot towel',
    whatToExpect: 'Luxurious medium-pressure scalp massage with warm oils. Reduces tension, stimulates circulation, and refreshes the mind and shoulders.',
    imageThumbnail: '',
  },
  {
    name: 'Crown Calm Therapy',
    shortDescription: 'Gentle strokes across the scalp, temples, and neck to relieve stress and tension. Encourages deep relaxation and mental clarity.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure',
    postTreatmentNotes: 'Calm, relaxed, refreshed',
    recommendedAddOns: 'Aromatherapy, warm compress',
    whatToExpect: 'Gentle strokes across the scalp, temples, and neck to relieve stress and tension. Encourages deep relaxation and mental clarity.',
    imageThumbnail: '',
  },
  {
    name: 'Mind Renewal Head Massage',
    shortDescription: 'Medium-pressure scalp massage with gentle shoulder kneading. Improves circulation, reduces tension, and refreshes the mind.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Fatigue, stress, headaches',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp massage, acupressure, shoulder massage',
    postTreatmentNotes: 'Relaxed, energized, calm mind',
    recommendedAddOns: 'Aromatherapy, peppermint oil',
    whatToExpect: 'Medium-pressure scalp massage with gentle shoulder kneading. Improves circulation, reduces tension, and refreshes the mind.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Mind Awakening',
    shortDescription: 'Light, soothing strokes across the scalp, temples, and neck. Reduces tension headaches and promotes mental clarity and calm.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress relief, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure',
    postTreatmentNotes: 'Relaxed head, calm mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Light, soothing strokes across the scalp, temples, and neck. Reduces tension headaches and promotes mental clarity and calm.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Crown Energy',
    shortDescription: 'Medium-pressure scalp massage that stimulates circulation, reduces tension, and energizes the mind. Includes neck and shoulder work.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Mental fatigue, stress, sluggishness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Scalp reflexology + shoulder massage',
    postTreatmentNotes: 'Energized, refreshed, relaxed',
    recommendedAddOns: 'Peppermint oil, hot towel',
    whatToExpect: 'Medium-pressure scalp massage that stimulates circulation, reduces tension, and energizes the mind. Includes neck and shoulder work.',
    imageThumbnail: '',
  },
  {
    name: 'Soothing Crown Escape',
    shortDescription: 'Soft, gentle massage targeting the scalp, temples, and upper neck. Relieves tension, headaches, and promotes mental calm.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Scalp, temples, neck',
    idealFor: 'Stress, tension headaches',
    suggestedFrequency: '1–2x weekly',
    techniqueStyle: 'Scalp massage, acupressure',
    postTreatmentNotes: 'Relaxed head and shoulders, calm mind',
    recommendedAddOns: 'Aromatherapy, eye mask',
    whatToExpect: 'Soft, gentle massage targeting the scalp, temples, and upper neck. Relieves tension, headaches, and promotes mental calm.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Mind Serenity',
    shortDescription: 'A luxurious medium-pressure scalp massage with hot oil. Combines scalp, neck, and shoulder work to reduce tension, improve circulation, and refresh the mind.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Scalp, neck, shoulders, temples',
    idealFor: 'Stress relief, headaches, fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Hot oil massage, acupressure, shoulder kneading',
    postTreatmentNotes: 'Relaxed, refreshed, calm and energized',
    recommendedAddOns: 'Aromatherapy, hot towel',
    whatToExpect: 'A luxurious medium-pressure scalp massage with hot oil. Combines scalp, neck, and shoulder work to reduce tension, improve circulation, and refresh the mind.',
    imageThumbnail: '',
  },
];
