/**
 * Body Scrub & Exfoliation directory entries.
 * Place directory only — NOT available for Home Service providers.
 * Display rule: Massage Places Directory only; must NOT be available for Home Service.
 */

export interface BodyScrubMassageDirectoryEntry {
  name: string;
  shortDescription: string;
  recommendedDuration: string;
  pressureLevel: string;
  focusAreas: string;
  idealFor: string;
  suggestedFrequency: string;
  techniqueStyle: string;
  postTreatmentNotes: string;
  recommendedAddOns: string;
  whatToExpect: string;
  imageThumbnail: string;
}

export function getBodyScrubMassagePopupContent(serviceName: string): string | null {
  const entry = BODY_SCRUB_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (serviceName || '').toLowerCase().trim()
  );
  if (!entry) return null;
  const parts: string[] = [
    'What to Expect:',
    entry.whatToExpect,
    '',
    `Recommended Duration: ${entry.recommendedDuration}`,
    `Pressure Level: ${entry.pressureLevel}`,
    `Focus Areas: ${entry.focusAreas}`,
    `Ideal For: ${entry.idealFor}`,
    `Suggested Frequency: ${entry.suggestedFrequency}`,
    `Technique Style: ${entry.techniqueStyle}`,
    `Post-Treatment Notes: ${entry.postTreatmentNotes}`,
    `Recommended Add-Ons: ${entry.recommendedAddOns}`,
  ];
  return parts.join('\n');
}

export function getBodyScrubMassageEntry(name: string): BodyScrubMassageDirectoryEntry | undefined {
  return BODY_SCRUB_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (name || '').toLowerCase().trim()
  );
}

export const BODY_SCRUB_DIRECTORY_NAMES = [
  'Tropical Sugar Glow Scrub',
  'Ocean Salt Renewal Scrub',
  'Coffee Bean Energizing Scrub',
  'Himalayan Salt Detox Scrub',
  'Lavender Aromatic Body Scrub',
  'Cocoa Butter Smooth Scrub',
  'Green Tea Revitalizing Scrub',
  'Tropical Coconut Scrub',
  'Rose Petal Glow Scrub',
  'Mint & Eucalyptus Invigorating Scrub',
  'Vanilla Bean Hydrating Scrub',
  'Honey Almond Glow Scrub',
  'Coffee & Cocoa Energy Scrub',
  'Lavender & Chamomile Calm Scrub',
  'Citrus Sunshine Scrub',
  'Seaweed Mineral Body Scrub',
  'Exotic Papaya Enzyme Scrub',
  'Tropical Pineapple Brightening Scrub',
  'Mint & Sea Salt Revive Scrub',
  'Coconut & Lime Energizing Scrub',
  'Vanilla & Brown Sugar Delight Scrub',
  'Himalayan Rose Salt Glow Scrub',
  'Aloe Vera Soothing Scrub',
  'Tropical Mango Smooth Scrub',
  'Coffee & Vanilla Energizing Scrub',
  'Honey & Oatmeal Gentle Scrub',
  'Citrus & Ginger Revitalizing Scrub',
  'Lavender & Sea Salt Calm Scrub',
  'Tropical Papaya & Pineapple Scrub',
  'Mint & Lemon Cooling Scrub',
  'Shea Butter & Brown Sugar Scrub',
  'Almond & Honey Nourishing Scrub',
  'Coffee & Mint Invigorating Scrub',
  'Tropical Coconut Lime Scrub',
  'Rose Quartz Glow Scrub',
  'Papaya & Coconut Enzyme Scrub',
  'Chocolate & Coffee Body Polish',
  'Citrus & Sugar Glow Scrub',
  'Green Tea & Mint Refresh Scrub',
  'Lavender & Honey Calming Scrub',
  'Mango & Papaya Tropical Glow Scrub',
  'Cocoa & Vanilla Indulgence Scrub',
  'Sea Salt & Aloe Hydration Scrub',
  'Coffee & Orange Energizing Scrub',
  'Lavender & Chamomile Relaxing Scrub',
  'Peppermint & Sugar Cooling Scrub',
  'Rose & Almond Luxurious Scrub',
  'Tropical Pineapple & Coconut Scrub',
  'Himalayan Salt & Citrus Invigorating Scrub',
  'Gold & Honey Luxury Body Polish',
] as const;

export const BODY_SCRUB_DIRECTORY_ENTRIES: BodyScrubMassageDirectoryEntry[] = [
  {
    name: 'Tropical Sugar Glow Scrub',
    shortDescription: 'A revitalizing sugar-based scrub that exfoliates dead skin cells and leaves the body soft, hydrated, and radiant.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry or dull skin, pre-event glow',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Sugar-based exfoliation with massage strokes',
    postTreatmentNotes: 'Smooth, hydrated skin; improved circulation',
    recommendedAddOns: 'Body butter application, aromatherapy',
    whatToExpect: 'A revitalizing sugar-based scrub that exfoliates dead skin cells and leaves the body soft, hydrated, and radiant. Gentle circular strokes improve circulation while nourishing oils protect the skin.',
    imageThumbnail: '',
  },
  {
    name: 'Ocean Salt Renewal Scrub',
    shortDescription: 'Sea salt exfoliation removes rough skin and stimulates circulation, leaving skin soft, refreshed, and energized.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Tired or rough skin',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Salt-based exfoliation',
    postTreatmentNotes: 'Refreshed, renewed skin',
    recommendedAddOns: 'Mineral body oil',
    whatToExpect: 'Sea salt exfoliation removes rough skin and stimulates circulation, leaving skin soft, refreshed, and energized.',
    imageThumbnail: '',
  },
  {
    name: 'Coffee Bean Energizing Scrub',
    shortDescription: 'Coffee grounds massage gently exfoliates, stimulates circulation, and energizes the body while leaving a subtle coffee scent.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Legs, arms, back',
    idealFor: 'Cellulite reduction, tired skin',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Coffee-based scrub with circular massage',
    postTreatmentNotes: 'Energized, smooth skin',
    recommendedAddOns: 'Coffee-infused body butter',
    whatToExpect: 'Coffee grounds massage gently exfoliates, stimulates circulation, and energizes the body while leaving a subtle coffee scent.',
    imageThumbnail: '',
  },
  {
    name: 'Himalayan Salt Detox Scrub',
    shortDescription: 'Natural Himalayan salt crystals gently polish skin and draw out impurities, improving circulation and skin texture.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Detoxifying skin, improving tone',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Salt-based exfoliation',
    postTreatmentNotes: 'Smoother, glowing skin',
    recommendedAddOns: 'Mineral oil or hydrating lotion',
    whatToExpect: 'Natural Himalayan salt crystals gently polish skin and draw out impurities, improving circulation and skin texture.',
    imageThumbnail: '',
  },
  {
    name: 'Lavender Aromatic Body Scrub',
    shortDescription: 'A calming lavender-infused scrub that exfoliates while soothing the mind and body with aromatherapy benefits.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stress relief, sensitive skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Gentle aromatic exfoliation',
    postTreatmentNotes: 'Soft, relaxed skin',
    recommendedAddOns: 'Lavender body oil',
    whatToExpect: 'A calming lavender-infused scrub that exfoliates while soothing the mind and body with aromatherapy benefits.',
    imageThumbnail: '',
  },
  {
    name: 'Cocoa Butter Smooth Scrub',
    shortDescription: 'Rich cocoa butter scrub exfoliates while deeply moisturizing, leaving skin soft and supple.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry or dehydrated skin',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Moisturizing body scrub',
    postTreatmentNotes: 'Soft, nourished skin',
    recommendedAddOns: 'Cocoa body cream',
    whatToExpect: 'Rich cocoa butter scrub exfoliates while deeply moisturizing, leaving skin soft and supple.',
    imageThumbnail: '',
  },
  {
    name: 'Green Tea Revitalizing Scrub',
    shortDescription: 'Green tea leaves exfoliate and deliver antioxidants to the skin, refreshing and rejuvenating the body.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Tired or dull skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Herbal exfoliation',
    postTreatmentNotes: 'Refreshed, revitalized skin',
    recommendedAddOns: 'Green tea infused lotion',
    whatToExpect: 'Green tea leaves exfoliate and deliver antioxidants to the skin, refreshing and rejuvenating the body.',
    imageThumbnail: '',
  },
  {
    name: 'Tropical Coconut Scrub',
    shortDescription: 'Coconut-based scrub exfoliates, nourishes, and hydrates the skin, leaving it soft with a tropical scent.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry skin, hydration boost',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Coconut oil exfoliation',
    postTreatmentNotes: 'Soft, silky skin',
    recommendedAddOns: 'Coconut body butter',
    whatToExpect: 'Coconut-based scrub exfoliates, nourishes, and hydrates the skin, leaving it soft with a tropical scent.',
    imageThumbnail: '',
  },
  {
    name: 'Rose Petal Glow Scrub',
    shortDescription: 'A delicate rose petal scrub that exfoliates while leaving a natural fragrance and hydrated, glowing skin.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or romantic-themed treatments',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Floral exfoliation',
    postTreatmentNotes: 'Smooth, fragrant skin',
    recommendedAddOns: 'Rose-scented body oil',
    whatToExpect: 'A delicate rose petal scrub that exfoliates while leaving a natural fragrance and hydrated, glowing skin.',
    imageThumbnail: '',
  },
  {
    name: 'Mint & Eucalyptus Invigorating Scrub',
    shortDescription: 'Refreshing mint and eucalyptus scrub energizes and exfoliates, leaving skin cooled and revitalized.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Legs, arms, back',
    idealFor: 'Fatigue and muscle refresh',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Cooling herbal scrub',
    postTreatmentNotes: 'Energized, fresh skin',
    recommendedAddOns: 'Mint-infused body lotion',
    whatToExpect: 'Refreshing mint and eucalyptus scrub energizes and exfoliates, leaving skin cooled and revitalized.',
    imageThumbnail: '',
  },
  {
    name: 'Vanilla Bean Hydrating Scrub',
    shortDescription: 'A gentle vanilla-infused scrub exfoliates and deeply hydrates the skin, leaving it soft, fragrant, and smooth.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry or sensitive skin',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Moisturizing exfoliation',
    postTreatmentNotes: 'Hydrated, soft skin',
    recommendedAddOns: 'Body butter application',
    whatToExpect: 'A gentle vanilla-infused scrub exfoliates and deeply hydrates the skin, leaving it soft, fragrant, and smooth.',
    imageThumbnail: '',
  },
  {
    name: 'Honey Almond Glow Scrub',
    shortDescription: 'A nourishing almond and honey scrub that exfoliates dead skin and moisturizes, leaving skin radiant.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dry or dull skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Nutritive exfoliation',
    postTreatmentNotes: 'Smooth and glowing skin',
    recommendedAddOns: 'Almond oil massage',
    whatToExpect: 'A nourishing almond and honey scrub that exfoliates dead skin and moisturizes, leaving skin radiant.',
    imageThumbnail: '',
  },
  {
    name: 'Coffee & Cocoa Energy Scrub',
    shortDescription: 'Coffee and cocoa grounds invigorate and exfoliate while promoting circulation and skin rejuvenation.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Legs, arms, back',
    idealFor: 'Fatigue, dull skin, cellulite-prone areas',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Stimulating scrub therapy',
    postTreatmentNotes: 'Energized, smoother skin',
    recommendedAddOns: 'Cocoa body cream',
    whatToExpect: 'Coffee and cocoa grounds invigorate and exfoliate while promoting circulation and skin rejuvenation.',
    imageThumbnail: '',
  },
  {
    name: 'Lavender & Chamomile Calm Scrub',
    shortDescription: 'A calming floral scrub using lavender and chamomile to gently exfoliate and soothe the skin and mind.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or stressed clients',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Aromatic gentle exfoliation',
    postTreatmentNotes: 'Relaxed and hydrated skin',
    recommendedAddOns: 'Lavender oil application',
    whatToExpect: 'A calming floral scrub using lavender and chamomile to gently exfoliate and soothe the skin and mind.',
    imageThumbnail: '',
  },
  {
    name: 'Citrus Sunshine Scrub',
    shortDescription: 'A zesty citrus scrub that exfoliates and refreshes the skin, promoting brightness and circulation.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dull or tired skin',
    suggestedFrequency: '2 times monthly',
    techniqueStyle: 'Citrus-based exfoliation',
    postTreatmentNotes: 'Glowing, revitalized skin',
    recommendedAddOns: 'Citrus body lotion',
    whatToExpect: 'A zesty citrus scrub that exfoliates and refreshes the skin, promoting brightness and circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Seaweed Mineral Body Scrub',
    shortDescription: 'Mineral-rich seaweed scrub exfoliates while replenishing nutrients and detoxifying the skin.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Detoxification and skin nourishment',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Mineral-enriched exfoliation',
    postTreatmentNotes: 'Soft, refreshed, and detoxed skin',
    recommendedAddOns: 'Seaweed wrap',
    whatToExpect: 'Mineral-rich seaweed scrub exfoliates while replenishing nutrients and detoxifying the skin.',
    imageThumbnail: '',
  },
  {
    name: 'Exotic Papaya Enzyme Scrub',
    shortDescription: 'Papaya enzymes gently dissolve dead skin while promoting natural skin renewal and hydration.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or uneven skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Enzyme-based exfoliation',
    postTreatmentNotes: 'Soft, glowing, refreshed skin',
    recommendedAddOns: 'Tropical body oil',
    whatToExpect: 'Papaya enzymes gently dissolve dead skin while promoting natural skin renewal and hydration.',
    imageThumbnail: '',
  },
  {
    name: 'Tropical Pineapple Brightening Scrub',
    shortDescription: 'A pineapple-based scrub exfoliates and brightens skin while stimulating circulation.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dull or tired skin',
    suggestedFrequency: '2 times monthly',
    techniqueStyle: 'Fruit enzyme exfoliation',
    postTreatmentNotes: 'Radiant and smooth skin',
    recommendedAddOns: 'Pineapple-scented body lotion',
    whatToExpect: 'A pineapple-based scrub exfoliates and brightens skin while stimulating circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Mint & Sea Salt Revive Scrub',
    shortDescription: 'Refreshing mint combined with sea salt exfoliates and cools tired muscles while softening skin.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back, legs, arms',
    idealFor: 'Fatigue, circulation boost',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Cooling herbal exfoliation',
    postTreatmentNotes: 'Invigorated, smooth skin',
    recommendedAddOns: 'Mint oil massage',
    whatToExpect: 'Refreshing mint combined with sea salt exfoliates and cools tired muscles while softening skin.',
    imageThumbnail: '',
  },
  {
    name: 'Coconut & Lime Energizing Scrub',
    shortDescription: 'Tropical coconut and lime scrub exfoliates and hydrates while leaving a refreshing scent.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Hydration and glow',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Coconut-lime scrub',
    postTreatmentNotes: 'Soft, nourished skin',
    recommendedAddOns: 'Coconut body butter',
    whatToExpect: 'Tropical coconut and lime scrub exfoliates and hydrates while leaving a refreshing scent.',
    imageThumbnail: '',
  },
  {
    name: 'Vanilla & Brown Sugar Delight Scrub',
    shortDescription: 'Brown sugar granules gently exfoliate while vanilla oil moisturizes, leaving skin soft and aromatic.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or dry skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Aromatic exfoliation',
    postTreatmentNotes: 'Soft, smooth, fragrant skin',
    recommendedAddOns: 'Vanilla body cream',
    whatToExpect: 'Brown sugar granules gently exfoliate while vanilla oil moisturizes, leaving skin soft and aromatic.',
    imageThumbnail: '',
  },
  {
    name: 'Himalayan Rose Salt Glow Scrub',
    shortDescription: 'Himalayan pink salt and rose essence exfoliate and energize skin while nourishing it with essential oils.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dull or rough skin',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Salt-based aromatherapy scrub',
    postTreatmentNotes: 'Smooth, glowing skin',
    recommendedAddOns: 'Rose-scented lotion',
    whatToExpect: 'Himalayan pink salt and rose essence exfoliate and energize skin while nourishing it with essential oils.',
    imageThumbnail: '',
  },
  {
    name: 'Aloe Vera Soothing Scrub',
    shortDescription: 'A gentle aloe vera scrub exfoliates while calming and hydrating irritated or sensitive skin.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or sun-exposed skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Gentle moisturizing scrub',
    postTreatmentNotes: 'Calm, soft skin',
    recommendedAddOns: 'Aloe body lotion',
    whatToExpect: 'A gentle aloe vera scrub exfoliates while calming and hydrating irritated or sensitive skin.',
    imageThumbnail: '',
  },
  {
    name: 'Tropical Mango Smooth Scrub',
    shortDescription: 'Mango pulp and natural sugar granules gently exfoliate and hydrate, leaving skin smooth, soft, and radiant.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dull or dehydrated skin',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Fruit-based exfoliation',
    postTreatmentNotes: 'Soft, glowing skin',
    recommendedAddOns: 'Mango body butter',
    whatToExpect: 'Mango pulp and natural sugar granules gently exfoliate and hydrate, leaving skin smooth, soft, and radiant.',
    imageThumbnail: '',
  },
  {
    name: 'Coffee & Vanilla Energizing Scrub',
    shortDescription: 'Coffee grounds exfoliate while vanilla oil hydrates and energizes the skin, promoting circulation and smoothness.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Legs, back, arms',
    idealFor: 'Fatigue, cellulite-prone areas',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Coffee-granule exfoliation',
    postTreatmentNotes: 'Energized, soft skin',
    recommendedAddOns: 'Vanilla body lotion',
    whatToExpect: 'Coffee grounds exfoliate while vanilla oil hydrates and energizes the skin, promoting circulation and smoothness.',
    imageThumbnail: '',
  },
  {
    name: 'Honey & Oatmeal Gentle Scrub',
    shortDescription: 'Oatmeal granules gently exfoliate while honey moisturizes and soothes sensitive skin.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or dry skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Gentle natural exfoliation',
    postTreatmentNotes: 'Smooth, calm skin',
    recommendedAddOns: 'Honey-infused body cream',
    whatToExpect: 'Oatmeal granules gently exfoliate while honey moisturizes and soothes sensitive skin.',
    imageThumbnail: '',
  },
  {
    name: 'Citrus & Ginger Revitalizing Scrub',
    shortDescription: 'Citrus zest and ginger gently exfoliate, stimulate circulation, and awaken the senses.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dull skin, fatigue, stress',
    suggestedFrequency: '2 times monthly',
    techniqueStyle: 'Invigorating scrub therapy',
    postTreatmentNotes: 'Refreshed, radiant skin',
    recommendedAddOns: 'Citrus body oil',
    whatToExpect: 'Citrus zest and ginger gently exfoliate, stimulate circulation, and awaken the senses.',
    imageThumbnail: '',
  },
  {
    name: 'Lavender & Sea Salt Calm Scrub',
    shortDescription: 'Sea salt exfoliates while lavender soothes the skin and mind, perfect for stress relief and relaxation.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or stressed clients',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Aromatherapy exfoliation',
    postTreatmentNotes: 'Smooth, relaxed skin',
    recommendedAddOns: 'Lavender oil massage',
    whatToExpect: 'Sea salt exfoliates while lavender soothes the skin and mind, perfect for stress relief and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Tropical Papaya & Pineapple Scrub',
    shortDescription: 'Enzyme-rich papaya and pineapple gently exfoliate and brighten the skin while nourishing oils hydrate.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dull, uneven skin',
    suggestedFrequency: '2 times monthly',
    techniqueStyle: 'Enzyme fruit scrub',
    postTreatmentNotes: 'Radiant, soft skin',
    recommendedAddOns: 'Tropical body lotion',
    whatToExpect: 'Enzyme-rich papaya and pineapple gently exfoliate and brighten the skin while nourishing oils hydrate.',
    imageThumbnail: '',
  },
  {
    name: 'Mint & Lemon Cooling Scrub',
    shortDescription: 'Cooling mint and zesty lemon refresh, exfoliate, and invigorate the skin while enhancing circulation.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Legs, arms, back',
    idealFor: 'Tired or stressed skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Herbal citrus scrub',
    postTreatmentNotes: 'Energized, refreshed skin',
    recommendedAddOns: 'Mint-scented lotion',
    whatToExpect: 'Cooling mint and zesty lemon refresh, exfoliate, and invigorate the skin while enhancing circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Shea Butter & Brown Sugar Scrub',
    shortDescription: 'Brown sugar gently exfoliates while shea butter deeply moisturizes, leaving skin smooth and nourished.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry or sensitive skin',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Moisturizing exfoliation',
    postTreatmentNotes: 'Soft, hydrated skin',
    recommendedAddOns: 'Shea body cream',
    whatToExpect: 'Brown sugar gently exfoliates while shea butter deeply moisturizes, leaving skin smooth and nourished.',
    imageThumbnail: '',
  },
  {
    name: 'Almond & Honey Nourishing Scrub',
    shortDescription: 'Almond granules polish and exfoliate while honey moisturizes and softens the skin.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dry, dull, or dehydrated skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Nutritive exfoliation',
    postTreatmentNotes: 'Smooth, nourished skin',
    recommendedAddOns: 'Almond oil application',
    whatToExpect: 'Almond granules polish and exfoliate while honey moisturizes and softens the skin.',
    imageThumbnail: '',
  },
  {
    name: 'Coffee & Mint Invigorating Scrub',
    shortDescription: 'Coffee grounds exfoliate while mint refreshes and stimulates circulation for energized skin.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Legs, arms, back',
    idealFor: 'Fatigue or dull skin',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Invigorating scrub therapy',
    postTreatmentNotes: 'Energized, smooth skin',
    recommendedAddOns: 'Mint body lotion',
    whatToExpect: 'Coffee grounds exfoliate while mint refreshes and stimulates circulation for energized skin.',
    imageThumbnail: '',
  },
  {
    name: 'Tropical Coconut Lime Scrub',
    shortDescription: 'Coconut and lime exfoliate and hydrate, leaving skin soft, radiant, and fragrant.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry skin, hydration',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Tropical fruit scrub',
    postTreatmentNotes: 'Soft, nourished skin',
    recommendedAddOns: 'Coconut body butter',
    whatToExpect: 'Coconut and lime exfoliate and hydrate, leaving skin soft, radiant, and fragrant.',
    imageThumbnail: '',
  },
  {
    name: 'Rose Quartz Glow Scrub',
    shortDescription: 'Gentle rose quartz crystals polish skin while rose-scented oils hydrate and energize the body.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or delicate skin',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Crystal-infused exfoliation',
    postTreatmentNotes: 'Smooth, radiant skin',
    recommendedAddOns: 'Rose oil',
    whatToExpect: 'Gentle rose quartz crystals polish skin while rose-scented oils hydrate and energize the body.',
    imageThumbnail: '',
  },
  {
    name: 'Papaya & Coconut Enzyme Scrub',
    shortDescription: 'Papaya enzymes exfoliate while coconut oil moisturizes and softens the skin naturally.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive, dry skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Enzyme fruit scrub',
    postTreatmentNotes: 'Soft, glowing skin',
    recommendedAddOns: 'Coconut body butter',
    whatToExpect: 'Papaya enzymes exfoliate while coconut oil moisturizes and softens the skin naturally.',
    imageThumbnail: '',
  },
  {
    name: 'Chocolate & Coffee Body Polish',
    shortDescription: 'Exfoliating coffee and cocoa grounds remove dead skin while nourishing chocolate oils hydrate.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dull skin, tired muscles',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Coffee-chocolate scrub',
    postTreatmentNotes: 'Energized, smooth skin',
    recommendedAddOns: 'Chocolate oil',
    whatToExpect: 'Exfoliating coffee and cocoa grounds remove dead skin while nourishing chocolate oils hydrate.',
    imageThumbnail: '',
  },
  {
    name: 'Citrus & Sugar Glow Scrub',
    shortDescription: 'Sugar granules exfoliate while citrus oils brighten and refresh the skin for a radiant glow.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dull, tired skin',
    suggestedFrequency: '2 times monthly',
    techniqueStyle: 'Sugar-citrus scrub',
    postTreatmentNotes: 'Bright, soft skin',
    recommendedAddOns: 'Citrus body lotion',
    whatToExpect: 'Sugar granules exfoliate while citrus oils brighten and refresh the skin for a radiant glow.',
    imageThumbnail: '',
  },
  {
    name: 'Green Tea & Mint Refresh Scrub',
    shortDescription: 'Green tea leaves and mint gently exfoliate and detoxify the skin while invigorating the senses.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Detox, circulation boost',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Herbal exfoliation',
    postTreatmentNotes: 'Refreshed, energized skin',
    recommendedAddOns: 'Mint oil',
    whatToExpect: 'Green tea leaves and mint gently exfoliate and detoxify the skin while invigorating the senses.',
    imageThumbnail: '',
  },
  {
    name: 'Lavender & Honey Calming Scrub',
    shortDescription: 'Lavender and honey gently exfoliate and soothe skin, ideal for relaxation and stress relief.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive, stressed skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Aromatherapy scrub',
    postTreatmentNotes: 'Calm, soft skin',
    recommendedAddOns: 'Lavender oil',
    whatToExpect: 'Lavender and honey gently exfoliate and soothe skin, ideal for relaxation and stress relief.',
    imageThumbnail: '',
  },
  {
    name: 'Mango & Papaya Tropical Glow Scrub',
    shortDescription: 'A tropical fruit blend of mango and papaya gently exfoliates dead skin while nourishing oils hydrate, leaving skin soft and radiant.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dull or dehydrated skin',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Fruit enzyme exfoliation',
    postTreatmentNotes: 'Smooth, glowing skin',
    recommendedAddOns: 'Tropical body lotion',
    whatToExpect: 'A tropical fruit blend of mango and papaya gently exfoliates dead skin while nourishing oils hydrate, leaving skin soft and radiant.',
    imageThumbnail: '',
  },
  {
    name: 'Cocoa & Vanilla Indulgence Scrub',
    shortDescription: 'Rich cocoa and soothing vanilla granules exfoliate while deeply moisturizing, leaving skin silky and fragrant.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Dry or stressed skin',
    suggestedFrequency: '2 times monthly',
    techniqueStyle: 'Chocolate-based scrub',
    postTreatmentNotes: 'Hydrated, smooth skin',
    recommendedAddOns: 'Cocoa body butter',
    whatToExpect: 'Rich cocoa and soothing vanilla granules exfoliate while deeply moisturizing, leaving skin silky and fragrant.',
    imageThumbnail: '',
  },
  {
    name: 'Sea Salt & Aloe Hydration Scrub',
    shortDescription: 'Mineral-rich sea salt gently polishes skin while aloe vera soothes and hydrates for refreshed, soft skin.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Sensitive or dry skin',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Salt and aloe exfoliation',
    postTreatmentNotes: 'Smooth, hydrated skin',
    recommendedAddOns: 'Aloe body cream',
    whatToExpect: 'Mineral-rich sea salt gently polishes skin while aloe vera soothes and hydrates for refreshed, soft skin.',
    imageThumbnail: '',
  },
  {
    name: 'Coffee & Orange Energizing Scrub',
    shortDescription: 'Coffee grounds stimulate circulation while orange essential oils brighten and refresh the skin for energy and radiance.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Legs, arms, back',
    idealFor: 'Fatigue, dull skin',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Coffee-citrus scrub',
    postTreatmentNotes: 'Energized, smooth skin',
    recommendedAddOns: 'Orange-scented lotion',
    whatToExpect: 'Coffee grounds stimulate circulation while orange essential oils brighten and refresh the skin for energy and radiance.',
    imageThumbnail: '',
  },
  {
    name: 'Lavender & Chamomile Relaxing Scrub',
    shortDescription: 'Calming lavender and chamomile exfoliate gently while providing aromatherapy benefits for ultimate relaxation.',
    recommendedDuration: '45 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stressed or sensitive skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Aromatherapy scrub',
    postTreatmentNotes: 'Relaxed, soft skin',
    recommendedAddOns: 'Lavender oil',
    whatToExpect: 'Calming lavender and chamomile exfoliate gently while providing aromatherapy benefits for ultimate relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Peppermint & Sugar Cooling Scrub',
    shortDescription: 'Sugar granules exfoliate while peppermint cools and invigorates, improving circulation and refreshing tired skin.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Legs, back, arms',
    idealFor: 'Fatigue or stressed skin',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Cooling sugar scrub',
    postTreatmentNotes: 'Energized, smooth skin',
    recommendedAddOns: 'Peppermint lotion',
    whatToExpect: 'Sugar granules exfoliate while peppermint cools and invigorates, improving circulation and refreshing tired skin.',
    imageThumbnail: '',
  },
  {
    name: 'Rose & Almond Luxurious Scrub',
    shortDescription: 'Almond granules gently polish skin while rose-infused oils moisturize and leave a soft fragrance.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry or sensitive skin',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Nutritive floral scrub',
    postTreatmentNotes: 'Smooth, fragrant skin',
    recommendedAddOns: 'Rose-scented body oil',
    whatToExpect: 'Almond granules gently polish skin while rose-infused oils moisturize and leave a soft fragrance.',
    imageThumbnail: '',
  },
  {
    name: 'Tropical Pineapple & Coconut Scrub',
    shortDescription: 'Enzyme-rich pineapple and hydrating coconut oil exfoliate and nourish skin for a bright, tropical glow.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry or dull skin',
    suggestedFrequency: '2–3 times monthly',
    techniqueStyle: 'Fruit enzyme exfoliation',
    postTreatmentNotes: 'Soft, radiant skin',
    recommendedAddOns: 'Coconut body butter',
    whatToExpect: 'Enzyme-rich pineapple and hydrating coconut oil exfoliate and nourish skin for a bright, tropical glow.',
    imageThumbnail: '',
  },
  {
    name: 'Himalayan Salt & Citrus Invigorating Scrub',
    shortDescription: 'Pink Himalayan salt exfoliates and detoxifies while citrus oils brighten and refresh the skin.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Tired, dull skin',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Salt and citrus scrub',
    postTreatmentNotes: 'Energized, smooth skin',
    recommendedAddOns: 'Citrus body lotion',
    whatToExpect: 'Pink Himalayan salt exfoliates and detoxifies while citrus oils brighten and refresh the skin.',
    imageThumbnail: '',
  },
  {
    name: 'Gold & Honey Luxury Body Polish',
    shortDescription: 'Gold-infused honey exfoliates and nourishes the skin, leaving it silky, radiant, and deeply hydrated.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Premium spa clients, dry or dull skin',
    suggestedFrequency: 'Monthly or special occasions',
    techniqueStyle: 'Luxury exfoliation polish',
    postTreatmentNotes: 'Soft, glowing, luxurious skin',
    recommendedAddOns: 'Gold-infused body lotion, aromatherapy',
    whatToExpect: 'Gold-infused honey exfoliates and nourishes the skin, leaving it silky, radiant, and deeply hydrated.',
    imageThumbnail: '',
  },
];
