/**
 * Sports Massage directory entries for dashboard (massage home service & massage city places).
 * Each entry appears in the Massage Types Directory; full content is shown in the (i) description
 * popup on the live site when the member has added the type to their menu price slider.
 */

export interface SportsMassageDirectoryEntry {
  name: string;
  shortDescription: string;
  recommendedDuration: string;
  pressureLevel: string;
  focusAreas: string;
  idealFor: string;
  suggestedFrequency: string;
  techniqueStyle: string;
  postTreatmentNotes: string;
  recommendedAddOns: string;
  whatToExpect: string;
  imageThumbnail: string;
}

export function getSportsMassagePopupContent(serviceName: string): string | null {
  const entry = SPORTS_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (serviceName || '').toLowerCase().trim()
  );
  if (!entry) return null;
  const parts: string[] = [
    'What to Expect:',
    entry.whatToExpect,
    '',
    `Recommended Duration: ${entry.recommendedDuration}`,
    `Pressure Level: ${entry.pressureLevel}`,
    `Focus Areas: ${entry.focusAreas}`,
    `Ideal For: ${entry.idealFor}`,
    `Suggested Frequency: ${entry.suggestedFrequency}`,
    `Technique Style: ${entry.techniqueStyle}`,
    `Post-Treatment Notes: ${entry.postTreatmentNotes}`,
    `Recommended Add-Ons: ${entry.recommendedAddOns}`,
  ];
  return parts.join('\n');
}

export function getSportsMassageEntry(name: string): SportsMassageDirectoryEntry | undefined {
  return SPORTS_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (name || '').toLowerCase().trim()
  );
}

export const SPORTS_MASSAGE_DIRECTORY_NAMES = [
  'Football Recovery Massage',
  'Basketball Performance Massage',
  'Rugby Muscle Recovery Massage',
  'Running Endurance Massage',
  'Cycling Recovery Massage',
  'Swimming Shoulder Therapy Massage',
  'Boxing Power Massage',
  'MMA Combat Recovery Massage',
  'Tennis Mobility Massage',
  'Golf Swing Alignment Massage',
  'CrossFit Recovery Massage',
  'Bodybuilding Muscle Maintenance Massage',
  'Weightlifting Recovery Massage',
  'Triathlon Endurance Massage',
  'Martial Arts Flexibility Massage',
  'Yoga Recovery Massage',
  'Climbing Grip Recovery Massage',
  'Surfing Balance Massage',
  'Skating Lower Body Massage',
  'Gymnastics Flexibility Massage',
  'Cricket Recovery Massage',
  'Baseball Throwing Arm Massage',
  'Hockey Impact Recovery Massage',
  'Volleyball Jump Recovery Massage',
  'Badminton Agility Massage',
  'Table Tennis Reflex Massage',
  'Rowing Back Strength Massage',
  'Wrestling Recovery Massage',
  'Fencing Precision Massage',
  'Archery Stability Massage',
  'Horse Riding Core Balance Massage',
  'Skiing Recovery Massage',
  'Snowboarding Mobility Massage',
  'Kayaking Upper Body Massage',
  'Track Sprint Recovery Massage',
  'Marathon Recovery Massage',
  'Powerlifting Muscle Reset Massage',
  'Parkour Agility Massage',
  'Dance Performance Massage',
  'Cheerleading Flexibility Massage',
  'American Football Impact Massage',
  'Handball Agility Massage',
  'Lacrosse Recovery Massage',
  'Netball Muscle Balance Massage',
  'Paddle Tennis Recovery Massage',
  'Motor Racing Neck Support Massage',
  'Diving Flexibility Massage',
  'Sailing Core Stability Massage',
  'Skateboarding Impact Massage',
  'Esports Posture Correction Massage',
] as const;

export const SPORTS_MASSAGE_DIRECTORY_ENTRIES: SportsMassageDirectoryEntry[] = [
  {
    name: 'Football Recovery Massage',
    shortDescription: 'Lower-body dominant session focusing on quadriceps, hamstrings, calves, and hip flexors. Combines compression, stretching, and deep tissue work to restore power and flexibility after high-intensity play.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★',
    focusAreas: 'Legs, hips, lower back',
    idealFor: 'Football players',
    suggestedFrequency: 'Post-match or weekly',
    techniqueStyle: 'Deep tissue with assisted stretching',
    postTreatmentNotes: 'Mild soreness possible; improved mobility expected within 24 hours.',
    recommendedAddOns: 'Stretch therapy, cold therapy',
    whatToExpect:
      'A lower-body dominant session focusing on quadriceps, hamstrings, calves, and hip flexors. Combines compression, stretching, and deep tissue work to restore power and flexibility after high-intensity play. Helps reduce stiffness and prevent strain injuries.',
    imageThumbnail: '',
  },
  {
    name: 'Basketball Performance Massage',
    shortDescription: 'Targets explosive muscle groups used in jumping and sprinting. Focus on calves, knees, and shoulders to improve agility and reduce impact stress.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Legs, knees, shoulders',
    idealFor: 'Basketball players',
    suggestedFrequency: 'Weekly during season',
    techniqueStyle: 'Compression and mobility-based therapy',
    postTreatmentNotes: 'Increased range of motion expected.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'Targets explosive muscle groups used in jumping and sprinting. Focus on calves, knees, and shoulders to improve agility and reduce impact stress.',
    imageThumbnail: '',
  },
  {
    name: 'Rugby Muscle Recovery Massage',
    shortDescription: 'Intensive full-body session addressing impact-related tension. Deep muscle work reduces bruising stiffness and enhances recovery.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Very Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Rugby athletes',
    suggestedFrequency: 'Post-match',
    techniqueStyle: 'Heavy compression and deep tissue',
    postTreatmentNotes: 'Hydration recommended post-session.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Intensive full-body session addressing impact-related tension. Deep muscle work reduces bruising stiffness and enhances recovery.',
    imageThumbnail: '',
  },
  {
    name: 'Running Endurance Massage',
    shortDescription: 'Focuses on repetitive strain areas including calves, IT band, and hamstrings. Improves stride efficiency and reduces tightness.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Lower body',
    idealFor: 'Runners & marathoners',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Myofascial and stretching therapy',
    postTreatmentNotes: 'Improved flexibility expected.',
    recommendedAddOns: 'Foot therapy',
    whatToExpect:
      'Focuses on repetitive strain areas including calves, IT band, and hamstrings. Improves stride efficiency and reduces tightness.',
    imageThumbnail: '',
  },
  {
    name: 'Cycling Recovery Massage',
    shortDescription: 'Addresses hip flexors, glutes, and lower back strain from prolonged seated posture.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★',
    focusAreas: 'Hips, glutes, lower back',
    idealFor: 'Cyclists',
    suggestedFrequency: 'After long rides',
    techniqueStyle: 'Deep compression and hip mobility work',
    postTreatmentNotes: 'Reduced hip stiffness.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Addresses hip flexors, glutes, and lower back strain from prolonged seated posture.',
    imageThumbnail: '',
  },
  {
    name: 'Swimming Shoulder Therapy Massage',
    shortDescription: 'Upper-body focused treatment relieving repetitive shoulder rotation strain.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Shoulders, lats, upper back',
    idealFor: 'Swimmers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Trigger point and mobility therapy',
    postTreatmentNotes: 'Improved shoulder rotation expected.',
    recommendedAddOns: 'Cupping',
    whatToExpect:
      'Upper-body focused treatment relieving repetitive shoulder rotation strain.',
    imageThumbnail: '',
  },
  {
    name: 'Boxing Power Massage',
    shortDescription: 'Targets shoulders, forearms, and core to enhance punching power and reduce tension buildup.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Upper body, core',
    idealFor: 'Boxers',
    suggestedFrequency: 'Pre or post-fight',
    techniqueStyle: 'Deep tissue and compression',
    postTreatmentNotes: 'Increased muscle readiness.',
    recommendedAddOns: 'Cold therapy',
    whatToExpect:
      'Targets shoulders, forearms, and core to enhance punching power and reduce tension buildup.',
    imageThumbnail: '',
  },
  {
    name: 'MMA Combat Recovery Massage',
    shortDescription: 'Full-body muscular reset addressing grappling strain and impact tension.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Very Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'MMA athletes',
    suggestedFrequency: 'Post-training',
    techniqueStyle: 'Advanced deep tissue',
    postTreatmentNotes: 'Muscle fatigue reduction expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Full-body muscular reset addressing grappling strain and impact tension.',
    imageThumbnail: '',
  },
  {
    name: 'Tennis Mobility Massage',
    shortDescription: 'Improves shoulder rotation and forearm flexibility while relieving lower-body pivot strain.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Shoulders, forearms, legs',
    idealFor: 'Tennis players',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Mobility-based therapy',
    postTreatmentNotes: 'Enhanced swing flexibility.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'Improves shoulder rotation and forearm flexibility while relieving lower-body pivot strain.',
    imageThumbnail: '',
  },
  {
    name: 'Golf Swing Alignment Massage',
    shortDescription: 'Enhances rotational flexibility and spinal mobility to improve swing consistency.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, hips, shoulders',
    idealFor: 'Golfers',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Structured alignment therapy',
    postTreatmentNotes: 'Improved posture expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Enhances rotational flexibility and spinal mobility to improve swing consistency.',
    imageThumbnail: '',
  },
  {
    name: 'CrossFit Recovery Massage',
    shortDescription: 'High-intensity muscle recovery session designed to relieve full-body fatigue from functional training. Focuses on reducing stiffness and restoring mobility after compound lifts and explosive movements.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'CrossFit athletes',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep tissue with mobility integration',
    postTreatmentNotes: 'Temporary soreness possible; improved range of motion expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A high-intensity muscle recovery session designed to relieve full-body fatigue from functional training. Focuses on reducing stiffness and restoring mobility after compound lifts and explosive movements.',
    imageThumbnail: '',
  },
  {
    name: 'Bodybuilding Muscle Maintenance Massage',
    shortDescription: 'Targets hypertrophied muscles to reduce tightness and improve muscle symmetry. Supports recovery between heavy lifting sessions.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Targeted muscle groups',
    idealFor: 'Bodybuilders',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep compression and myofascial therapy',
    postTreatmentNotes: 'Enhanced muscle definition and flexibility.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Targets hypertrophied muscles to reduce tightness and improve muscle symmetry. Supports recovery between heavy lifting sessions.',
    imageThumbnail: '',
  },
  {
    name: 'Weightlifting Recovery Massage',
    shortDescription: 'Designed to relieve central nervous system fatigue and muscle tension from heavy lifting.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Firm ★★★',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'Olympic lifters',
    suggestedFrequency: 'Post-training',
    techniqueStyle: 'Compression and trigger point therapy',
    postTreatmentNotes: 'Improved recovery time.',
    recommendedAddOns: 'Cold therapy',
    whatToExpect:
      'Designed to relieve central nervous system fatigue and muscle tension from heavy lifting.',
    imageThumbnail: '',
  },
  {
    name: 'Triathlon Endurance Massage',
    shortDescription: 'A balanced session addressing cumulative fatigue from swimming, cycling, and running.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Full body',
    idealFor: 'Triathletes',
    suggestedFrequency: 'Weekly during training',
    techniqueStyle: 'Myofascial and stretching therapy',
    postTreatmentNotes: 'Increased endurance support.',
    recommendedAddOns: 'Foot therapy',
    whatToExpect:
      'A balanced session addressing cumulative fatigue from swimming, cycling, and running.',
    imageThumbnail: '',
  },
  {
    name: 'Martial Arts Flexibility Massage',
    shortDescription: 'Improves dynamic flexibility and reduces impact strain from kicks and grappling.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Hips, legs, shoulders',
    idealFor: 'Martial artists',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Assisted stretching and compression',
    postTreatmentNotes: 'Improved kick height and mobility.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Improves dynamic flexibility and reduces impact strain from kicks and grappling.',
    imageThumbnail: '',
  },
  {
    name: 'Yoga Recovery Massage',
    shortDescription: 'Enhances muscle relaxation and releases deep connective tissue tension from advanced poses.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Yoga practitioners',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Myofascial and relaxation blend',
    postTreatmentNotes: 'Deeper flexibility and relaxation.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Enhances muscle relaxation and releases deep connective tissue tension from advanced poses.',
    imageThumbnail: '',
  },
  {
    name: 'Climbing Grip Recovery Massage',
    shortDescription: 'Focused on forearms, shoulders, and upper back to relieve overuse strain.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Firm ★★★',
    focusAreas: 'Forearms, shoulders',
    idealFor: 'Rock climbers',
    suggestedFrequency: 'After intense sessions',
    techniqueStyle: 'Trigger point therapy',
    postTreatmentNotes: 'Improved grip endurance.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'Focused on forearms, shoulders, and upper back to relieve overuse strain.',
    imageThumbnail: '',
  },
  {
    name: 'Surfing Balance Massage',
    shortDescription: 'Targets core, hips, and lower back to improve board stability and flexibility.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Core, hips',
    idealFor: 'Surfers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Mobility-focused therapy',
    postTreatmentNotes: 'Enhanced balance and posture.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Targets core, hips, and lower back to improve board stability and flexibility.',
    imageThumbnail: '',
  },
  {
    name: 'Skating Lower Body Massage',
    shortDescription: 'Reduces strain in quads and glutes from repetitive skating motion.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Legs, hips',
    idealFor: 'Ice and roller skaters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Compression and stretching',
    postTreatmentNotes: 'Reduced stiffness expected.',
    recommendedAddOns: 'Cold therapy',
    whatToExpect:
      'Reduces strain in quads and glutes from repetitive skating motion.',
    imageThumbnail: '',
  },
  {
    name: 'Gymnastics Flexibility Massage',
    shortDescription: 'Improves elasticity and joint mobility for high-level flexibility performance.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Gymnasts',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Assisted stretching therapy',
    postTreatmentNotes: 'Increased mobility.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Improves elasticity and joint mobility for high-level flexibility performance.',
    imageThumbnail: '',
  },
  {
    name: 'Cricket Recovery Massage',
    shortDescription: 'Targets shoulder rotation, hamstrings, and lower back strain from bowling and batting. Helps reduce repetitive overuse tension and supports mobility.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Shoulders, lower back, hamstrings',
    idealFor: 'Cricket players',
    suggestedFrequency: 'Weekly during season',
    techniqueStyle: 'Deep tissue with mobility work',
    postTreatmentNotes: 'Improved shoulder rotation expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Targets shoulder rotation, hamstrings, and lower back strain from bowling and batting. Helps reduce repetitive overuse tension and supports mobility.',
    imageThumbnail: '',
  },
  {
    name: 'Baseball Throwing Arm Massage',
    shortDescription: 'Focused treatment for pitching strain and repetitive throwing mechanics. Releases forearm and rotator cuff tightness.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Shoulder, forearm',
    idealFor: 'Baseball players',
    suggestedFrequency: 'Post-game',
    techniqueStyle: 'Trigger point and compression therapy',
    postTreatmentNotes: 'Reduced arm fatigue.',
    recommendedAddOns: 'Cold therapy',
    whatToExpect:
      'Focused treatment for pitching strain and repetitive throwing mechanics. Releases forearm and rotator cuff tightness.',
    imageThumbnail: '',
  },
  {
    name: 'Hockey Impact Recovery Massage',
    shortDescription: 'Designed to relieve lower-body fatigue and upper-body impact tension from fast-paced gameplay.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Legs, shoulders',
    idealFor: 'Hockey players',
    suggestedFrequency: 'Post-match',
    techniqueStyle: 'Deep compression therapy',
    postTreatmentNotes: 'Improved recovery speed.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Designed to relieve lower-body fatigue and upper-body impact tension from fast-paced gameplay.',
    imageThumbnail: '',
  },
  {
    name: 'Volleyball Jump Recovery Massage',
    shortDescription: 'Targets knees, calves, and shoulders to reduce strain from repetitive jumping and spiking.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Lower body, shoulders',
    idealFor: 'Volleyball players',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Myofascial release and stretching',
    postTreatmentNotes: 'Increased knee mobility.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Targets knees, calves, and shoulders to reduce strain from repetitive jumping and spiking.',
    imageThumbnail: '',
  },
  {
    name: 'Badminton Agility Massage',
    shortDescription: 'Enhances quick directional movement by reducing calf and shoulder tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Calves, shoulders',
    idealFor: 'Badminton players',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Compression and mobility therapy',
    postTreatmentNotes: 'Improved agility expected.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'Enhances quick directional movement by reducing calf and shoulder tension.',
    imageThumbnail: '',
  },
  {
    name: 'Table Tennis Reflex Massage',
    shortDescription: 'Relieves wrist, forearm, and shoulder fatigue from rapid repetitive motion.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Forearms, shoulders',
    idealFor: 'Table tennis players',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Targeted trigger point therapy',
    postTreatmentNotes: 'Reduced wrist stiffness.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Relieves wrist, forearm, and shoulder fatigue from rapid repetitive motion.',
    imageThumbnail: '',
  },
  {
    name: 'Rowing Back Strength Massage',
    shortDescription: 'Focuses on lats, lower back, and hamstrings to reduce repetitive pulling strain.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★',
    focusAreas: 'Back, hamstrings',
    idealFor: 'Rowers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep tissue with stretching',
    postTreatmentNotes: 'Improved back mobility.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Focuses on lats, lower back, and hamstrings to reduce repetitive pulling strain.',
    imageThumbnail: '',
  },
  {
    name: 'Wrestling Recovery Massage',
    shortDescription: 'Full-body muscular reset targeting neck, shoulders, and hips.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Very Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Wrestlers',
    suggestedFrequency: 'Post-training',
    techniqueStyle: 'Heavy compression therapy',
    postTreatmentNotes: 'Muscle fatigue reduction expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Full-body muscular reset targeting neck, shoulders, and hips.',
    imageThumbnail: '',
  },
  {
    name: 'Fencing Precision Massage',
    shortDescription: 'Enhances lower-body balance and arm precision by reducing tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Legs, forearm',
    idealFor: 'Fencers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Mobility-based therapy',
    postTreatmentNotes: 'Improved reaction speed.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'Enhances lower-body balance and arm precision by reducing tension.',
    imageThumbnail: '',
  },
  {
    name: 'Archery Stability Massage',
    shortDescription: 'Releases shoulder and upper back tension to improve posture and shot stability.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Shoulders, upper back',
    idealFor: 'Archers',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Structured muscle balancing',
    postTreatmentNotes: 'Enhanced shoulder endurance.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Releases shoulder and upper back tension to improve posture and shot stability.',
    imageThumbnail: '',
  },
  {
    name: 'Horse Riding Core Balance Massage',
    shortDescription: 'Improves hip flexibility and lower back stability for riding endurance.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Hips, lower back',
    idealFor: 'Equestrian athletes',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Core-focused therapy',
    postTreatmentNotes: 'Reduced hip tightness.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Improves hip flexibility and lower back stability for riding endurance.',
    imageThumbnail: '',
  },
  {
    name: 'Skiing Recovery Massage',
    shortDescription: 'Targets quads and glutes to relieve downhill strain.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★',
    focusAreas: 'Legs',
    idealFor: 'Skiers',
    suggestedFrequency: 'After activity',
    techniqueStyle: 'Deep compression',
    postTreatmentNotes: 'Reduced muscle fatigue.',
    recommendedAddOns: 'Cold therapy',
    whatToExpect:
      'Targets quads and glutes to relieve downhill strain.',
    imageThumbnail: '',
  },
  {
    name: 'Snowboarding Mobility Massage',
    shortDescription: 'Focuses on core and lower body to restore balance and flexibility.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Core, legs',
    idealFor: 'Snowboarders',
    suggestedFrequency: 'Weekly during season',
    techniqueStyle: 'Mobility therapy',
    postTreatmentNotes: 'Improved balance.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focuses on core and lower body to restore balance and flexibility.',
    imageThumbnail: '',
  },
  {
    name: 'Kayaking Upper Body Massage',
    shortDescription: 'Releases repetitive paddle strain in shoulders and lats.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Upper body',
    idealFor: 'Kayakers',
    suggestedFrequency: 'After long sessions',
    techniqueStyle: 'Trigger point therapy',
    postTreatmentNotes: 'Reduced shoulder tightness.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Releases repetitive paddle strain in shoulders and lats.',
    imageThumbnail: '',
  },
  {
    name: 'Track Sprint Recovery Massage',
    shortDescription: 'Improves hamstring elasticity and calf flexibility for explosive sprinting.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Firm ★★★',
    focusAreas: 'Hamstrings, calves',
    idealFor: 'Sprinters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep tissue with stretch integration',
    postTreatmentNotes: 'Increased stride efficiency.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Improves hamstring elasticity and calf flexibility for explosive sprinting.',
    imageThumbnail: '',
  },
  {
    name: 'Marathon Recovery Massage',
    shortDescription: 'Gentle but thorough muscle reset after endurance events.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Lower body',
    idealFor: 'Marathon runners',
    suggestedFrequency: 'Post-race',
    techniqueStyle: 'Circulation-focused recovery therapy',
    postTreatmentNotes: 'Reduced muscle soreness expected.',
    recommendedAddOns: 'Foot therapy',
    whatToExpect:
      'Gentle but thorough muscle reset after endurance events.',
    imageThumbnail: '',
  },
  {
    name: 'Powerlifting Muscle Reset Massage',
    shortDescription: 'Targets heavy load stress areas to improve lifting longevity.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Very Firm ★★★★',
    focusAreas: 'Back, hips',
    idealFor: 'Powerlifters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep compression and myofascial work',
    postTreatmentNotes: 'Improved lifting mobility.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Targets heavy load stress areas to improve lifting longevity.',
    imageThumbnail: '',
  },
  {
    name: 'Parkour Agility Massage',
    shortDescription: 'Supports joint flexibility and reduces impact strain from jumps.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Legs, shoulders',
    idealFor: 'Parkour athletes',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Mobility therapy',
    postTreatmentNotes: 'Enhanced movement fluidity.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Supports joint flexibility and reduces impact strain from jumps.',
    imageThumbnail: '',
  },
  {
    name: 'Dance Performance Massage',
    shortDescription: 'Improves flexibility and muscle recovery for repetitive choreography.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dancers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Stretch-integrated therapy',
    postTreatmentNotes: 'Increased flexibility expected.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Improves flexibility and muscle recovery for repetitive choreography.',
    imageThumbnail: '',
  },
  {
    name: 'Cheerleading Flexibility Massage',
    shortDescription: 'Enhances joint range and reduces impact strain.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Legs, shoulders',
    idealFor: 'Cheerleaders',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Assisted stretching therapy',
    postTreatmentNotes: 'Improved stunt mobility.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Enhances joint range and reduces impact strain.',
    imageThumbnail: '',
  },
  {
    name: 'American Football Impact Massage',
    shortDescription: 'Reduces heavy contact muscle tension and supports fast recovery.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Very Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'American football players',
    suggestedFrequency: 'Post-game',
    techniqueStyle: 'Deep compression therapy',
    postTreatmentNotes: 'Muscle recovery acceleration expected.',
    recommendedAddOns: 'Cold therapy',
    whatToExpect:
      'Reduces heavy contact muscle tension and supports fast recovery.',
    imageThumbnail: '',
  },
  {
    name: 'Handball Agility Massage',
    shortDescription: 'Improves shoulder endurance and lower-body agility.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Shoulders, legs',
    idealFor: 'Handball players',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Mobility-focused therapy',
    postTreatmentNotes: 'Increased agility.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Improves shoulder endurance and lower-body agility.',
    imageThumbnail: '',
  },
  {
    name: 'Lacrosse Recovery Massage',
    shortDescription: 'Relieves repetitive upper-body strain and sprint fatigue.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Firm ★★★',
    focusAreas: 'Upper body, legs',
    idealFor: 'Lacrosse players',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep tissue therapy',
    postTreatmentNotes: 'Reduced stiffness.',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Relieves repetitive upper-body strain and sprint fatigue.',
    imageThumbnail: '',
  },
  {
    name: 'Netball Muscle Balance Massage',
    shortDescription: 'Enhances knee and ankle stability through muscle release.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Lower body',
    idealFor: 'Netball players',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured balancing therapy',
    postTreatmentNotes: 'Improved stability expected.',
    recommendedAddOns: 'Joint mobilization',
    whatToExpect:
      'Enhances knee and ankle stability through muscle release.',
    imageThumbnail: '',
  },
  {
    name: 'Paddle Tennis Recovery Massage',
    shortDescription: 'Targets shoulder and wrist tension from repetitive strokes.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Shoulder, wrist',
    idealFor: 'Paddle tennis players',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Trigger point therapy',
    postTreatmentNotes: 'Reduced joint stiffness.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Targets shoulder and wrist tension from repetitive strokes.',
    imageThumbnail: '',
  },
  {
    name: 'Motor Racing Neck Support Massage',
    shortDescription: 'Reduces neck and upper back strain from prolonged helmet wear and vibration.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Neck, upper back',
    idealFor: 'Racing drivers',
    suggestedFrequency: 'After race',
    techniqueStyle: 'Targeted tension release therapy',
    postTreatmentNotes: 'Improved neck mobility.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Reduces neck and upper back strain from prolonged helmet wear and vibration.',
    imageThumbnail: '',
  },
  {
    name: 'Diving Flexibility Massage',
    shortDescription: 'Improves spinal mobility and leg flexibility for performance dives.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, legs',
    idealFor: 'Divers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Assisted stretching therapy',
    postTreatmentNotes: 'Increased body control.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Improves spinal mobility and leg flexibility for performance dives.',
    imageThumbnail: '',
  },
  {
    name: 'Sailing Core Stability Massage',
    shortDescription: 'Targets core and lower back to support balance on unstable surfaces.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Core, lower back',
    idealFor: 'Sailors',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Core-focused therapy',
    postTreatmentNotes: 'Reduced lower back fatigue.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Targets core and lower back to support balance on unstable surfaces.',
    imageThumbnail: '',
  },
  {
    name: 'Skateboarding Impact Massage',
    shortDescription: 'Relieves joint and muscle tension from repeated jumps and landings.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium–Firm ★★★',
    focusAreas: 'Legs, lower back',
    idealFor: 'Skateboarders',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Compression and mobility therapy',
    postTreatmentNotes: 'Improved joint comfort.',
    recommendedAddOns: 'Cold therapy',
    whatToExpect:
      'Relieves joint and muscle tension from repeated jumps and landings.',
    imageThumbnail: '',
  },
  {
    name: 'Esports Posture Correction Massage',
    shortDescription: 'Focused session addressing neck, shoulder, and wrist strain from prolonged seated gaming.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Neck, shoulders, wrists',
    idealFor: 'Esports players',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured posture-alignment therapy',
    postTreatmentNotes: 'Reduced tension and improved posture awareness.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused session addressing neck, shoulder, and wrist strain from prolonged seated gaming.',
    imageThumbnail: '',
  },
];
