/**
 * Prenatal / Pregnancy Massage directory entries.
 * Display rule: Massage Places Directory and Therapist Home Service (both).
 */

export interface PrenatalMassageDirectoryEntry {
  name: string;
  shortDescription: string;
  recommendedDuration: string;
  pressureLevel: string;
  focusAreas: string;
  idealFor: string;
  suggestedFrequency: string;
  techniqueStyle: string;
  postTreatmentNotes: string;
  recommendedAddOns: string;
  whatToExpect: string;
  imageThumbnail: string;
}

export function getPrenatalMassagePopupContent(serviceName: string): string | null {
  const entry = PRENATAL_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (serviceName || '').toLowerCase().trim()
  );
  if (!entry) return null;
  const parts: string[] = [
    'What to Expect:',
    entry.whatToExpect,
    '',
    `Recommended Duration: ${entry.recommendedDuration}`,
    `Pressure Level: ${entry.pressureLevel}`,
    `Focus Areas: ${entry.focusAreas}`,
    `Ideal For: ${entry.idealFor}`,
    `Suggested Frequency: ${entry.suggestedFrequency}`,
    `Technique Style: ${entry.techniqueStyle}`,
    `Post-Treatment Notes: ${entry.postTreatmentNotes}`,
    `Recommended Add-Ons: ${entry.recommendedAddOns}`,
  ];
  return parts.join('\n');
}

export function getPrenatalMassageEntry(name: string): PrenatalMassageDirectoryEntry | undefined {
  return PRENATAL_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (name || '').toLowerCase().trim()
  );
}

export const PRENATAL_MASSAGE_DIRECTORY_NAMES = [
  'Gentle Glow Prenatal Massage',
  'Serene Bloom Pregnancy Massage',
  'Tranquil Mother Massage',
  'Radiant Mama Massage',
  'Blossom Prenatal Massage',
  'Harmony Pregnancy Massage',
  'Serenity Mother Massage',
  'Calm Cradle Prenatal Massage',
  'Nurturing Nest Massage',
  "Mother's Embrace Massage",
  'Gentle Waves Prenatal Massage',
  'Radiance Mom-to-Be Massage',
  'Lotus Bloom Prenatal Massage',
  "Mother's Haven Massage",
  'Serene Cradle Massage',
  'Blossom Comfort Massage',
  'Gentle Nest Massage',
  'Calm Horizon Prenatal Massage',
  "Angel's Touch Prenatal Massage",
  'Tranquil Bloom Massage',
  "Mother's Serenity Massage",
  'Blissful Journey Prenatal Massage',
  'Gentle Oasis Massage',
  'Tranquility Wave Massage',
  'Blossom Path Prenatal Massage',
  'Serenity Flow Pregnancy Massage',
  'Calming Cradle Massage',
  "Mother's Whisper Massage",
  'Nurturing Flow Massage',
  'Harmony Cradle Prenatal Massage',
  'Gentle Balance Massage',
  'Serene Glow Prenatal Massage',
  'Tranquil Motherhood Massage',
  "Mother's Bliss Massage",
  'Gentle Serenity Massage',
  'Calm Haven Prenatal Massage',
  "Mother's Tranquility Massage",
  'Gentle Harmony Massage',
  'Calm Bloom Prenatal Massage',
  'Tranquil Embrace Massage',
  'Gentle Radiance Massage',
  "Mother's Glow Massage",
  'Serenity Nest Prenatal Massage',
  'Tranquil Heart Massage',
  'Gentle Harmony Flow Massage',
  'Calm Radiance Prenatal Massage',
  "Mother's Whisper Flow Massage",
  'Tranquil Bloom Flow Massage',
  'Nurturing Glow Prenatal Massage',
  "Mother's Serenity Flow Massage",
] as const;

export const PRENATAL_MASSAGE_DIRECTORY_ENTRIES: PrenatalMassageDirectoryEntry[] = [
  {
    name: 'Gentle Glow Prenatal Massage',
    shortDescription: 'A calming massage to relieve tension in the back, shoulders, and legs. Side-lying positioning ensures safety.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, shoulders, arms',
    idealFor: 'Expectant mothers, any trimester',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Prenatal-safe massage, side-lying, gentle stretches',
    postTreatmentNotes: 'Reduced muscle tension, better sleep',
    recommendedAddOns: 'Safe essential oil aromatherapy, hydration',
    whatToExpect: 'A calming massage to relieve tension in the back, shoulders, and legs. Side-lying positioning ensures safety. Light, nurturing strokes improve circulation, reduce swelling, and promote relaxation. Leaves clients feeling peaceful, supported, and refreshed.',
    imageThumbnail: '',
  },
  {
    name: 'Serene Bloom Pregnancy Massage',
    shortDescription: 'Gentle strokes ease swollen legs and back discomfort while calming the mind. Uses pregnancy-safe positioning.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body with focus on back and legs',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, gentle circulatory massage',
    postTreatmentNotes: 'Improved relaxation and reduced swelling',
    recommendedAddOns: 'Herbal compress, hydration',
    whatToExpect: 'Gentle strokes ease swollen legs and back discomfort while calming the mind. Supports proper posture and relieves stress naturally. Uses pregnancy-safe positioning with bolsters and cushions.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Mother Massage',
    shortDescription: 'A nurturing massage emphasizing relaxation and comfort. Light to medium pressure on shoulders, arms, and legs.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Prenatal-safe, gentle strokes',
    postTreatmentNotes: 'Improved comfort and mood',
    recommendedAddOns: 'Pregnancy pillow support',
    whatToExpect: 'A nurturing massage emphasizing relaxation and comfort. Light to medium pressure is applied to shoulders, arms, and legs. Helps reduce fatigue, back pain, and stress.',
    imageThumbnail: '',
  },
  {
    name: 'Radiant Mama Massage',
    shortDescription: 'A soothing massage with gentle stretching to relieve tension in the back, hips, and legs. Optional safe aromatherapy.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Back, hips, legs',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, gentle stretching',
    postTreatmentNotes: 'Reduced discomfort, calm mind',
    recommendedAddOns: 'Aromatherapy, hydration',
    whatToExpect: 'A soothing massage with gentle stretching to relieve tension in the back, hips, and legs. Aromatherapy is optional with safe essential oils. Enhances overall wellness and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Blossom Prenatal Massage',
    shortDescription: 'Relieves common pregnancy discomforts: lower back pain, leg swelling, shoulder tension. Safe positioning throughout.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Prenatal-safe, side-lying massage',
    postTreatmentNotes: 'Relaxed, refreshed body',
    recommendedAddOns: 'Herbal compress, essential oil application',
    whatToExpect: 'Focuses on relieving common pregnancy discomforts such as lower back pain, leg swelling, and shoulder tension. Safe positioning ensures comfort throughout the session.',
    imageThumbnail: '',
  },
  {
    name: 'Harmony Pregnancy Massage',
    shortDescription: 'Gentle, flowing strokes combined with light stretching promote balance and circulation. Soothes muscles and calms the nervous system.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, arms, shoulders',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced muscle tension, improved mood',
    recommendedAddOns: 'Aromatherapy, pregnancy pillow support',
    whatToExpect: 'Gentle, flowing strokes combined with light stretching promote balance and circulation. Designed to soothe muscles and calm the nervous system.',
    imageThumbnail: '',
  },
  {
    name: 'Serenity Mother Massage',
    shortDescription: 'Eases fatigue and swelling with gentle strokes to the back, legs, and arms. Mother-to-be feels light, relaxed, and supported.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body with focus on lower back and legs',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, gentle massage',
    postTreatmentNotes: 'Improved circulation, reduced tension',
    recommendedAddOns: 'Safe herbal oil, bolsters',
    whatToExpect: 'This session focuses on easing fatigue and swelling with gentle strokes to the back, legs, and arms. Helps the mother-to-be feel light, relaxed, and supported.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Cradle Prenatal Massage',
    shortDescription: 'Gentle release of muscle tension, especially in hips and back. Light stretches improve flexibility and reduce discomfort.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, shoulders',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed body, eased tension',
    recommendedAddOns: 'Pregnancy-safe aromatherapy',
    whatToExpect: 'Focuses on gentle release of muscle tension, especially in hips and back. Incorporates light stretches to improve flexibility and reduce discomfort.',
    imageThumbnail: '',
  },
  {
    name: 'Nurturing Nest Massage',
    shortDescription: 'Eases stress and discomfort. Light massage strokes improve circulation and reduce swelling in the legs and feet.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Legs, back, arms',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Prenatal-safe, gentle massage',
    postTreatmentNotes: 'Reduced fatigue, improved mood',
    recommendedAddOns: 'Pregnancy pillow, hydration',
    whatToExpect: 'Designed to ease stress and discomfort. Light massage strokes improve circulation and reduce swelling in the legs and feet.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Embrace Massage",
    shortDescription: 'Full-body, gentle massage to reduce tension in the back, shoulders, and legs. Pregnancy-safe positioning for safety and comfort.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal massage',
    postTreatmentNotes: 'Relaxed and supported body',
    recommendedAddOns: 'Aromatherapy, bolsters',
    whatToExpect: 'A full-body, gentle massage aimed at reducing tension in the back, shoulders, and legs. Ensures safety and comfort using pregnancy-safe positioning.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Waves Prenatal Massage',
    shortDescription: 'Smooth, flowing strokes gently release tension in the back, hips, and legs. Encourages circulation and deep relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced swelling, relaxed muscles',
    recommendedAddOns: 'Pregnancy pillow, aromatherapy',
    whatToExpect: 'Smooth, flowing strokes gently release tension in the back, hips, and legs. Encourages circulation and deep relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Radiance Mom-to-Be Massage',
    shortDescription: 'Hydrating massage oils combined with gentle strokes nourish the skin and muscles. Focuses on calming the mind and reducing fatigue.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, shoulders, legs, arms',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Prenatal-safe, gentle massage',
    postTreatmentNotes: 'Glowing skin, relaxed muscles',
    recommendedAddOns: 'Essential oils, bolsters',
    whatToExpect: 'Hydrating massage oils combined with gentle strokes nourish the skin and muscles. Focuses on calming the mind and reducing fatigue.',
    imageThumbnail: '',
  },
  {
    name: 'Lotus Bloom Prenatal Massage',
    shortDescription: 'A nurturing massage that eases back tension and leg swelling while promoting relaxation and emotional calm.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, arms',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relieved tension, calm mind',
    recommendedAddOns: 'Pregnancy-safe aromatherapy',
    whatToExpect: 'A nurturing massage that eases back tension and leg swelling while promoting relaxation and emotional calm.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Haven Massage",
    shortDescription: 'Gentle, restorative strokes focus on relieving discomfort in the hips, back, and legs. Provides emotional and physical relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced fatigue, calm mood',
    recommendedAddOns: 'Bolster support, hydration',
    whatToExpect: 'Gentle, restorative strokes focus on relieving discomfort in the hips, back, and legs. Provides emotional and physical relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Serene Cradle Massage',
    shortDescription: 'Focuses on comfort and support using side-lying positioning with bolsters. Gentle strokes release tension and enhance circulation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, shoulders',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Prenatal-safe massage',
    postTreatmentNotes: 'Relaxed muscles, improved circulation',
    recommendedAddOns: 'Pregnancy pillow, safe aromatherapy',
    whatToExpect: 'Focuses on comfort and support using side-lying positioning with bolsters. Gentle strokes release tension and enhance circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Blossom Comfort Massage',
    shortDescription: 'A nurturing massage that relieves back and leg tension while providing a calming experience for the mind.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, arms',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced swelling, relaxed body',
    recommendedAddOns: 'Aromatherapy, bolster support',
    whatToExpect: 'A nurturing massage that relieves back and leg tension while providing a calming experience for the mind.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Nest Massage',
    shortDescription: 'Designed for ultimate comfort and relaxation, focusing on tension in the back, hips, and legs. Promotes better sleep and emotional calm.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, arms',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Prenatal-safe side-lying massage',
    postTreatmentNotes: 'Relaxed muscles, calm mind',
    recommendedAddOns: 'Pregnancy-safe oils, hydration',
    whatToExpect: 'Designed for ultimate comfort and relaxation, focusing on tension in the back, hips, and legs. Promotes better sleep and emotional calm.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Horizon Prenatal Massage',
    shortDescription: 'Gentle strokes ease tension, reduce swelling, and encourage circulation. Focuses on comfort and stress relief for the mother-to-be.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, gentle prenatal massage',
    postTreatmentNotes: 'Relaxed muscles, refreshed mind',
    recommendedAddOns: 'Bolsters, aromatherapy',
    whatToExpect: 'Gentle strokes ease tension, reduce swelling, and encourage circulation. Focuses on comfort and stress relief for the mother-to-be.',
    imageThumbnail: '',
  },
  {
    name: "Angel's Touch Prenatal Massage",
    shortDescription: 'A gentle, flowing massage targeting hips, back, and legs. Supports emotional balance and reduces muscle tension safely.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Prenatal-safe, side-lying massage',
    postTreatmentNotes: 'Reduced fatigue, relaxed mind',
    recommendedAddOns: 'Safe essential oils, bolster support',
    whatToExpect: 'A gentle, flowing massage targeting hips, back, and legs. Supports emotional balance and reduces muscle tension safely.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Bloom Massage',
    shortDescription: 'Gentle nurturing massage that relieves tension in the back and legs. Aromatherapy can be included with pregnancy-safe oils for enhanced relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, arms',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal massage',
    postTreatmentNotes: 'Calmed body and mind',
    recommendedAddOns: 'Aromatherapy, hydration',
    whatToExpect: 'Gentle nurturing massage that relieves tension in the back and legs. Aromatherapy can be included with pregnancy-safe oils for enhanced relaxation.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Serenity Massage",
    shortDescription: 'Gentle, nurturing strokes target the back, hips, and legs, reducing tension and promoting relaxation. Side-lying positioning ensures safety.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, shoulders',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Prenatal-safe, side-lying massage',
    postTreatmentNotes: 'Relaxed body, calm mind',
    recommendedAddOns: 'Bolster support, hydration',
    whatToExpect: 'Gentle, nurturing strokes target the back, hips, and legs, reducing tension and promoting relaxation. Side-lying positioning ensures safety.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Journey Prenatal Massage',
    shortDescription: 'A soothing massage that eases fatigue, swelling, and muscle tension. Focuses on comfort and emotional well-being for mothers-to-be.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body with emphasis on back and legs',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe gentle strokes',
    postTreatmentNotes: 'Relaxed, refreshed, and supported',
    recommendedAddOns: 'Aromatherapy, pregnancy pillow',
    whatToExpect: 'A soothing massage that eases fatigue, swelling, and muscle tension. Focuses on comfort and emotional well-being for mothers-to-be.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Oasis Massage',
    shortDescription: 'Provides calm and comfort, with light strokes and gentle stretching to reduce back and leg tension. Improves circulation and emotional calm.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, hips',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced swelling, relaxed muscles',
    recommendedAddOns: 'Herbal oils, bolster support',
    whatToExpect: 'Provides calm and comfort, with light strokes and gentle stretching to reduce back and leg tension. Improves circulation and emotional calm.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquility Wave Massage',
    shortDescription: 'A flowing massage that targets stress points in the shoulders, back, and legs. Promotes comfort, circulation, and relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Shoulders, back, legs',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Prenatal-safe, gentle strokes',
    postTreatmentNotes: 'Relaxed body, eased tension',
    recommendedAddOns: 'Pregnancy pillow, safe oils',
    whatToExpect: 'A flowing massage that targets stress points in the shoulders, back, and legs. Promotes comfort, circulation, and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Blossom Path Prenatal Massage',
    shortDescription: 'Nurturing strokes alleviate tension and swelling while supporting emotional well-being. Incorporates gentle stretching for hip and back comfort.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, shoulders',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal massage',
    postTreatmentNotes: 'Relaxed muscles, improved mood',
    recommendedAddOns: 'Aromatherapy, bolsters',
    whatToExpect: 'Nurturing strokes alleviate tension and swelling while supporting emotional well-being. Incorporates gentle stretching for hip and back comfort.',
    imageThumbnail: '',
  },
  {
    name: 'Serenity Flow Pregnancy Massage',
    shortDescription: 'Gentle flowing strokes combined with light stretching to relieve muscle tension. Focuses on comfort, circulation, and relaxation for expectant mothers.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, shoulders, hips, legs',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced fatigue, relaxed body',
    recommendedAddOns: 'Safe essential oils, bolsters',
    whatToExpect: 'Gentle flowing strokes combined with light stretching to relieve muscle tension. Focuses on comfort, circulation, and relaxation for expectant mothers.',
    imageThumbnail: '',
  },
  {
    name: 'Calming Cradle Massage',
    shortDescription: 'Provides gentle relief to back, legs, and shoulders. Designed to improve comfort and relaxation with pregnancy-safe positioning.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, shoulders',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced swelling, relaxed mind',
    recommendedAddOns: 'Aromatherapy, bolsters',
    whatToExpect: 'Provides gentle relief to back, legs, and shoulders. Designed to improve comfort and relaxation with pregnancy-safe positioning.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Whisper Massage",
    shortDescription: 'A gentle, calming massage that reduces stress, muscle tension, and fatigue. Encourages emotional balance and relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, arms, shoulders',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe gentle strokes',
    postTreatmentNotes: 'Relaxed, refreshed, supported',
    recommendedAddOns: 'Pregnancy pillow, safe oils',
    whatToExpect: 'A gentle, calming massage that reduces stress, muscle tension, and fatigue. Encourages emotional balance and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Nurturing Flow Massage',
    shortDescription: 'Smooth strokes relieve muscle tension and swelling while supporting comfort and emotional well-being. Safe for all stages of pregnancy.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed muscles, improved circulation',
    recommendedAddOns: 'Aromatherapy, bolsters',
    whatToExpect: 'Smooth strokes relieve muscle tension and swelling while supporting comfort and emotional well-being. Safe for all stages of pregnancy.',
    imageThumbnail: '',
  },
  {
    name: 'Harmony Cradle Prenatal Massage',
    shortDescription: 'Focuses on relieving back pain, leg swelling, and shoulder tension. Promotes comfort and relaxation with gentle, nurturing strokes.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, shoulders, arms',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed body, reduced fatigue',
    recommendedAddOns: 'Pregnancy pillow, aromatherapy',
    whatToExpect: 'Focuses on relieving back pain, leg swelling, and shoulder tension. Promotes comfort and relaxation with gentle, nurturing strokes.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Balance Massage',
    shortDescription: 'Restorative massage focusing on hips, back, and legs. Encourages balance, circulation, and deep relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body with emphasis on back and legs',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Prenatal-safe side-lying massage',
    postTreatmentNotes: 'Relieved tension, calm mind',
    recommendedAddOns: 'Bolster support, aromatherapy',
    whatToExpect: 'Restorative massage focusing on hips, back, and legs. Encourages balance, circulation, and deep relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Serene Glow Prenatal Massage',
    shortDescription: 'Gentle massage with light stretching and soothing oils. Focuses on comfort, circulation, and emotional well-being.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, shoulders',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed muscles, refreshed mind',
    recommendedAddOns: 'Aromatherapy, bolsters',
    whatToExpect: 'Gentle massage with light stretching and soothing oils. Focuses on comfort, circulation, and emotional well-being.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Motherhood Massage',
    shortDescription: 'Relieves tension in the back, hips, and legs while promoting relaxation and emotional calm. Uses pregnancy-safe positioning for safety.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, arms',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal massage',
    postTreatmentNotes: 'Relaxed muscles, reduced fatigue',
    recommendedAddOns: 'Pregnancy pillow, safe oils',
    whatToExpect: 'Relieves tension in the back, hips, and legs while promoting relaxation and emotional calm. Uses pregnancy-safe positioning for safety.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Bliss Massage",
    shortDescription: 'Light, flowing strokes focus on comfort and stress relief. Improves circulation, reduces swelling, and promotes emotional calm.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, arms, shoulders',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed body, calm mind',
    recommendedAddOns: 'Aromatherapy, bolster support',
    whatToExpect: 'Light, flowing strokes focus on comfort and stress relief. Improves circulation, reduces swelling, and promotes emotional calm.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Serenity Massage',
    shortDescription: 'Restorative massage that eases back and leg discomfort. Supports emotional balance with gentle prenatal-safe techniques.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, gentle strokes',
    postTreatmentNotes: 'Relaxed muscles, improved comfort',
    recommendedAddOns: 'Pregnancy pillow, safe oils',
    whatToExpect: 'Restorative massage that eases back and leg discomfort. Supports emotional balance with gentle prenatal-safe techniques.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Haven Prenatal Massage',
    shortDescription: 'Focuses on relieving tension in the back, hips, and legs. Promotes comfort, circulation, and emotional well-being.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed body, calm mind',
    recommendedAddOns: 'Bolster support, aromatherapy',
    whatToExpect: 'Focuses on relieving tension in the back, hips, and legs. Promotes comfort, circulation, and emotional well-being.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Tranquility Massage",
    shortDescription: 'Gentle massage focusing on hips, back, and legs. Light strokes reduce swelling, relieve tension, and promote relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, shoulders',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced fatigue, relaxed muscles',
    recommendedAddOns: 'Pregnancy pillow, safe essential oils',
    whatToExpect: 'Gentle massage focusing on hips, back, and legs. Light strokes reduce swelling, relieve tension, and promote relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Harmony Massage',
    shortDescription: 'Soft, flowing strokes relieve tension in the back and legs while supporting emotional well-being. Improves circulation and comfort.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed body, calm mind',
    recommendedAddOns: 'Aromatherapy, bolster support',
    whatToExpect: 'Soft, flowing strokes relieve tension in the back and legs while supporting emotional well-being. Improves circulation and comfort.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Bloom Prenatal Massage',
    shortDescription: 'Light massage with gentle stretching focuses on relieving tension and improving circulation. Encourages relaxation and emotional calm.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, arms',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced swelling and discomfort',
    recommendedAddOns: 'Pregnancy pillow, safe oils',
    whatToExpect: 'Light massage with gentle stretching focuses on relieving tension and improving circulation. Encourages relaxation and emotional calm.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Embrace Massage',
    shortDescription: 'A comforting massage designed to soothe muscles and joints during pregnancy. Light strokes and bolsters ensure safety and relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, shoulders, hips, legs',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal massage',
    postTreatmentNotes: 'Relaxed muscles, reduced tension',
    recommendedAddOns: 'Aromatherapy, bolster support',
    whatToExpect: 'A comforting massage designed to soothe muscles and joints during pregnancy. Light strokes and bolsters ensure safety and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Radiance Massage',
    shortDescription: 'Soft massage strokes combined with gentle stretching improve circulation and relieve tension. Focused on comfort for the mother-to-be.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body with emphasis on back and legs',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal-safe massage',
    postTreatmentNotes: 'Relaxed muscles, calm mind',
    recommendedAddOns: 'Safe essential oils, bolster support',
    whatToExpect: 'Soft massage strokes combined with gentle stretching improve circulation and relieve tension. Focused on comfort for the mother-to-be.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Glow Massage",
    shortDescription: 'Restorative massage that reduces back and leg discomfort. Gentle, nurturing strokes promote relaxation and emotional balance.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, hips, shoulders',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced fatigue, improved comfort',
    recommendedAddOns: 'Aromatherapy, pregnancy pillow',
    whatToExpect: 'Restorative massage that reduces back and leg discomfort. Gentle, nurturing strokes promote relaxation and emotional balance.',
    imageThumbnail: '',
  },
  {
    name: 'Serenity Nest Prenatal Massage',
    shortDescription: 'Focuses on comfort and gentle tension release in the back, legs, and hips. Supports relaxation and emotional calm.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, hips',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed muscles, improved mood',
    recommendedAddOns: 'Bolster support, aromatherapy',
    whatToExpect: 'Focuses on comfort and gentle tension release in the back, legs, and hips. Supports relaxation and emotional calm.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Heart Massage',
    shortDescription: 'Soft, flowing strokes reduce tension in the back, hips, and legs. Enhances circulation, comfort, and emotional well-being.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed body, reduced swelling',
    recommendedAddOns: 'Aromatherapy, bolsters',
    whatToExpect: 'Soft, flowing strokes reduce tension in the back, hips, and legs. Enhances circulation, comfort, and emotional well-being.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Harmony Flow Massage',
    shortDescription: 'Combines light strokes and gentle stretches to relieve muscle tension. Promotes calm, comfort, and circulation for expectant mothers.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal massage',
    postTreatmentNotes: 'Relaxed muscles, calm mind',
    recommendedAddOns: 'Safe essential oils, bolsters',
    whatToExpect: 'Combines light strokes and gentle stretches to relieve muscle tension. Promotes calm, comfort, and circulation for expectant mothers.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Radiance Prenatal Massage',
    shortDescription: 'Focuses on easing discomfort in the back, hips, and legs. Gentle massage strokes enhance comfort, circulation, and emotional well-being.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced tension, relaxed body',
    recommendedAddOns: 'Aromatherapy, bolster support',
    whatToExpect: 'Focuses on easing discomfort in the back, hips, and legs. Gentle massage strokes enhance comfort, circulation, and emotional well-being.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Whisper Flow Massage",
    shortDescription: 'Gentle nurturing strokes reduce swelling and tension. Enhances relaxation and emotional calm for the mother-to-be.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal massage',
    postTreatmentNotes: 'Relaxed body, improved circulation',
    recommendedAddOns: 'Bolsters, aromatherapy',
    whatToExpect: 'Gentle nurturing strokes reduce swelling and tension. Enhances relaxation and emotional calm for the mother-to-be.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Bloom Flow Massage',
    shortDescription: 'Soft, flowing strokes ease tension in the back, hips, and legs. Promotes relaxation, comfort, and emotional balance.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'Mid-pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Reduced swelling, relaxed muscles',
    recommendedAddOns: 'Pregnancy pillow, safe oils',
    whatToExpect: 'Soft, flowing strokes ease tension in the back, hips, and legs. Promotes relaxation, comfort, and emotional balance.',
    imageThumbnail: '',
  },
  {
    name: 'Nurturing Glow Prenatal Massage',
    shortDescription: 'Gentle massage that targets back, legs, and hips. Light stretching and soft strokes promote comfort and emotional calm.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, hips, legs, shoulders',
    idealFor: 'All trimesters',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying, prenatal-safe massage',
    postTreatmentNotes: 'Relaxed body, improved mood',
    recommendedAddOns: 'Bolster support, aromatherapy',
    whatToExpect: 'Gentle massage that targets back, legs, and hips. Light stretching and soft strokes promote comfort and emotional calm.',
    imageThumbnail: '',
  },
  {
    name: "Mother's Serenity Flow Massage",
    shortDescription: 'Restorative, gentle massage that relieves tension in the back, legs, and shoulders. Promotes circulation, comfort, and deep relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Mid to late pregnancy',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Side-lying prenatal-safe massage',
    postTreatmentNotes: 'Relaxed, calm, and supported',
    recommendedAddOns: 'Pregnancy pillow, safe essential oils',
    whatToExpect: 'Restorative, gentle massage that relieves tension in the back, legs, and shoulders. Promotes circulation, comfort, and deep relaxation.',
    imageThumbnail: '',
  },
];
