/**
 * Traditional Massage directory entries for dashboard (massage home service & massage city places).
 * Each entry appears in the Massage Types Directory; full content is shown in the (i) description
 * popup on the live site when the member has added the type to their menu price slider.
 * Image thumbnails can be set later via imageThumbnail URL.
 */

export interface TraditionalMassageDirectoryEntry {
  name: string;
  shortDescription: string;
  recommendedDuration: string;
  pressureLevel: string;
  focusAreas: string;
  idealFor: string;
  suggestedFrequency: string;
  techniqueStyle: string;
  postTreatmentNotes: string;
  recommendedAddOns: string;
  /** What to Expect paragraph (main description). */
  whatToExpect: string;
  /** Optional thumbnail URL for directory card and popup. Set later. */
  imageThumbnail: string;
}

/** Full content for popup: combines whatToExpect + all sections. */
export function getTraditionalMassagePopupContent(serviceName: string): string | null {
  const entry = TRADITIONAL_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (serviceName || '').toLowerCase().trim()
  );
  if (!entry) return null;
  const parts: string[] = [
    'What to Expect:',
    entry.whatToExpect,
    '',
    `Recommended Duration: ${entry.recommendedDuration}`,
    `Pressure Level: ${entry.pressureLevel}`,
    `Focus Areas: ${entry.focusAreas}`,
    `Ideal For: ${entry.idealFor}`,
    `Suggested Frequency: ${entry.suggestedFrequency}`,
    `Technique Style: ${entry.techniqueStyle}`,
    `Post-Treatment Notes: ${entry.postTreatmentNotes}`,
    `Recommended Add-Ons: ${entry.recommendedAddOns}`,
  ];
  return parts.join('\n');
}

export function getTraditionalMassageEntry(name: string): TraditionalMassageDirectoryEntry | undefined {
  return TRADITIONAL_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (name || '').toLowerCase().trim()
  );
}

export const TRADITIONAL_MASSAGE_DIRECTORY_NAMES = [
  'Office Relief Massage',
  'Deep Reset Massage',
  'Urban Escape Session',
  'Tension Release Therapy',
  'Serenity Flow Massage',
  'Muscle Ease Treatment',
  'Harmony Bodywork',
  'Stress Melt Session',
  'Rebalance Massage',
  'Calm Restore Therapy',
  'Pure Relaxation Session',
  'Vital Energy Massage',
  'Body Revival Treatment',
  'Total Unwind Massage',
  'Restore & Renew Session',
  'Inner Peace Massage',
  'Core Relief Therapy',
  'Energy Balance Session',
  'Comfort Touch Massage',
  'Gentle Pressure Therapy',
  'Wellness Flow Massage',
  'Signature Relax Session',
  'Daily Reset Massage',
  'Calm Mind Bodywork',
  'Full Body Recharge',
  'Tranquil Touch Therapy',
  'Release & Relax Massage',
  'Body Harmony Session',
  'Stress Away Massage',
  'Revive & Relax Treatment',
  'Peaceful Escape Massage',
  'Natural Balance Therapy',
  'Comfort Restore Massage',
  'Relaxation Ritual',
  'Total Body Ease',
  'Mind & Muscle Relief',
  'Reset & Recharge Massage',
  'Soothing Hands Therapy',
  'Energy Flow Session',
  'Restore Balance Massage',
  'Urban Calm Treatment',
  'Pure Bliss Session',
  'Body Reset Therapy',
  'Everyday Relief Massage',
  'Gentle Flow Massage',
  'Wellness Reset Session',
  'Deep Comfort Massage',
  'Calm Energy Therapy',
  'Relax & Revive Session',
  'Harmony Reset Massage',
] as const;

export const TRADITIONAL_MASSAGE_DIRECTORY_ENTRIES: TraditionalMassageDirectoryEntry[] = [
  {
    name: 'Office Relief Massage',
    shortDescription: 'Designed for individuals who sit for long hours or work at a desk. Focus on neck, shoulders, upper back, and arms. Targeted pressure helps relieve stiffness and improve posture.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Neck, shoulders, upper back, arms',
    idealFor: 'Office workers, students, remote workers',
    suggestedFrequency: '1–2 times weekly',
    techniqueStyle: 'Oil-based, targeted pressure, light stretching',
    postTreatmentNotes: 'Mild soreness possible if tension is heavy. Hydrate well.',
    recommendedAddOns: 'Head massage, hot towel therapy',
    whatToExpect:
      'Designed for individuals who sit for long hours or work at a desk. Focus is placed on the neck, shoulders, upper back, and arms where tension builds most. Targeted pressure helps relieve stiffness and improve posture. Gentle stretching may be included to restore mobility. You\'ll leave feeling lighter and more flexible.',
    imageThumbnail: '',
  },
  {
    name: 'Deep Reset Massage',
    shortDescription: 'Firm-pressure session targeting deep muscle layers. Releases chronic tightness and restores flexibility. Ideal for long-standing tension.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Strong ★★★',
    focusAreas: 'Back, hips, shoulders, legs',
    idealFor: 'Athletes, manual workers, chronic stiffness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep structured muscle work',
    postTreatmentNotes: 'Light soreness for 24 hours is normal.',
    recommendedAddOns: 'Hot stone, stretching enhancement',
    whatToExpect:
      'A firm-pressure session targeting deep muscle layers. Designed to release chronic tightness and restore flexibility. Slow, controlled movements focus on problem areas. Encourages muscle recovery and improved range of motion. Ideal for long-standing tension.',
    imageThumbnail: '',
  },
  {
    name: 'Urban Escape Session',
    shortDescription: 'A calming full-body experience to disconnect from daily stress. Smooth flowing strokes quiet the nervous system. Perfect for busy lifestyles.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stress relief, burnout, relaxation',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Oil-based, rhythmic flow',
    postTreatmentNotes: 'Deep relaxation or sleepiness afterward.',
    recommendedAddOns: 'Aromatherapy, scalp massage',
    whatToExpect:
      'A calming full-body experience to disconnect from daily stress. Smooth flowing strokes quiet the nervous system. Breathing naturally slows during the session. Encourages mental clarity and physical relaxation. Perfect for busy lifestyles.',
    imageThumbnail: '',
  },
  {
    name: 'Tension Release Therapy',
    shortDescription: 'Targets high-tension muscle groups with focused pressure. Reduces stiffness and discomfort. Improves mobility in restricted areas.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium to Strong ★★★',
    focusAreas: 'Back, shoulders, lower body',
    idealFor: 'Muscle tightness, stress tension',
    suggestedFrequency: '1–2 times weekly',
    techniqueStyle: 'Focused pressure therapy',
    postTreatmentNotes: 'Slight tenderness may occur.',
    recommendedAddOns: 'Hot towel therapy',
    whatToExpect:
      'Targets high-tension muscle groups with focused pressure. Designed to reduce stiffness and discomfort. Improves mobility in restricted areas. Helps relieve stress-related tightness. Leaves muscles feeling softer and more flexible.',
    imageThumbnail: '',
  },
  {
    name: 'Serenity Flow Massage',
    shortDescription: 'Gentle continuous strokes promote full relaxation. Encourages deep breathing and calmness. Ideal for emotional balance and stress relief.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'First-time clients, relaxation seekers',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Slow flowing oil massage',
    postTreatmentNotes: 'No downtime required.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Gentle continuous strokes promote full relaxation. Encourages deep breathing and calmness. Helps reduce nervous tension. Ideal for emotional balance and stress relief. Leaves body and mind peaceful.',
    imageThumbnail: '',
  },
  {
    name: 'Muscle Ease Treatment',
    shortDescription: 'Focused muscle work to relieve soreness. Improves blood circulation and flexibility. Targets everyday strain areas.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'Mild soreness, active individuals',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured muscle therapy',
    postTreatmentNotes: 'Hydration recommended.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused muscle work to relieve soreness. Improves blood circulation and flexibility. Targets everyday strain areas. Helps reduce mild to moderate discomfort. Encourages smoother movement.',
    imageThumbnail: '',
  },
  {
    name: 'Harmony Bodywork',
    shortDescription: 'Combines rhythmic pressure and gentle stretching. Encourages body alignment and flexibility. Improves posture support.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Posture improvement, flexibility',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Oil-based with stretching',
    postTreatmentNotes: 'Increased mobility afterward.',
    recommendedAddOns: 'Deep stretch add-on',
    whatToExpect:
      'Combines rhythmic pressure and gentle stretching. Encourages body alignment and flexibility. Improves posture support. Helps release muscle imbalance. Promotes full-body comfort.',
    imageThumbnail: '',
  },
  {
    name: 'Stress Melt Session',
    shortDescription: 'Slow soothing strokes calm the body. Designed to melt away physical and emotional stress. Improves sleep quality.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'Stress, anxiety, fatigue',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Gentle relaxation massage',
    postTreatmentNotes: 'Deep calmness expected.',
    recommendedAddOns: 'Scalp massage',
    whatToExpect:
      'Slow soothing strokes calm the body. Designed to melt away physical and emotional stress. Encourages relaxation and clarity. Improves sleep quality. Leaves you refreshed.',
    imageThumbnail: '',
  },
  {
    name: 'Rebalance Massage',
    shortDescription: 'Designed to correct uneven muscle tension across the body. Focuses on restoring symmetry and improving posture support. Helps improve movement efficiency and reduce strain patterns.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, hips, shoulders',
    idealFor: 'Postural imbalance, uneven tension, maintenance care',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured oil-based muscle balancing',
    postTreatmentNotes: 'Improved posture awareness after session.',
    recommendedAddOns: 'Stretch enhancement',
    whatToExpect:
      'Designed to correct uneven muscle tension across the body. This session focuses on restoring symmetry and improving posture support. Pressure is applied strategically to tight areas while relaxing overworked muscles. Helps improve movement efficiency and reduce strain patterns. Leaves you feeling physically aligned and balanced.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Restore Therapy',
    shortDescription: 'A deeply calming treatment designed to quiet both body and mind. Gentle pressure techniques reduce muscle tightness without intensity. Encourages slow breathing and nervous system reset.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'Stress relief, anxiety, light tension',
    suggestedFrequency: '1–2 times weekly',
    techniqueStyle: 'Slow rhythm oil massage',
    postTreatmentNotes: 'No soreness expected.',
    recommendedAddOns: 'Aromatherapy, scalp massage',
    whatToExpect:
      'A deeply calming treatment designed to quiet both body and mind. Gentle pressure techniques reduce muscle tightness without intensity. Encourages slow breathing and nervous system reset. Ideal for emotional and physical relaxation. Leaves you centered and refreshed.',
    imageThumbnail: '',
  },
  {
    name: 'Pure Relaxation Session',
    shortDescription: 'A smooth full-body session focused entirely on comfort. Light to moderate pressure encourages muscle relaxation. Promotes improved sleep quality. Ideal for clients seeking pure calmness.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'First-time clients, relaxation seekers',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Gentle oil-based relaxation',
    postTreatmentNotes: 'Deep relaxation and possible sleepiness.',
    recommendedAddOns: 'Hot towel therapy',
    whatToExpect:
      'A smooth full-body session focused entirely on comfort. Light to moderate pressure encourages muscle relaxation. Promotes improved sleep quality. Helps reduce daily stress levels. Ideal for clients seeking pure calmness.',
    imageThumbnail: '',
  },
  {
    name: 'Vital Energy Massage',
    shortDescription: 'A rhythmic session designed to stimulate circulation and energy flow. Combines moderate pressure with flowing movements. Helps reduce fatigue and improve alertness. Leaves you feeling energized yet relaxed.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Low energy, fatigue, active lifestyle',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Rhythmic oil massage',
    postTreatmentNotes: 'Increased energy levels after session.',
    recommendedAddOns: 'Foot reflex add-on',
    whatToExpect:
      'A rhythmic session designed to stimulate circulation and energy flow. Combines moderate pressure with flowing movements. Helps reduce fatigue and improve alertness. Encourages muscle responsiveness. Leaves you feeling energized yet relaxed.',
    imageThumbnail: '',
  },
  {
    name: 'Body Revival Treatment',
    shortDescription: 'Focused on restoring tired muscles and improving flexibility. Moderate pressure works into key tension areas. Encourages circulation and muscle recovery. Leaves the body feeling revived and mobile.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'Muscle fatigue, active individuals',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted muscle therapy',
    postTreatmentNotes: 'Light soreness possible if muscles are tight.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused on restoring tired muscles and improving flexibility. Moderate pressure works into key tension areas. Encourages circulation and muscle recovery. Helps reduce stiffness from daily activity. Leaves the body feeling revived and mobile.',
    imageThumbnail: '',
  },
  {
    name: 'Total Unwind Massage',
    shortDescription: 'A complete full-body relaxation journey. Slow, flowing strokes help reduce tension from head to toe. Encourages deep breathing and mental calmness. Ideal after a stressful week.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stress relief, relaxation, burnout',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Oil-based calming flow',
    postTreatmentNotes: 'Deep relaxation expected.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A complete full-body relaxation journey. Slow, flowing strokes help reduce tension from head to toe. Encourages deep breathing and mental calmness. Ideal after a stressful week. Leaves you completely unwound.',
    imageThumbnail: '',
  },
  {
    name: 'Restore & Renew Session',
    shortDescription: 'Designed to release muscle tension while improving flexibility. Moderate pressure targets tired muscle groups. Encourages circulation and recovery. Leaves the body refreshed and renewed.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body with tension focus',
    idealFor: 'Muscle tightness, weekly maintenance',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured muscle therapy',
    postTreatmentNotes: 'Hydration recommended.',
    recommendedAddOns: 'Hot stone therapy',
    whatToExpect:
      'Designed to release muscle tension while improving flexibility. Moderate pressure targets tired muscle groups. Encourages circulation and recovery. Helps restore natural movement. Leaves the body refreshed and renewed.',
    imageThumbnail: '',
  },
  {
    name: 'Inner Peace Massage',
    shortDescription: 'A gentle calming session aimed at emotional and physical balance. Slow consistent strokes relax the nervous system. Encourages deep breathing and mental clarity. Promotes a strong sense of peace and calm.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'Anxiety relief, emotional stress',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Soft flowing oil massage',
    postTreatmentNotes: 'Deep calmness and relaxation.',
    recommendedAddOns: 'Scalp massage, aromatherapy',
    whatToExpect:
      'A gentle calming session aimed at emotional and physical balance. Slow consistent strokes relax the nervous system. Encourages deep breathing and mental clarity. Ideal for those feeling overwhelmed. Promotes a strong sense of peace and calm.',
    imageThumbnail: '',
  },
  {
    name: 'Core Relief Therapy',
    shortDescription: 'Focused on the central structure of the body including lower back, hips, and abdominal tension areas. Helps relieve strain from prolonged sitting or physical work. Improves stability and posture support.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium to Strong ★★★',
    focusAreas: 'Lower back, hips, core',
    idealFor: 'Lower back discomfort, posture strain',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted structured muscle work',
    postTreatmentNotes: 'Mild soreness possible in tight areas.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused on the central structure of the body including lower back, hips, and abdominal tension areas. Helps relieve strain caused by prolonged sitting or physical work. Improves stability and posture support. Moderate to firm pressure is applied to release deep tightness. Leaves the core feeling supported and lighter.',
    imageThumbnail: '',
  },
  {
    name: 'Energy Balance Session',
    shortDescription: 'A structured full-body session designed to restore muscle harmony. Combines rhythmic pressure and relaxation techniques. Encourages improved circulation and natural body balance. Helps reduce both physical and mental fatigue.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Fatigue, imbalance, stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Oil-based balanced flow',
    postTreatmentNotes: 'Increased energy and clarity after session.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A structured full-body session designed to restore muscle harmony. Combines rhythmic pressure and relaxation techniques. Encourages improved circulation and natural body balance. Helps reduce both physical and mental fatigue. Leaves you feeling centered and refreshed.',
    imageThumbnail: '',
  },
  {
    name: 'Comfort Touch Massage',
    shortDescription: 'A soothing session using soft to moderate pressure. Designed to create a sense of safety and comfort. Encourages muscle relaxation without intensity. Helps calm the nervous system.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'First-time clients, relaxation seekers',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Gentle oil massage',
    postTreatmentNotes: 'No soreness expected.',
    recommendedAddOns: 'Hot towel therapy',
    whatToExpect:
      'A soothing session using soft to moderate pressure. Designed to create a sense of safety and comfort. Encourages muscle relaxation without intensity. Helps calm the nervous system. Ideal for clients preferring gentle therapy.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Pressure Therapy',
    shortDescription: 'Light to moderate pressure is applied to relieve mild tension. Designed to improve circulation without deep intensity. Encourages relaxation while maintaining comfort. Ideal for sensitive muscles.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sensitive clients, mild stiffness',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Soft structured pressure',
    postTreatmentNotes: 'No downtime required.',
    recommendedAddOns: 'Scalp massage',
    whatToExpect:
      'Light to moderate pressure is applied to relieve mild tension. Designed to improve circulation without deep intensity. Encourages relaxation while maintaining comfort. Ideal for sensitive muscles. Leaves the body relaxed and at ease.',
    imageThumbnail: '',
  },
  {
    name: 'Wellness Flow Massage',
    shortDescription: 'A continuous flowing full-body session promoting overall wellness. Combines smooth strokes with balanced pressure. Improves circulation and flexibility. Helps maintain muscle health.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Maintenance care, general wellness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Rhythmic oil-based flow',
    postTreatmentNotes: 'Light relaxation expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A continuous flowing full-body session promoting overall wellness. Combines smooth strokes with balanced pressure. Improves circulation and flexibility. Helps maintain muscle health. Leaves you feeling refreshed and aligned.',
    imageThumbnail: '',
  },
  {
    name: 'Signature Relax Session',
    shortDescription: 'A customizable relaxation-focused massage. Pressure is adjusted based on client preference. Designed to reduce stress and muscle tension. Encourages deep breathing and calmness.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body or client choice',
    idealFor: 'Stress relief, general relaxation',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Custom oil massage',
    postTreatmentNotes: 'Deep calm and improved sleep possible.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A customizable relaxation-focused massage. Pressure is adjusted based on client preference. Designed to reduce stress and muscle tension. Encourages deep breathing and calmness. Provides a personalized relaxation experience.',
    imageThumbnail: '',
  },
  {
    name: 'Daily Reset Massage',
    shortDescription: 'Ideal for routine muscle maintenance. Helps relieve daily built-up tension. Moderate pressure improves circulation. Encourages flexibility and smoother movement.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Daily tension, routine care',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Structured muscle maintenance',
    postTreatmentNotes: 'Minimal soreness expected.',
    recommendedAddOns: 'Foot reflex add-on',
    whatToExpect:
      'Ideal for routine muscle maintenance. Helps relieve daily built-up tension. Moderate pressure improves circulation. Encourages flexibility and smoother movement. Leaves you refreshed and ready for your day.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Mind Bodywork',
    shortDescription: 'A session designed to reduce both physical and mental stress. Gentle flowing techniques calm the nervous system. Encourages deeper breathing and relaxation. Helps reduce muscle tightness caused by stress.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Anxiety, stress, burnout',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Slow oil-based relaxation',
    postTreatmentNotes: 'Deep calmness and improved rest.',
    recommendedAddOns: 'Scalp massage, aromatherapy',
    whatToExpect:
      'A session designed to reduce both physical and mental stress. Gentle flowing techniques calm the nervous system. Encourages deeper breathing and relaxation. Helps reduce muscle tightness caused by stress. Leaves body and mind balanced.',
    imageThumbnail: '',
  },
  {
    name: 'Full Body Recharge',
    shortDescription: 'A revitalizing full-body session designed to restore energy and reduce fatigue. Moderate pressure techniques stimulate circulation and improve muscle responsiveness. Focus is evenly distributed across all major muscle groups.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Fatigue, low energy, active individuals',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured oil-based muscle therapy',
    postTreatmentNotes: 'Increased energy and improved mobility.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A revitalizing full-body session designed to restore energy and reduce fatigue. Moderate pressure techniques stimulate circulation and improve muscle responsiveness. Focus is evenly distributed across all major muscle groups. Helps reduce stiffness and improve flexibility. Leaves you feeling refreshed, alert, and recharged.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquil Touch Therapy',
    shortDescription: 'A deeply calming session using gentle flowing movements. Designed to relax the nervous system and reduce stress. Pressure remains light to ensure complete comfort. Encourages deep breathing and emotional balance.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'Stress relief, first-time clients',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Slow, soothing oil massage',
    postTreatmentNotes: 'Deep relaxation and calmness expected.',
    recommendedAddOns: 'Aromatherapy, scalp massage',
    whatToExpect:
      'A deeply calming session using gentle flowing movements. Designed to relax the nervous system and reduce stress. Pressure remains light to ensure complete comfort. Encourages deep breathing and emotional balance. Ideal for those seeking peaceful relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Release & Relax Massage',
    shortDescription: 'Combines focused pressure on tight areas with soothing relaxation strokes. Helps release built-up tension while maintaining comfort. Improves circulation and flexibility. Encourages muscle softness and ease.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Mild to moderate muscle tension',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted pressure with flowing finish',
    postTreatmentNotes: 'Mild tenderness possible in tight areas.',
    recommendedAddOns: 'Hot towel therapy',
    whatToExpect:
      'Combines focused pressure on tight areas with soothing relaxation strokes. Helps release built-up tension while maintaining comfort. Improves circulation and flexibility. Encourages muscle softness and ease. Leaves you relaxed but physically restored.',
    imageThumbnail: '',
  },
  {
    name: 'Body Harmony Session',
    shortDescription: 'A balanced massage designed to align muscle groups and improve natural movement. Combines moderate pressure with rhythmic techniques. Helps reduce uneven tension patterns. Encourages better posture and flexibility.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body with posture focus',
    idealFor: 'Muscle imbalance, posture support',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Oil-based structured therapy',
    postTreatmentNotes: 'Increased flexibility and smoother movement.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A balanced massage designed to align muscle groups and improve natural movement. Combines moderate pressure with rhythmic techniques. Helps reduce uneven tension patterns. Encourages better posture and flexibility. Leaves the body feeling balanced and coordinated.',
    imageThumbnail: '',
  },
  {
    name: 'Stress Away Massage',
    shortDescription: 'A calming full-body experience focused on reducing stress levels. Gentle to moderate pressure relaxes tight muscles. Encourages slow breathing and nervous system reset. Ideal for emotional and physical tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stress, anxiety, burnout',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Slow calming oil massage',
    postTreatmentNotes: 'Improved sleep and relaxation.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A calming full-body experience focused on reducing stress levels. Gentle to moderate pressure relaxes tight muscles. Encourages slow breathing and nervous system reset. Ideal for emotional and physical tension. Leaves you mentally refreshed and relaxed.',
    imageThumbnail: '',
  },
  {
    name: 'Revive & Relax Treatment',
    shortDescription: 'A combination of revitalizing pressure and soothing strokes. Helps relieve muscle fatigue while maintaining deep relaxation. Improves circulation and muscle flexibility. Designed to restore both body and mind.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Muscle fatigue, stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured muscle therapy with relaxation finish',
    postTreatmentNotes: 'Hydration recommended post-session.',
    recommendedAddOns: 'Hot stone therapy',
    whatToExpect:
      'A combination of revitalizing pressure and soothing strokes. Helps relieve muscle fatigue while maintaining deep relaxation. Improves circulation and muscle flexibility. Designed to restore both body and mind. Leaves you refreshed and calm.',
    imageThumbnail: '',
  },
  {
    name: 'Peaceful Escape Massage',
    shortDescription: 'A quiet, slow-paced session focused entirely on relaxation. Light pressure encourages total comfort. Helps reduce nervous tension and mental fatigue. Creates a calming sensory experience.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'Emotional stress, relaxation seekers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Gentle flowing oil massage',
    postTreatmentNotes: 'Deep relaxation and possible sleepiness.',
    recommendedAddOns: 'Scalp massage',
    whatToExpect:
      'A quiet, slow-paced session focused entirely on relaxation. Light pressure encourages total comfort. Helps reduce nervous tension and mental fatigue. Creates a calming sensory experience. Ideal for those seeking deep peace.',
    imageThumbnail: '',
  },
  {
    name: 'Natural Balance Therapy',
    shortDescription: 'Designed to restore natural muscle balance and flexibility. Moderate pressure focuses on correcting tension patterns. Encourages smoother body movement. Improves circulation and posture support.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Muscle imbalance, posture concerns',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured oil-based therapy',
    postTreatmentNotes: 'Improved mobility expected.',
    recommendedAddOns: 'Stretch enhancement',
    whatToExpect:
      'Designed to restore natural muscle balance and flexibility. Moderate pressure focuses on correcting tension patterns. Encourages smoother body movement. Improves circulation and posture support. Leaves the body feeling stable and aligned.',
    imageThumbnail: '',
  },
  {
    name: 'Comfort Restore Massage',
    shortDescription: 'A gentle to moderate session designed to restore overall body comfort. Focuses on relieving mild muscle soreness and stiffness. Smooth, steady strokes improve circulation and flexibility. Encourages relaxation without deep intensity.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Mild tension, general maintenance',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Oil-based relaxation with light structure',
    postTreatmentNotes: 'Minimal soreness expected.',
    recommendedAddOns: 'Hot towel therapy',
    whatToExpect:
      'A gentle to moderate session designed to restore overall body comfort. Focuses on relieving mild muscle soreness and stiffness. Smooth, steady strokes improve circulation and flexibility. Encourages relaxation without deep intensity. Leaves the body feeling comfortable and balanced.',
    imageThumbnail: '',
  },
  {
    name: 'Relaxation Ritual',
    shortDescription: 'A slow, structured session focused purely on relaxation. Gentle rhythmic strokes calm the nervous system. Encourages deep breathing and emotional ease. Ideal for unwinding after a stressful period.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'Stress relief, sleep improvement',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Slow flowing oil massage',
    postTreatmentNotes: 'Deep calmness and improved sleep possible.',
    recommendedAddOns: 'Aromatherapy, scalp massage',
    whatToExpect:
      'A slow, structured session focused purely on relaxation. Gentle rhythmic strokes calm the nervous system. Encourages deep breathing and emotional ease. Ideal for unwinding after a stressful period. Leaves you fully relaxed and mentally clear.',
    imageThumbnail: '',
  },
  {
    name: 'Total Body Ease',
    shortDescription: 'A full-body treatment focused on reducing everyday muscle tightness. Moderate pressure improves circulation and flexibility. Targets common tension areas such as back and shoulders. Encourages smoother movement and comfort.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Daily muscle strain, active lifestyle',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured oil-based muscle work',
    postTreatmentNotes: 'Light tenderness possible in tight spots.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A full-body treatment focused on reducing everyday muscle tightness. Moderate pressure improves circulation and flexibility. Targets common tension areas such as back and shoulders. Encourages smoother movement and comfort. Leaves you feeling physically lighter.',
    imageThumbnail: '',
  },
  {
    name: 'Mind & Muscle Relief',
    shortDescription: 'A balanced session addressing both physical tension and mental stress. Moderate pressure reduces muscle stiffness. Calming strokes help reset the nervous system. Encourages emotional and physical relaxation.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, neck, shoulders',
    idealFor: 'Stress-related tension, busy professionals',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Combination of targeted pressure and relaxation flow',
    postTreatmentNotes: 'Improved clarity and relaxation after session.',
    recommendedAddOns: 'Head massage',
    whatToExpect:
      'A balanced session addressing both physical tension and mental stress. Moderate pressure reduces muscle stiffness. Calming strokes help reset the nervous system. Encourages emotional and physical relaxation. Leaves you feeling refreshed and centered.',
    imageThumbnail: '',
  },
  {
    name: 'Reset & Recharge Massage',
    shortDescription: 'Designed to restore energy while relieving muscle tension. Moderate pressure stimulates circulation and muscle recovery. Focuses on revitalizing tired areas. Helps reduce fatigue and stiffness.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Fatigue, low energy, active individuals',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Rhythmic oil-based muscle therapy',
    postTreatmentNotes: 'Increased energy and mobility.',
    recommendedAddOns: 'Hot stone therapy',
    whatToExpect:
      'Designed to restore energy while relieving muscle tension. Moderate pressure stimulates circulation and muscle recovery. Focuses on revitalizing tired areas. Helps reduce fatigue and stiffness. Leaves you energized yet relaxed.',
    imageThumbnail: '',
  },
  {
    name: 'Soothing Hands Therapy',
    shortDescription: 'A comforting session using controlled, soothing hand techniques. Designed to calm muscle tension without strong intensity. Encourages relaxation and improved circulation. Ideal for sensitive clients.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'First-time clients, sensitive muscles',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Gentle oil massage',
    postTreatmentNotes: 'No soreness expected.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A comforting session using controlled, soothing hand techniques. Designed to calm muscle tension without strong intensity. Encourages relaxation and improved circulation. Ideal for sensitive clients. Leaves the body feeling safe and relaxed.',
    imageThumbnail: '',
  },
  {
    name: 'Energy Flow Session',
    shortDescription: 'A rhythmic session designed to stimulate circulation and natural body energy. Moderate pressure encourages muscle activation. Improves flexibility and movement. Helps reduce fatigue and tension.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Low energy, circulation improvement',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured rhythmic oil massage',
    postTreatmentNotes: 'Increased alertness and comfort.',
    recommendedAddOns: 'Foot reflex therapy',
    whatToExpect:
      'A rhythmic session designed to stimulate circulation and natural body energy. Moderate pressure encourages muscle activation. Improves flexibility and movement. Helps reduce fatigue and tension. Leaves you feeling balanced and revitalized.',
    imageThumbnail: '',
  },
  {
    name: 'Restore Balance Massage',
    shortDescription: 'Focused on correcting muscle tension patterns and restoring body harmony. Moderate pressure is applied to problem areas. Encourages improved posture and flexibility. Helps reduce strain caused by daily activity.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body with posture emphasis',
    idealFor: 'Muscle imbalance, posture concerns',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured oil-based therapy',
    postTreatmentNotes: 'Improved mobility and comfort.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'Focused on correcting muscle tension patterns and restoring body harmony. Moderate pressure is applied to problem areas. Encourages improved posture and flexibility. Helps reduce strain caused by daily activity. Leaves you feeling aligned and stable.',
    imageThumbnail: '',
  },
  {
    name: 'Urban Calm Treatment',
    shortDescription: 'Designed for those living a fast-paced lifestyle. This session focuses on calming the nervous system while easing muscle tension. Smooth, steady strokes reduce physical stress and mental overload. Moderate pressure improves circulation without intensity.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Busy professionals, stress relief',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Flowing oil-based relaxation',
    postTreatmentNotes: 'Deep calmness and mental clarity expected.',
    recommendedAddOns: 'Aromatherapy, scalp massage',
    whatToExpect:
      'Designed for those living a fast-paced lifestyle. This session focuses on calming the nervous system while easing muscle tension. Smooth, steady strokes reduce physical stress and mental overload. Moderate pressure improves circulation without intensity. Leaves you feeling grounded and relaxed.',
    imageThumbnail: '',
  },
  {
    name: 'Pure Bliss Session',
    shortDescription: 'A deeply soothing full-body experience designed for complete comfort. Gentle strokes encourage emotional and physical relaxation. Helps reduce muscle tension without firm pressure. Improves sleep quality and relaxation response.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'Relaxation seekers, stress relief',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Gentle flowing oil massage',
    postTreatmentNotes: 'No downtime required.',
    recommendedAddOns: 'Hot towel therapy',
    whatToExpect:
      'A deeply soothing full-body experience designed for complete comfort. Gentle strokes encourage emotional and physical relaxation. Helps reduce muscle tension without firm pressure. Improves sleep quality and relaxation response. Leaves you feeling completely at ease.',
    imageThumbnail: '',
  },
  {
    name: 'Body Reset Therapy',
    shortDescription: 'A structured session aimed at reducing accumulated muscle tension. Moderate pressure focuses on restoring flexibility and mobility. Targets areas of stiffness from daily activity. Encourages circulation and muscle recovery.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, legs, shoulders',
    idealFor: 'Muscle tightness, active lifestyle',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted oil-based muscle therapy',
    postTreatmentNotes: 'Mild soreness possible in tight areas.',
    recommendedAddOns: 'Stretch enhancement',
    whatToExpect:
      'A structured session aimed at reducing accumulated muscle tension. Moderate pressure focuses on restoring flexibility and mobility. Targets areas of stiffness from daily activity. Encourages circulation and muscle recovery. Leaves the body feeling reset and functional.',
    imageThumbnail: '',
  },
  {
    name: 'Everyday Relief Massage',
    shortDescription: 'A practical session designed to ease common daily aches. Moderate pressure improves blood flow and muscle comfort. Focuses on typical tension areas such as back and shoulders. Encourages smoother movement.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Back, shoulders, neck',
    idealFor: 'Daily tension, maintenance care',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Structured muscle relief',
    postTreatmentNotes: 'Minimal tenderness expected.',
    recommendedAddOns: 'Head massage',
    whatToExpect:
      'A practical session designed to ease common daily aches. Moderate pressure improves blood flow and muscle comfort. Focuses on typical tension areas such as back and shoulders. Encourages smoother movement. Leaves you comfortable and refreshed.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Flow Massage',
    shortDescription: 'Light, continuous strokes promote deep relaxation. Designed to calm both body and mind. Encourages improved circulation without strong pressure. Ideal for sensitive clients.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★☆☆',
    focusAreas: 'Full body',
    idealFor: 'First-time clients, relaxation',
    suggestedFrequency: '1–2 weekly',
    techniqueStyle: 'Slow flowing oil massage',
    postTreatmentNotes: 'Deep relaxation and possible sleepiness.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Light, continuous strokes promote deep relaxation. Designed to calm both body and mind. Encourages improved circulation without strong pressure. Ideal for sensitive clients. Leaves you feeling peaceful and balanced.',
    imageThumbnail: '',
  },
  {
    name: 'Wellness Reset Session',
    shortDescription: 'A balanced full-body session designed to restore muscle health. Moderate pressure works into key tension areas. Improves flexibility and circulation. Encourages overall body maintenance.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Weekly maintenance, general wellness',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured oil-based therapy',
    postTreatmentNotes: 'Improved mobility expected.',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A balanced full-body session designed to restore muscle health. Moderate pressure works into key tension areas. Improves flexibility and circulation. Encourages overall body maintenance. Leaves you feeling stable and refreshed.',
    imageThumbnail: '',
  },
  {
    name: 'Deep Comfort Massage',
    shortDescription: 'Firm yet controlled pressure targets deep muscle tension. Designed to relieve chronic tightness and stiffness. Encourages muscle recovery and flexibility. Works thoroughly through major muscle groups.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Strong ★★★',
    focusAreas: 'Back, hips, legs',
    idealFor: 'Chronic tension, athletes, manual workers',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Deep structured muscle work',
    postTreatmentNotes: 'Soreness for up to 24 hours possible. Hydration recommended.',
    recommendedAddOns: 'Hot stone therapy',
    whatToExpect:
      'Firm yet controlled pressure targets deep muscle tension. Designed to relieve chronic tightness and stiffness. Encourages muscle recovery and flexibility. Works thoroughly through major muscle groups. Leaves the body deeply relaxed and relieved.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Energy Therapy',
    shortDescription: 'A session combining gentle relaxation with subtle revitalizing techniques. Moderate pressure helps balance muscle tension. Encourages emotional calmness and improved circulation. Ideal for restoring natural energy levels.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Fatigue, stress, balance',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Rhythmic oil massage',
    postTreatmentNotes: 'Balanced energy and relaxation.',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A session combining gentle relaxation with subtle revitalizing techniques. Moderate pressure helps balance muscle tension. Encourages emotional calmness and improved circulation. Ideal for restoring natural energy levels. Leaves you feeling relaxed yet alert.',
    imageThumbnail: '',
  },
  {
    name: 'Relax & Revive Session',
    shortDescription: 'A combination of soothing strokes and moderate pressure. Designed to reduce muscle fatigue while maintaining relaxation. Improves circulation and flexibility. Encourages overall body comfort.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Muscle fatigue, stress relief',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured muscle therapy with relaxation flow',
    postTreatmentNotes: 'Light tenderness possible in tight areas.',
    recommendedAddOns: 'Hot towel therapy',
    whatToExpect:
      'A combination of soothing strokes and moderate pressure. Designed to reduce muscle fatigue while maintaining relaxation. Improves circulation and flexibility. Encourages overall body comfort. Leaves you refreshed and revived.',
    imageThumbnail: '',
  },
  {
    name: 'Harmony Reset Massage',
    shortDescription: 'A comprehensive session designed to restore balance across the entire body. Moderate pressure releases muscle tension while maintaining comfort. Encourages improved posture and flexibility. Helps reset the body after stress or physical strain.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Muscle imbalance, weekly maintenance',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Structured oil-based balancing therapy',
    postTreatmentNotes: 'Improved movement and relaxation expected.',
    recommendedAddOns: 'Stretch therapy, aromatherapy',
    whatToExpect:
      'A comprehensive session designed to restore balance across the entire body. Moderate pressure releases muscle tension while maintaining comfort. Encourages improved posture and flexibility. Helps reset the body after stress or physical strain. Leaves you feeling aligned, relaxed, and stable.',
    imageThumbnail: '',
  },
];
