/**
 * Couples & Romantic Spa directory entries.
 * Place directory only — NOT available for Home Service providers.
 * Display rule: Massage Places Directory Dashboard only; must NOT be available for Home Service.
 */

export interface CouplesMassageDirectoryEntry {
  name: string;
  shortDescription: string;
  recommendedDuration: string;
  pressureLevel: string;
  focusAreas: string;
  idealFor: string;
  suggestedFrequency: string;
  techniqueStyle: string;
  postTreatmentNotes: string;
  recommendedAddOns: string;
  whatToExpect: string;
  imageThumbnail: string;
}

export function getCouplesMassagePopupContent(serviceName: string): string | null {
  const entry = COUPLES_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (serviceName || '').toLowerCase().trim()
  );
  if (!entry) return null;
  const parts: string[] = [
    'What to Expect:',
    entry.whatToExpect,
    '',
    `Recommended Duration: ${entry.recommendedDuration}`,
    `Pressure Level: ${entry.pressureLevel}`,
    `Focus Areas: ${entry.focusAreas}`,
    `Ideal For: ${entry.idealFor}`,
    `Suggested Frequency: ${entry.suggestedFrequency}`,
    `Technique Style: ${entry.techniqueStyle}`,
    `Post-Treatment Notes: ${entry.postTreatmentNotes}`,
    `Recommended Add-Ons: ${entry.recommendedAddOns}`,
  ];
  return parts.join('\n');
}

export function getCouplesMassageEntry(name: string): CouplesMassageDirectoryEntry | undefined {
  return COUPLES_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (name || '').toLowerCase().trim()
  );
}

export const COUPLES_MASSAGE_DIRECTORY_NAMES = [
  'Classic Couples Relaxation Massage',
  'Romantic Candlelight Couples Massage',
  'Luxury Couples Spa Ritual',
  'His & Hers Signature Massage',
  'Honeymoon Bliss Massage',
  'Warm Oil Couples Massage',
  'Chocolate Indulgence Couples Massage',
  'Hot Stone Couples Retreat',
  'Sunset Romance Massage',
  'Anniversary Celebration Spa Package',
  'Private Suite Couples Escape',
  'Gold Ritual Couples Massage',
  'Rose Petal Romance Therapy',
  'Couples Aroma Journey',
  'Harmony Connection Massage',
  'Serenity Duo Spa Experience',
  'Deep Relax Couples Therapy',
  'Couples Detox & Relax Ritual',
  'Midnight Calm Massage for Two',
  'Royal Couples Indulgence',
  'Couples Bamboo Relax Therapy',
  'Ocean Breeze Duo Massage',
  'Couples Head-to-Toe Retreat',
  'Blissful Together Massage',
  'Couples Herbal Compress Therapy',
  'Romantic Escape Deluxe Package',
  'Premium Duo Relaxation Therapy',
  'Couples Stress Release Session',
  'Lovers Luxury Oil Massage',
  'Couples Wellness Reset',
  'Couples Dream State Therapy',
  'Elite Romantic Experience',
  'Couples Tension Relief Therapy',
  'Champagne & Chocolate Couples Package',
  'Anniversary Romantic Spa Package',
  'Honeymoon Couples Spa Experience',
  'Engagement Celebration Spa Package',
  'Private Jacuzzi & Massage Package',
  'Sunset Couples Beach Massage',
  'Villa Private Couples Massage',
  'Romantic Rose Petal Spa Setup',
  'Gold & Honey Couples Ritual',
  'Aromatherapy Lovers Escape',
  'Romantic Spa & Dinner Package',
  'His & Hers Relaxation Package',
  'Chocolate Body Wrap for Two',
  'Four Hands Couples Experience',
  'Love Escape Spa Retreat',
  'Romantic Weekend Spa Package',
  'VIP Private Couples Spa Suite',
] as const;

export const COUPLES_MASSAGE_DIRECTORY_ENTRIES: CouplesMassageDirectoryEntry[] = [
  {
    name: 'Classic Couples Relaxation Massage',
    shortDescription: 'Side-by-side full-body relaxation massage in a private couples suite.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Couples seeking shared relaxation',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Swedish-based relaxation',
    postTreatmentNotes: 'Shared calm and emotional connection',
    recommendedAddOns: 'Aromatherapy upgrade',
    whatToExpect: 'Side-by-side full-body relaxation massage in a private couples suite.',
    imageThumbnail: '',
  },
  {
    name: 'Romantic Candlelight Couples Massage',
    shortDescription: 'A side-by-side massage in a softly lit candle setting for an intimate spa experience.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Anniversaries and romantic occasions',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Flow relaxation therapy',
    postTreatmentNotes: 'Deep relaxation and romantic ambiance',
    recommendedAddOns: 'Rose oil enhancement',
    whatToExpect: 'A side-by-side massage in a softly lit candle setting for an intimate spa experience.',
    imageThumbnail: '',
  },
  {
    name: 'Luxury Couples Spa Ritual',
    shortDescription: 'A premium spa experience combining massage, warm oils, and calming atmosphere.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Luxury spa seekers',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Integrated spa therapy',
    postTreatmentNotes: 'Elevated relaxation and bonding',
    recommendedAddOns: 'Hot stones',
    whatToExpect: 'A premium spa experience combining massage, warm oils, and calming atmosphere.',
    imageThumbnail: '',
  },
  {
    name: 'His & Hers Signature Massage',
    shortDescription: 'Customized massage styles tailored individually while sharing the same room.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Customizable ★★☆ to ★★★★',
    focusAreas: 'Customized per guest',
    idealFor: 'Couples with different pressure preferences',
    suggestedFrequency: 'As needed',
    techniqueStyle: 'Personalized spa therapy',
    postTreatmentNotes: 'Individual comfort with shared experience',
    recommendedAddOns: 'Scalp therapy',
    whatToExpect: 'Customized massage styles tailored individually while sharing the same room.',
    imageThumbnail: '',
  },
  {
    name: 'Honeymoon Bliss Massage',
    shortDescription: 'A soothing couples massage designed for newlyweds or romantic getaways.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Honeymooners',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Relaxation flow therapy',
    postTreatmentNotes: 'Emotional warmth and relaxation',
    recommendedAddOns: 'Flower bath',
    whatToExpect: 'A soothing couples massage designed for newlyweds or romantic getaways.',
    imageThumbnail: '',
  },
  {
    name: 'Warm Oil Couples Massage',
    shortDescription: 'Heated oils used for deep relaxation side-by-side.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Stress relief together',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Warm oil therapy',
    postTreatmentNotes: 'Muscle softness',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect: 'Heated oils used for deep relaxation side-by-side.',
    imageThumbnail: '',
  },
  {
    name: 'Chocolate Indulgence Couples Massage',
    shortDescription: 'Massage using warm chocolate-infused oil.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Romantic spa indulgence',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Sensory relaxation therapy',
    postTreatmentNotes: 'Smooth skin and uplifted mood',
    recommendedAddOns: 'Body polish',
    whatToExpect: 'Massage using warm chocolate-infused oil.',
    imageThumbnail: '',
  },
  {
    name: 'Hot Stone Couples Retreat',
    shortDescription: 'Warm stones placed and glided during massage.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back and shoulders',
    idealFor: 'Deep muscle relaxation',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Stone-assisted therapy',
    postTreatmentNotes: 'Deep warmth',
    recommendedAddOns: 'Oil enhancement',
    whatToExpect: 'Warm stones placed and glided during massage.',
    imageThumbnail: '',
  },
  {
    name: 'Sunset Romance Massage',
    shortDescription: 'Couples massage designed for evening relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★',
    focusAreas: 'Full body',
    idealFor: 'Evening spa dates',
    suggestedFrequency: 'As desired',
    techniqueStyle: 'Gentle relaxation massage',
    postTreatmentNotes: 'Calm mood',
    recommendedAddOns: 'Lavender oil',
    whatToExpect: 'Couples massage designed for evening relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Anniversary Celebration Spa Package',
    shortDescription: 'Extended couples session with relaxation focus.',
    recommendedDuration: '120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Anniversary celebrations',
    suggestedFrequency: 'Yearly',
    techniqueStyle: 'Multi-technique spa therapy',
    postTreatmentNotes: 'Deep shared relaxation',
    recommendedAddOns: 'Champagne service',
    whatToExpect: 'Extended couples session with relaxation focus.',
    imageThumbnail: '',
  },
  {
    name: 'Private Suite Couples Escape',
    shortDescription: 'A side-by-side massage in an exclusive private spa suite designed for intimacy and comfort.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples seeking privacy and relaxation',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Relaxation flow therapy',
    postTreatmentNotes: 'Deep calm and enhanced connection',
    recommendedAddOns: 'Aromatherapy oils',
    whatToExpect: 'A side-by-side massage in an exclusive private spa suite designed for intimacy and comfort.',
    imageThumbnail: '',
  },
  {
    name: 'Gold Ritual Couples Massage',
    shortDescription: 'A luxurious couples massage using enriched oils and slow rhythmic techniques.',
    recommendedDuration: '75–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Premium spa guests',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Luxury relaxation therapy',
    postTreatmentNotes: 'Softened muscles and glowing skin',
    recommendedAddOns: 'Hot stone enhancement',
    whatToExpect: 'A luxurious couples massage using enriched oils and slow rhythmic techniques.',
    imageThumbnail: '',
  },
  {
    name: 'Rose Petal Romance Therapy',
    shortDescription: 'A romantic couples massage in a rose-petal prepared spa room for a sensory experience.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Anniversaries and date nights',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Gentle relaxation massage',
    postTreatmentNotes: 'Emotional warmth and relaxation',
    recommendedAddOns: 'Rose oil upgrade',
    whatToExpect: 'A romantic couples massage in a rose-petal prepared spa room for a sensory experience.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Aroma Journey',
    shortDescription: 'Side-by-side aromatherapy massage using customized essential oil blends.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stress relief and emotional bonding',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Aromatherapy relaxation therapy',
    postTreatmentNotes: 'Calm mood and improved breathing',
    recommendedAddOns: 'Scalp massage',
    whatToExpect: 'Side-by-side aromatherapy massage using customized essential oil blends.',
    imageThumbnail: '',
  },
  {
    name: 'Harmony Connection Massage',
    shortDescription: 'A synchronized couples massage designed to create balance and shared relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples wanting deeper connection',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Coordinated relaxation therapy',
    postTreatmentNotes: 'Harmonized energy and reduced tension',
    recommendedAddOns: 'Warm oil therapy',
    whatToExpect: 'A synchronized couples massage designed to create balance and shared relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Serenity Duo Spa Experience',
    shortDescription: 'A calming spa session combining massage and soothing ambiance in a shared room.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Busy couples needing stress relief',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Flow-based relaxation massage',
    postTreatmentNotes: 'Reduced muscle stiffness',
    recommendedAddOns: 'Hot towel compress',
    whatToExpect: 'A calming spa session combining massage and soothing ambiance in a shared room.',
    imageThumbnail: '',
  },
  {
    name: 'Deep Relax Couples Therapy',
    shortDescription: 'A deeper-pressure couples massage targeting muscle tension while maintaining a relaxing pace.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Back and shoulders',
    idealFor: 'Active couples with muscle tightness',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Deep relaxation bodywork',
    postTreatmentNotes: 'Improved flexibility and tension relief',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect: 'A deeper-pressure couples massage targeting muscle tension while maintaining a relaxing pace.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Detox & Relax Ritual',
    shortDescription: 'A detox-focused couples massage encouraging circulation and relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Fatigue and stress recovery',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Detoxifying spa therapy',
    postTreatmentNotes: 'Lighter body sensation',
    recommendedAddOns: 'Dry brushing',
    whatToExpect: 'A detox-focused couples massage encouraging circulation and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Midnight Calm Massage for Two',
    shortDescription: 'An evening couples massage designed to promote sleep and deep relaxation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Night-time relaxation',
    suggestedFrequency: 'As desired',
    techniqueStyle: 'Nervous system calming therapy',
    postTreatmentNotes: 'Improved sleep quality',
    recommendedAddOns: 'Lavender oil',
    whatToExpect: 'An evening couples massage designed to promote sleep and deep relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Couples Indulgence',
    shortDescription: 'A premium spa treatment combining massage and luxury elements in a private suite.',
    recommendedDuration: '120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Special celebrations',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Multi-technique spa integration',
    postTreatmentNotes: 'Deep relaxation and shared indulgence',
    recommendedAddOns: 'Hot stones and aromatherapy',
    whatToExpect: 'A premium spa treatment combining massage and luxury elements in a private suite.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Bamboo Relax Therapy',
    shortDescription: 'Heated bamboo sticks are used during a side-by-side massage to ease muscle tension.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Back and legs',
    idealFor: 'Muscle tightness',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Bamboo rolling therapy',
    postTreatmentNotes: 'Improved circulation and flexibility',
    recommendedAddOns: 'Oil enhancement',
    whatToExpect: 'Heated bamboo sticks are used during a side-by-side massage to ease muscle tension.',
    imageThumbnail: '',
  },
  {
    name: 'Ocean Breeze Duo Massage',
    shortDescription: 'A refreshing side-by-side massage inspired by calming coastal relaxation techniques.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Stress and fatigue relief',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Flow-based relaxation therapy',
    postTreatmentNotes: 'Re-energized body and calm mind',
    recommendedAddOns: 'Cooling gel treatment',
    whatToExpect: 'A refreshing side-by-side massage inspired by calming coastal relaxation techniques.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Head-to-Toe Retreat',
    shortDescription: 'A comprehensive couples massage covering scalp to feet for complete relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Total body reset together',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Integrated full-body relaxation',
    postTreatmentNotes: 'Balanced muscles and deep calm',
    recommendedAddOns: 'Scalp therapy',
    whatToExpect: 'A comprehensive couples massage covering scalp to feet for complete relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Together Massage',
    shortDescription: 'A synchronized couples massage designed to create a shared relaxation rhythm.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Couples wanting gentle shared relaxation',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Coordinated relaxation flow',
    postTreatmentNotes: 'Emotional connection and stress relief',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect: 'A synchronized couples massage designed to create a shared relaxation rhythm.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Herbal Compress Therapy',
    shortDescription: 'Heated herbal pouches applied during a side-by-side massage to ease tension.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back and legs',
    idealFor: 'Muscle stiffness and fatigue',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Herbal compress therapy',
    postTreatmentNotes: 'Improved circulation and muscle softness',
    recommendedAddOns: 'Warm oil finish',
    whatToExpect: 'Heated herbal pouches applied during a side-by-side massage to ease tension.',
    imageThumbnail: '',
  },
  {
    name: 'Romantic Escape Deluxe Package',
    shortDescription: 'An extended couples spa session combining massage and relaxation enhancements.',
    recommendedDuration: '120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Special romantic celebrations',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Multi-element spa ritual',
    postTreatmentNotes: 'Deep relaxation and shared indulgence',
    recommendedAddOns: 'Flower bath',
    whatToExpect: 'An extended couples spa session combining massage and relaxation enhancements.',
    imageThumbnail: '',
  },
  {
    name: 'Premium Duo Relaxation Therapy',
    shortDescription: 'A tailored couples massage focusing on comfort and synchronized relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples seeking luxury spa time',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Premium relaxation therapy',
    postTreatmentNotes: 'Muscle relief and emotional calm',
    recommendedAddOns: 'Hot stone therapy',
    whatToExpect: 'A tailored couples massage focusing on comfort and synchronized relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Stress Release Session',
    shortDescription: 'A focused couples massage targeting neck, shoulders, and upper back tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Neck, shoulders, upper back',
    idealFor: 'Working couples with stress buildup',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Targeted tension relief',
    postTreatmentNotes: 'Reduced stiffness and improved posture',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect: 'A focused couples massage targeting neck, shoulders, and upper back tension.',
    imageThumbnail: '',
  },
  {
    name: 'Lovers Luxury Oil Massage',
    shortDescription: 'A warm oil couples massage emphasizing smooth, flowing strokes.',
    recommendedDuration: '75–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Romantic spa evenings',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Warm oil relaxation therapy',
    postTreatmentNotes: 'Softened muscles and hydrated skin',
    recommendedAddOns: 'Aromatherapy upgrade',
    whatToExpect: 'A warm oil couples massage emphasizing smooth, flowing strokes.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Wellness Reset',
    shortDescription: 'A restorative couples massage aimed at relieving accumulated tension.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Stress recovery and wellness maintenance',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Integrated wellness bodywork',
    postTreatmentNotes: 'Renewed energy and balance',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect: 'A restorative couples massage aimed at relieving accumulated tension.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Dream State Therapy',
    shortDescription: 'A slow rhythmic couples massage encouraging deep relaxation and improved sleep.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sleep support and stress relief',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Nervous system calming therapy',
    postTreatmentNotes: 'Enhanced sleep quality',
    recommendedAddOns: 'Lavender oil',
    whatToExpect: 'A slow rhythmic couples massage encouraging deep relaxation and improved sleep.',
    imageThumbnail: '',
  },
  {
    name: 'Elite Romantic Experience',
    shortDescription: 'A high-end couples spa session with customized massage pressure and ambiance.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Customizable ★★☆ to ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Luxury-focused couples',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Personalized spa integration',
    postTreatmentNotes: 'Deep relaxation and shared indulgence',
    recommendedAddOns: 'Hot stones and aromatherapy',
    whatToExpect: 'A high-end couples spa session with customized massage pressure and ambiance.',
    imageThumbnail: '',
  },
  {
    name: 'Couples Tension Relief Therapy',
    shortDescription: 'A couples massage targeting deeper muscle tension while maintaining a relaxing atmosphere.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Active couples with muscle tightness',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Deep relaxation bodywork',
    postTreatmentNotes: 'Improved flexibility and muscle comfort',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect: 'A couples massage targeting deeper muscle tension while maintaining a relaxing atmosphere.',
    imageThumbnail: '',
  },
  {
    name: 'Champagne & Chocolate Couples Package',
    shortDescription: 'A luxurious couples massage incorporating warm chocolate oils and light champagne aromatherapy, creating a sensual and indulgent experience.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Romantic celebrations or indulgent evenings',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Sensory indulgence massage',
    postTreatmentNotes: 'Softened muscles and heightened mood',
    recommendedAddOns: 'Flower petals, scalp therapy',
    whatToExpect: 'A luxurious couples massage incorporating warm chocolate oils and light champagne aromatherapy, creating a sensual and indulgent experience.',
    imageThumbnail: '',
  },
  {
    name: 'Anniversary Romantic Spa Package',
    shortDescription: 'A tailored couples massage celebrating your relationship milestone with soothing oils, gentle strokes, and intimate ambiance.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Anniversaries and couple milestones',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Flow-based relaxation therapy',
    postTreatmentNotes: 'Enhanced bonding and deep relaxation',
    recommendedAddOns: 'Hot stones, aromatherapy',
    whatToExpect: 'A tailored couples massage celebrating your relationship milestone with soothing oils, gentle strokes, and intimate ambiance.',
    imageThumbnail: '',
  },
  {
    name: 'Honeymoon Couples Spa Experience',
    shortDescription: 'A romantic full-body massage for newlyweds, combining gentle pressure, aromatherapy, and a serene atmosphere.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Newlyweds and honeymooners',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Gentle relaxation therapy',
    postTreatmentNotes: 'Emotional warmth and shared calm',
    recommendedAddOns: 'Flower bath, candle setup',
    whatToExpect: 'A romantic full-body massage for newlyweds, combining gentle pressure, aromatherapy, and a serene atmosphere.',
    imageThumbnail: '',
  },
  {
    name: 'Engagement Celebration Spa Package',
    shortDescription: 'A couples massage designed to celebrate engagement, with synchronized strokes and a private spa suite ambiance.',
    recommendedDuration: '75–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples celebrating engagements',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Partner-focused relaxation therapy',
    postTreatmentNotes: 'Deep relaxation and joyful bonding',
    recommendedAddOns: 'Aromatherapy oils, hot towel treatment',
    whatToExpect: 'A couples massage designed to celebrate engagement, with synchronized strokes and a private spa suite ambiance.',
    imageThumbnail: '',
  },
  {
    name: 'Private Jacuzzi & Massage Package',
    shortDescription: 'Combine side-by-side massage with private jacuzzi time for ultimate relaxation and romantic indulgence.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples looking for complete spa immersion',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Multi-sensory relaxation therapy',
    postTreatmentNotes: 'Muscles softened, mind calmed',
    recommendedAddOns: 'Aromatherapy, flower petals',
    whatToExpect: 'Combine side-by-side massage with private jacuzzi time for ultimate relaxation and romantic indulgence.',
    imageThumbnail: '',
  },
  {
    name: 'Sunset Couples Beach Massage',
    shortDescription: 'A romantic massage experience on the beach during sunset with gentle flowing strokes and soft ambient sounds.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Romantic outdoor spa experiences',
    suggestedFrequency: 'Seasonal or special trips',
    techniqueStyle: 'Relaxation flow therapy',
    postTreatmentNotes: 'Emotional calm and scenic memory',
    recommendedAddOns: 'Aromatherapy, light refreshments',
    whatToExpect: 'A romantic massage experience on the beach during sunset with gentle flowing strokes and soft ambient sounds.',
    imageThumbnail: '',
  },
  {
    name: 'Villa Private Couples Massage',
    shortDescription: 'An exclusive couples massage in a private villa or suite, offering privacy, luxury, and a serene environment.',
    recommendedDuration: '90–120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'VIP clients and special celebrations',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Personalized luxury therapy',
    postTreatmentNotes: 'Deep relaxation, intimate experience',
    recommendedAddOns: 'Hot stones, aromatherapy',
    whatToExpect: 'An exclusive couples massage in a private villa or suite, offering privacy, luxury, and a serene environment.',
    imageThumbnail: '',
  },
  {
    name: 'Romantic Rose Petal Spa Setup',
    shortDescription: 'Side-by-side massage in a spa room decorated with rose petals for a sensual and romantic atmosphere.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Light ★★',
    focusAreas: 'Full body',
    idealFor: 'Anniversaries, Valentine\'s Day, or special dates',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Gentle flow relaxation therapy',
    postTreatmentNotes: 'Emotional connection and calming effect',
    recommendedAddOns: 'Scalp therapy, rose oil',
    whatToExpect: 'Side-by-side massage in a spa room decorated with rose petals for a sensual and romantic atmosphere.',
    imageThumbnail: '',
  },
  {
    name: 'Gold & Honey Couples Ritual',
    shortDescription: 'A luxurious treatment with warm honey and gold-infused oils to soften skin and relax muscles.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples seeking a premium spa experience',
    suggestedFrequency: 'Monthly or special events',
    techniqueStyle: 'Sensory indulgence therapy',
    postTreatmentNotes: 'Softened skin, relaxed muscles',
    recommendedAddOns: 'Hot stones, aromatherapy',
    whatToExpect: 'A luxurious treatment with warm honey and gold-infused oils to soften skin and relax muscles.',
    imageThumbnail: '',
  },
  {
    name: 'Aromatherapy Lovers Escape',
    shortDescription: 'A calming couples massage focused on essential oils to relax the mind and enhance emotional connection.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Couples looking for stress relief and emotional bonding',
    suggestedFrequency: 'Weekly or monthly',
    techniqueStyle: 'Aromatherapy massage',
    postTreatmentNotes: 'Emotional balance and calm mood',
    recommendedAddOns: 'Scalp massage, flower bath',
    whatToExpect: 'A calming couples massage focused on essential oils to relax the mind and enhance emotional connection.',
    imageThumbnail: '',
  },
  {
    name: 'Romantic Spa & Dinner Package',
    shortDescription: 'A full couples massage followed by an intimate dinner, combining relaxation and romantic dining.',
    recommendedDuration: '120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Special romantic celebrations',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Full sensory spa experience',
    postTreatmentNotes: 'Relaxed muscles, emotional connection',
    recommendedAddOns: 'Candlelit setup, hot stones',
    whatToExpect: 'A full couples massage followed by an intimate dinner, combining relaxation and romantic dining.',
    imageThumbnail: '',
  },
  {
    name: 'His & Hers Relaxation Package',
    shortDescription: 'Tailored massage for each partner while sharing the same private suite, providing individual attention and shared relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Customizable ★★☆ to ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples with different preferences',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Personalized dual therapy',
    postTreatmentNotes: 'Muscles relaxed and shared comfort',
    recommendedAddOns: 'Aromatherapy, scalp therapy',
    whatToExpect: 'Tailored massage for each partner while sharing the same private suite, providing individual attention and shared relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Chocolate Body Wrap for Two',
    shortDescription: 'Couples enjoy a chocolate-infused body wrap followed by a side-by-side massage, promoting skin hydration and relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Romantic indulgence and skin care',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Sensory indulgence therapy',
    postTreatmentNotes: 'Soft skin and relaxed muscles',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect: 'Couples enjoy a chocolate-infused body wrap followed by a side-by-side massage, promoting skin hydration and relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Four Hands Couples Experience',
    shortDescription: 'Two therapists simultaneously work on the couple, delivering a synchronized four-handed massage.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples seeking deep relaxation and luxury',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Multi-therapist synchronized therapy',
    postTreatmentNotes: 'Deep tension release and shared bliss',
    recommendedAddOns: 'Hot stones, aromatherapy',
    whatToExpect: 'Two therapists simultaneously work on the couple, delivering a synchronized four-handed massage.',
    imageThumbnail: '',
  },
  {
    name: 'Love Escape Spa Retreat',
    shortDescription: 'Extended couples spa retreat including massage, aromatherapy, and relaxation rituals for a full sensory escape.',
    recommendedDuration: '120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples seeking immersive relaxation',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Multi-element retreat therapy',
    postTreatmentNotes: 'Muscles relaxed, deep emotional connection',
    recommendedAddOns: 'Hot stone therapy, flower bath',
    whatToExpect: 'Extended couples spa retreat including massage, aromatherapy, and relaxation rituals for a full sensory escape.',
    imageThumbnail: '',
  },
  {
    name: 'Romantic Weekend Spa Package',
    shortDescription: 'An extended couples massage experience designed for weekend retreats with full relaxation amenities.',
    recommendedDuration: '120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Couples spending quality weekend time together',
    suggestedFrequency: 'As desired',
    techniqueStyle: 'Luxury retreat therapy',
    postTreatmentNotes: 'Muscle relaxation, mental calm',
    recommendedAddOns: 'Aromatherapy, hot stones, flower petals',
    whatToExpect: 'An extended couples massage experience designed for weekend retreats with full relaxation amenities.',
    imageThumbnail: '',
  },
  {
    name: 'VIP Private Couples Spa Suite',
    shortDescription: 'Exclusive couples massage in a VIP suite with privacy, premium oils, and full spa amenities.',
    recommendedDuration: '120 minutes',
    pressureLevel: 'Customizable ★★☆ to ★★★★',
    focusAreas: 'Full body',
    idealFor: 'High-end clients seeking ultimate intimacy and luxury',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Personalized luxury therapy',
    postTreatmentNotes: 'Deep relaxation, emotional connection',
    recommendedAddOns: 'Hot stones, aromatherapy, scalp massage',
    whatToExpect: 'Exclusive couples massage in a VIP suite with privacy, premium oils, and full spa amenities.',
    imageThumbnail: '',
  },
];
