/**
 * Wellness & Relaxation (Spa-Based) directory entries.
 * Place directory only — NOT available for Home Service providers.
 * Full content is shown in the (i) description popup on the live site when the place has the type on their menu.
 */

export interface WellnessMassageDirectoryEntry {
  name: string;
  shortDescription: string;
  recommendedDuration: string;
  pressureLevel: string;
  focusAreas: string;
  idealFor: string;
  suggestedFrequency: string;
  techniqueStyle: string;
  postTreatmentNotes: string;
  recommendedAddOns: string;
  whatToExpect: string;
  imageThumbnail: string;
}

export function getWellnessMassagePopupContent(serviceName: string): string | null {
  const entry = WELLNESS_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (serviceName || '').toLowerCase().trim()
  );
  if (!entry) return null;
  const parts: string[] = [
    'What to Expect:',
    entry.whatToExpect,
    '',
    `Recommended Duration: ${entry.recommendedDuration}`,
    `Pressure Level: ${entry.pressureLevel}`,
    `Focus Areas: ${entry.focusAreas}`,
    `Ideal For: ${entry.idealFor}`,
    `Suggested Frequency: ${entry.suggestedFrequency}`,
    `Technique Style: ${entry.techniqueStyle}`,
    `Post-Treatment Notes: ${entry.postTreatmentNotes}`,
    `Recommended Add-Ons: ${entry.recommendedAddOns}`,
  ];
  return parts.join('\n');
}

export function getWellnessMassageEntry(name: string): WellnessMassageDirectoryEntry | undefined {
  return WELLNESS_MASSAGE_DIRECTORY_ENTRIES.find(
    (e) => e.name.toLowerCase().trim() === (name || '').toLowerCase().trim()
  );
}

export const WELLNESS_MASSAGE_DIRECTORY_NAMES = [
  'Signature Relaxation Massage',
  'Aroma Oil Serenity Massage',
  'Deep Calm Swedish Therapy',
  'Luxury Hot Stone Ritual',
  'Himalayan Salt Stone Massage',
  'Candle Oil Drip Massage',
  'Stress Relief Body Flow',
  'Total Body Relaxation Therapy',
  'Warm Herbal Compress Therapy',
  'Balinese Harmony Massage',
  'Lomi Lomi Flow Massage',
  'Four Hands Synchronised Massage',
  'Gentle Touch Relax Therapy',
  'Anti-Stress Back & Shoulder Relief',
  'Sleep Inducing Massage Ritual',
  'Full Body Detox Massage',
  'Relax & Renew Body Treatment',
  'Calm Mind Therapy Massage',
  'Head to Toe Serenity Massage',
  'Spa Classic Oil Massage',
  'Premium Wellness Bodywork',
  'Warm Bamboo Relax Massage',
  'Tension Melt Body Therapy',
  'Holistic Spa Relax Treatment',
  'Soft Pressure Comfort Massage',
  'Rejuvenation Body Ritual',
  'Spa Signature Glow Massage',
  'Mindful Body Relax Therapy',
  'Luxury Spa Experience Massage',
  'Tranquility Touch Massage',
  'Royal Relaxation Treatment',
  'Gentle Wave Body Massage',
  'Deep Relax Harmony Therapy',
  'Serenity Flow Oil Massage',
  'Golden Glow Spa Massage',
  'Blissful Escape Body Massage',
  'Premium Aroma Relax Therapy',
  'Pure Calm Massage Experience',
  'Ocean Breeze Relax Massage',
  'Soothing Stone & Oil Therapy',
  'Dream State Relax Massage',
  'Wellness Reset Body Massage',
  'Urban Calm Spa Therapy',
  'Body & Mind Balance Massage',
  'Ultimate Relax Package Massage',
  'Deluxe Spa Oil Therapy',
  'Warm Oil Luxury Massage',
  'Comfort Touch Relax Treatment',
  'Signature Spa Renewal Massage',
  'Elite Wellness Relax Massage',
] as const;

export const WELLNESS_MASSAGE_DIRECTORY_ENTRIES: WellnessMassageDirectoryEntry[] = [
  {
    name: 'Signature Relaxation Massage',
    shortDescription: 'A flowing full-body massage designed to calm the nervous system and release everyday tension.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'General relaxation and stress reduction',
    suggestedFrequency: 'Weekly or bi-weekly',
    techniqueStyle: 'Swedish-based flowing strokes',
    postTreatmentNotes: 'Deep calm, lighter body sensation, improved mood',
    recommendedAddOns: 'Aromatherapy upgrade',
    whatToExpect:
      'A flowing full-body massage designed to calm the nervous system and release everyday tension.',
    imageThumbnail: '',
  },
  {
    name: 'Aroma Oil Serenity Massage',
    shortDescription: 'A relaxation massage enhanced with therapeutic essential oils for emotional and physical balance.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stress, anxiety, mental fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Aromatherapy relaxation massage',
    postTreatmentNotes: 'Calm mind, improved breathing, subtle detox effect',
    recommendedAddOns: 'Scalp massage',
    whatToExpect:
      'A relaxation massage enhanced with therapeutic essential oils for emotional and physical balance.',
    imageThumbnail: '',
  },
  {
    name: 'Deep Calm Swedish Therapy',
    shortDescription: 'A traditional Swedish-style massage focusing on long strokes and gentle kneading to release muscle tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Muscle stiffness from daily activity',
    suggestedFrequency: 'Every 2 weeks',
    techniqueStyle: 'Swedish therapeutic method',
    postTreatmentNotes: 'Improved circulation and flexibility',
    recommendedAddOns: 'Hot towel treatment',
    whatToExpect:
      'A traditional Swedish-style massage focusing on long strokes and gentle kneading to release muscle tension.',
    imageThumbnail: '',
  },
  {
    name: 'Luxury Hot Stone Ritual',
    shortDescription: 'Warm basalt stones are used to relax muscles deeply and improve circulation.',
    recommendedDuration: '75–90 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Chronic tension and stress',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Heated stone therapy',
    postTreatmentNotes: 'Deep warmth and muscle relaxation',
    recommendedAddOns: 'Aromatherapy oils',
    whatToExpect:
      'Warm basalt stones are used to relax muscles deeply and improve circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Himalayan Salt Stone Massage',
    shortDescription: 'Heated salt stones glide over the body to soothe muscles and promote mineral absorption.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back and legs',
    idealFor: 'Fatigue and mild muscle tension',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Warm salt stone therapy',
    postTreatmentNotes: 'Relaxed muscles and smoother skin feel',
    recommendedAddOns: 'Body scrub',
    whatToExpect:
      'Heated salt stones glide over the body to soothe muscles and promote mineral absorption.',
    imageThumbnail: '',
  },
  {
    name: 'Candle Oil Drip Massage',
    shortDescription: 'Warm melted massage candle oil is poured onto the body for a luxurious sensory experience.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Dry skin and deep relaxation',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Warm oil relaxation therapy',
    postTreatmentNotes: 'Hydrated skin and calm nervous system',
    recommendedAddOns: 'Foot reflexology',
    whatToExpect:
      'Warm melted massage candle oil is poured onto the body for a luxurious sensory experience.',
    imageThumbnail: '',
  },
  {
    name: 'Stress Relief Body Flow',
    shortDescription: 'Rhythmic movements designed to release accumulated stress and calm the body.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Neck, shoulders, back',
    idealFor: 'Office workers and mental stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Flow-based relaxation therapy',
    postTreatmentNotes: 'Reduced shoulder tightness',
    recommendedAddOns: 'Neck & scalp therapy',
    whatToExpect:
      'Rhythmic movements designed to release accumulated stress and calm the body.',
    imageThumbnail: '',
  },
  {
    name: 'Total Body Relaxation Therapy',
    shortDescription: 'A comprehensive head-to-toe massage focused on soothing muscles and improving circulation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Full system reset',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Integrated spa relaxation',
    postTreatmentNotes: 'Balanced energy and improved sleep',
    recommendedAddOns: 'Facial massage',
    whatToExpect:
      'A comprehensive head-to-toe massage focused on soothing muscles and improving circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Warm Herbal Compress Therapy',
    shortDescription: 'Heated herbal pouches are pressed along the body to relieve muscle tension and promote detox.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back and legs',
    idealFor: 'Muscle stiffness and fatigue',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Herbal compress therapy',
    postTreatmentNotes: 'Muscle softness and improved circulation',
    recommendedAddOns: 'Oil massage finish',
    whatToExpect:
      'Heated herbal pouches are pressed along the body to relieve muscle tension and promote detox.',
    imageThumbnail: '',
  },
  {
    name: 'Balinese Harmony Massage',
    shortDescription: 'A traditional Indonesian-inspired massage combining acupressure, stretching, and flowing strokes.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Deep relaxation with therapeutic pressure',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Balinese traditional therapy',
    postTreatmentNotes: 'Loosened muscles and enhanced flexibility',
    recommendedAddOns: 'Hot stone upgrade',
    whatToExpect:
      'A traditional Indonesian-inspired massage combining acupressure, stretching, and flowing strokes.',
    imageThumbnail: '',
  },
  {
    name: 'Lomi Lomi Flow Massage',
    shortDescription: 'A rhythmic flowing massage using forearm movements to create continuous body relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Deep relaxation and emotional balance',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Hawaiian-inspired flowing therapy',
    postTreatmentNotes: 'Lightness and emotional release',
    recommendedAddOns: 'Aromatherapy oils',
    whatToExpect:
      'A rhythmic flowing massage using forearm movements to create continuous body relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Four Hands Synchronised Massage',
    shortDescription: 'Two therapists work in coordinated movements for a deeply immersive relaxation experience.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Luxury spa experience seekers',
    suggestedFrequency: 'Special occasions',
    techniqueStyle: 'Dual synchronized relaxation therapy',
    postTreatmentNotes: 'Intensified relaxation effect',
    recommendedAddOns: 'Hot stone finish',
    whatToExpect:
      'Two therapists work in coordinated movements for a deeply immersive relaxation experience.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Touch Relax Therapy',
    shortDescription: 'A soft-pressure calming massage designed for sensitive clients.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, arms, legs',
    idealFor: 'First-time spa guests',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Gentle relaxation massage',
    postTreatmentNotes: 'Calm nervous system',
    recommendedAddOns: 'Scalp massage',
    whatToExpect:
      'A soft-pressure calming massage designed for sensitive clients.',
    imageThumbnail: '',
  },
  {
    name: 'Anti-Stress Back & Shoulder Relief',
    shortDescription: 'Focused therapy targeting upper body tension from desk work and stress.',
    recommendedDuration: '45–60 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Neck, shoulders, upper back',
    idealFor: 'Office professionals',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted tension relief',
    postTreatmentNotes: 'Reduced stiffness and improved posture',
    recommendedAddOns: 'Cupping therapy',
    whatToExpect:
      'Focused therapy targeting upper body tension from desk work and stress.',
    imageThumbnail: '',
  },
  {
    name: 'Sleep Inducing Massage Ritual',
    shortDescription: 'A slow rhythmic massage aimed at activating deep relaxation and better sleep patterns.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Insomnia and stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Nervous system calming therapy',
    postTreatmentNotes: 'Improved sleep quality',
    recommendedAddOns: 'Lavender oil upgrade',
    whatToExpect:
      'A slow rhythmic massage aimed at activating deep relaxation and better sleep patterns.',
    imageThumbnail: '',
  },
  {
    name: 'Full Body Detox Massage',
    shortDescription: 'Stimulating strokes designed to encourage lymphatic flow and detox support.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Water retention and fatigue',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Detoxifying bodywork',
    postTreatmentNotes: 'Increased circulation',
    recommendedAddOns: 'Dry brushing',
    whatToExpect:
      'Stimulating strokes designed to encourage lymphatic flow and detox support.',
    imageThumbnail: '',
  },
  {
    name: 'Relax & Renew Body Treatment',
    shortDescription: 'A balanced relaxation massage promoting muscle renewal and stress relief.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'General wellness maintenance',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Integrated relaxation therapy',
    postTreatmentNotes: 'Refreshed body sensation',
    recommendedAddOns: 'Foot therapy',
    whatToExpect:
      'A balanced relaxation massage promoting muscle renewal and stress relief.',
    imageThumbnail: '',
  },
  {
    name: 'Calm Mind Therapy Massage',
    shortDescription: 'A slow technique focusing on breath and rhythmic strokes to calm mental tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Head, neck, shoulders',
    idealFor: 'Anxiety and burnout',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Mind-body relaxation therapy',
    postTreatmentNotes: 'Clearer mental state',
    recommendedAddOns: 'Scalp therapy',
    whatToExpect:
      'A slow technique focusing on breath and rhythmic strokes to calm mental tension.',
    imageThumbnail: '',
  },
  {
    name: 'Head to Toe Serenity Massage',
    shortDescription: 'Complete body treatment from scalp to feet for total relaxation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Full reset relaxation',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Comprehensive spa therapy',
    postTreatmentNotes: 'Balanced body and mind',
    recommendedAddOns: 'Facial massage',
    whatToExpect:
      'Complete body treatment from scalp to feet for total relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Spa Classic Oil Massage',
    shortDescription: 'Traditional spa oil massage with smooth gliding strokes.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back, legs',
    idealFor: 'General muscle relaxation',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Classic oil-based therapy',
    postTreatmentNotes: 'Relaxed muscles',
    recommendedAddOns: 'Hot towel compress',
    whatToExpect:
      'Traditional spa oil massage with smooth gliding strokes.',
    imageThumbnail: '',
  },
  {
    name: 'Premium Wellness Bodywork',
    shortDescription: 'Customized spa therapy combining multiple relaxation techniques.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Premium spa clients',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Hybrid relaxation therapy',
    postTreatmentNotes: 'Deep overall relaxation',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Customized spa therapy combining multiple relaxation techniques.',
    imageThumbnail: '',
  },
  {
    name: 'Warm Bamboo Relax Massage',
    shortDescription: 'Heated bamboo sticks are rolled across muscles to ease tension.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Back and legs',
    idealFor: 'Muscle tightness',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Bamboo rolling therapy',
    postTreatmentNotes: 'Improved muscle flexibility',
    recommendedAddOns: 'Oil therapy',
    whatToExpect:
      'Heated bamboo sticks are rolled across muscles to ease tension.',
    imageThumbnail: '',
  },
  {
    name: 'Tension Melt Body Therapy',
    shortDescription: 'Deep relaxation strokes targeting stubborn muscle tension.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Firm ★★★★',
    focusAreas: 'Back and shoulders',
    idealFor: 'Chronic tension',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Deep relaxation therapy',
    postTreatmentNotes: 'Reduced muscle tightness',
    recommendedAddOns: 'Cupping',
    whatToExpect:
      'Deep relaxation strokes targeting stubborn muscle tension.',
    imageThumbnail: '',
  },
  {
    name: 'Holistic Spa Relax Treatment',
    shortDescription: 'A full-body treatment integrating breath work and relaxation massage.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Mind-body balance',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Holistic relaxation therapy',
    postTreatmentNotes: 'Balanced energy',
    recommendedAddOns: 'Meditation guidance',
    whatToExpect:
      'A full-body treatment integrating breath work and relaxation massage.',
    imageThumbnail: '',
  },
  {
    name: 'Soft Pressure Comfort Massage',
    shortDescription: 'Gentle flowing strokes ideal for stress reduction.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back and arms',
    idealFor: 'Sensitive clients',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Light comfort massage',
    postTreatmentNotes: 'Calm and comforted',
    recommendedAddOns: 'Scalp massage',
    whatToExpect:
      'Gentle flowing strokes ideal for stress reduction.',
    imageThumbnail: '',
  },
  {
    name: 'Rejuvenation Body Ritual',
    shortDescription: 'Restorative spa massage promoting renewal.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Fatigue recovery',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Spa ritual therapy',
    postTreatmentNotes: 'Refreshed and energised',
    recommendedAddOns: 'Body scrub',
    whatToExpect:
      'Restorative spa massage promoting renewal.',
    imageThumbnail: '',
  },
  {
    name: 'Spa Signature Glow Massage',
    shortDescription: 'Relaxation massage promoting circulation and skin glow.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Pre-event relaxation',
    suggestedFrequency: 'As needed',
    techniqueStyle: 'Circulatory enhancement massage',
    postTreatmentNotes: 'Improved skin appearance',
    recommendedAddOns: 'Facial treatment',
    whatToExpect:
      'Relaxation massage promoting circulation and skin glow.',
    imageThumbnail: '',
  },
  {
    name: 'Mindful Body Relax Therapy',
    shortDescription: 'Slow, intentional movements with guided breathing.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stress management',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Mindfulness-based massage',
    postTreatmentNotes: 'Reduced mental tension',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Slow, intentional movements with guided breathing.',
    imageThumbnail: '',
  },
  {
    name: 'Luxury Spa Experience Massage',
    shortDescription: 'High-end customized relaxation treatment.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Premium spa clients',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Luxury spa integration',
    postTreatmentNotes: 'Deep relaxation',
    recommendedAddOns: 'Hot stones',
    whatToExpect:
      'High-end customized relaxation treatment.',
    imageThumbnail: '',
  },
  {
    name: 'Tranquility Touch Massage',
    shortDescription: 'Gentle, flowing strokes designed to quiet the mind and release physical stress.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back, shoulders, arms',
    idealFor: 'Anxiety relief and emotional relaxation',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Soothing relaxation therapy',
    postTreatmentNotes: 'Emotional calm and light muscle relief',
    recommendedAddOns: 'Scalp therapy',
    whatToExpect:
      'Gentle, flowing strokes designed to quiet the mind and release physical stress.',
    imageThumbnail: '',
  },
  {
    name: 'Royal Relaxation Treatment',
    shortDescription: 'A luxurious full-body massage combining warm oils and rhythmic techniques.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Premium spa clients',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Luxury spa relaxation therapy',
    postTreatmentNotes: 'Deep relaxation and improved circulation',
    recommendedAddOns: 'Hot stone enhancement',
    whatToExpect:
      'A luxurious full-body massage combining warm oils and rhythmic techniques.',
    imageThumbnail: '',
  },
  {
    name: 'Gentle Wave Body Massage',
    shortDescription: 'Soft wave-like movements that create a continuous calming sensation.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Stress reduction and nervous system calming',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Rhythmic flow massage',
    postTreatmentNotes: 'Reduced muscle tension and mental clarity',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'Soft wave-like movements that create a continuous calming sensation.',
    imageThumbnail: '',
  },
  {
    name: 'Deep Relax Harmony Therapy',
    shortDescription: 'A balanced massage using moderate pressure to release deeper muscle tension.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium to Firm ★★★★',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Moderate muscle stiffness',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Deep relaxation bodywork',
    postTreatmentNotes: 'Loosened muscles and improved flexibility',
    recommendedAddOns: 'Warm towel therapy',
    whatToExpect:
      'A balanced massage using moderate pressure to release deeper muscle tension.',
    imageThumbnail: '',
  },
  {
    name: 'Serenity Flow Oil Massage',
    shortDescription: 'A smooth oil-based massage focusing on long gliding strokes.',
    recommendedDuration: '60–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'General wellness maintenance',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Oil flow relaxation massage',
    postTreatmentNotes: 'Balanced body sensation and stress relief',
    recommendedAddOns: 'Foot reflexology',
    whatToExpect:
      'A smooth oil-based massage focusing on long gliding strokes.',
    imageThumbnail: '',
  },
  {
    name: 'Golden Glow Spa Massage',
    shortDescription: 'Relaxation massage aimed at improving circulation and skin vitality.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Pre-event preparation or skin glow',
    suggestedFrequency: 'As needed',
    techniqueStyle: 'Circulatory enhancement massage',
    postTreatmentNotes: 'Brighter skin tone and relaxed muscles',
    recommendedAddOns: 'Body polish',
    whatToExpect:
      'Relaxation massage aimed at improving circulation and skin vitality.',
    imageThumbnail: '',
  },
  {
    name: 'Blissful Escape Body Massage',
    shortDescription: 'An immersive spa experience combining calming strokes and soothing oils.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Complete mental and physical escape',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Full-body relaxation therapy',
    postTreatmentNotes: 'Deep calm and improved sleep',
    recommendedAddOns: 'Aromatherapy upgrade',
    whatToExpect:
      'An immersive spa experience combining calming strokes and soothing oils.',
    imageThumbnail: '',
  },
  {
    name: 'Premium Aroma Relax Therapy',
    shortDescription: 'Therapeutic essential oils blended with smooth massage techniques.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Back, shoulders, neck',
    idealFor: 'Stress and mental fatigue',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Aromatherapy-based relaxation',
    postTreatmentNotes: 'Improved mood and relaxation',
    recommendedAddOns: 'Scalp massage',
    whatToExpect:
      'Therapeutic essential oils blended with smooth massage techniques.',
    imageThumbnail: '',
  },
  {
    name: 'Pure Calm Massage Experience',
    shortDescription: 'A minimal-pressure massage focused on calming the nervous system.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Full body',
    idealFor: 'First-time spa clients or high stress levels',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Gentle relaxation therapy',
    postTreatmentNotes: 'Calm breathing and reduced anxiety',
    recommendedAddOns: 'Lavender oil',
    whatToExpect:
      'A minimal-pressure massage focused on calming the nervous system.',
    imageThumbnail: '',
  },
  {
    name: 'Ocean Breeze Relax Massage',
    shortDescription: 'A refreshing spa massage inspired by coastal relaxation techniques.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back and legs',
    idealFor: 'Muscle fatigue and stress',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Flow-based spa massage',
    postTreatmentNotes: 'Re-energized muscles and calm mind',
    recommendedAddOns: 'Cooling gel treatment',
    whatToExpect:
      'A refreshing spa massage inspired by coastal relaxation techniques.',
    imageThumbnail: '',
  },
  {
    name: 'Soothing Stone & Oil Therapy',
    shortDescription: 'Combination of warm stones and massage oil to ease muscle tension.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Back, shoulders, legs',
    idealFor: 'Deep relaxation and muscle stiffness',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Stone-assisted relaxation therapy',
    postTreatmentNotes: 'Deep warmth and improved circulation',
    recommendedAddOns: 'Aromatherapy blend',
    whatToExpect:
      'Combination of warm stones and massage oil to ease muscle tension.',
    imageThumbnail: '',
  },
  {
    name: 'Dream State Relax Massage',
    shortDescription: 'A slow, rhythmic massage designed to bring the body into a deeply relaxed, almost meditative state.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Light to Medium ★★☆',
    focusAreas: 'Full body',
    idealFor: 'Sleep improvement and stress recovery',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Nervous system calming therapy',
    postTreatmentNotes: 'Deep relaxation and improved sleep quality',
    recommendedAddOns: 'Lavender aromatherapy',
    whatToExpect:
      'A slow, rhythmic massage designed to bring the body into a deeply relaxed, almost meditative state.',
    imageThumbnail: '',
  },
  {
    name: 'Wellness Reset Body Massage',
    shortDescription: 'A restorative full-body massage aimed at resetting muscle tension and improving circulation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Physical and mental burnout',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Integrated wellness bodywork',
    postTreatmentNotes: 'Renewed energy and muscle balance',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A restorative full-body massage aimed at resetting muscle tension and improving circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Urban Calm Spa Therapy',
    shortDescription: 'A relaxation massage tailored for busy professionals experiencing urban stress.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Neck, shoulders, upper back',
    idealFor: 'Office workers and city lifestyle stress',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Targeted relaxation therapy',
    postTreatmentNotes: 'Reduced shoulder tightness and mental clarity',
    recommendedAddOns: 'Scalp massage',
    whatToExpect:
      'A relaxation massage tailored for busy professionals experiencing urban stress.',
    imageThumbnail: '',
  },
  {
    name: 'Body & Mind Balance Massage',
    shortDescription: 'A holistic treatment combining calming strokes and breath-focused relaxation.',
    recommendedDuration: '75–90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Emotional balance and tension relief',
    suggestedFrequency: 'Bi-weekly',
    techniqueStyle: 'Mind-body integration massage',
    postTreatmentNotes: 'Balanced mood and muscle relaxation',
    recommendedAddOns: 'Guided breathing session',
    whatToExpect:
      'A holistic treatment combining calming strokes and breath-focused relaxation.',
    imageThumbnail: '',
  },
  {
    name: 'Ultimate Relax Package Massage',
    shortDescription: 'An extended spa experience combining multiple relaxation techniques in one session.',
    recommendedDuration: '120 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Complete relaxation and indulgence',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Multi-technique spa integration',
    postTreatmentNotes: 'Deep full-body calm and muscle release',
    recommendedAddOns: 'Hot stone and aromatherapy',
    whatToExpect:
      'An extended spa experience combining multiple relaxation techniques in one session.',
    imageThumbnail: '',
  },
  {
    name: 'Deluxe Spa Oil Therapy',
    shortDescription: 'A premium oil-based massage using enriched oils for smoother glide and deeper comfort.',
    recommendedDuration: '75 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Skin hydration and muscle relaxation',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Oil-intensive relaxation massage',
    postTreatmentNotes: 'Hydrated skin and loosened muscles',
    recommendedAddOns: 'Body polish',
    whatToExpect:
      'A premium oil-based massage using enriched oils for smoother glide and deeper comfort.',
    imageThumbnail: '',
  },
  {
    name: 'Warm Oil Luxury Massage',
    shortDescription: 'Heated oils applied in slow strokes to deeply relax muscles and soothe the nervous system.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Stress relief and dry skin',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Warm oil relaxation therapy',
    postTreatmentNotes: 'Deep muscle comfort and skin nourishment',
    recommendedAddOns: 'Scalp therapy',
    whatToExpect:
      'Heated oils applied in slow strokes to deeply relax muscles and soothe the nervous system.',
    imageThumbnail: '',
  },
  {
    name: 'Comfort Touch Relax Treatment',
    shortDescription: 'A gentle massage designed to provide comfort and emotional reassurance.',
    recommendedDuration: '60 minutes',
    pressureLevel: 'Light ★★☆',
    focusAreas: 'Back and shoulders',
    idealFor: 'High stress or first-time spa clients',
    suggestedFrequency: 'Weekly',
    techniqueStyle: 'Soft therapeutic touch',
    postTreatmentNotes: 'Calm mood and light muscle relief',
    recommendedAddOns: 'Aromatherapy',
    whatToExpect:
      'A gentle massage designed to provide comfort and emotional reassurance.',
    imageThumbnail: '',
  },
  {
    name: 'Signature Spa Renewal Massage',
    shortDescription: 'A rejuvenating full-body treatment focused on restoring muscle vitality and circulation.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Medium ★★★',
    focusAreas: 'Full body',
    idealFor: 'Wellness maintenance',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Circulatory enhancement therapy',
    postTreatmentNotes: 'Improved flexibility and refreshed body feeling',
    recommendedAddOns: 'Stretch therapy',
    whatToExpect:
      'A rejuvenating full-body treatment focused on restoring muscle vitality and circulation.',
    imageThumbnail: '',
  },
  {
    name: 'Elite Wellness Relax Massage',
    shortDescription: 'A premium-level relaxation massage tailored to individual comfort preferences.',
    recommendedDuration: '90 minutes',
    pressureLevel: 'Customizable ★★☆ to ★★★★',
    focusAreas: 'Full body',
    idealFor: 'Clients seeking personalized luxury treatment',
    suggestedFrequency: 'Monthly',
    techniqueStyle: 'Customized spa bodywork',
    postTreatmentNotes: 'Deep relaxation and muscular balance',
    recommendedAddOns: 'Hot stones, aromatherapy, or scalp therapy',
    whatToExpect:
      'A premium-level relaxation massage tailored to individual comfort preferences.',
    imageThumbnail: '',
  },
];
