/**
 * Page Type Definitions
 * All possible pages/routes in the application
 */

export type Page = 
    | 'loading' // Loading state
    | 'landing' 
    | 'auth' 
    | 'signIn'
    | 'signin' // Sign in page
    | 'signup' // Sign up page
    | 'login' // Login page
    | 'createAccount' // Create account page
    | 'onboarding-package' // Package onboarding
    | 'create-account'  // New unified account creation page
    | 'create-account-employer' // Create account with Post Job (employer) pre-selected
    | 'home' 
    | 'joinIndastreet'
    | 'role-selection'
    | 'detail' 
    | 'massagePlaceProfile' 
    | 'facialProviders'
    | 'facial-providers'
    | 'facialPlaceProfile'
    | 'facialPlaceDashboard'
    | 'facialPortal'
    | 'facialMemberDashboard'
    | 'facialTypes'
    | 'registrationChoice' 
    | 'providerAuth' 
    | 'therapistStatus' 
    | 'appwrite-diagnostic' // Appwrite diagnostic page
    | 'diagnostic' // General diagnostic page 
    | 'therapistAvailability' // Therapist availability page
    | 'therapistPortal'
    | 'therapist' // Therapist portal/dashboard
    | 'therapist-profile' // Customer-facing therapist profile page (different from dashboard)
    | 'therapist-status'
    | 'therapist-schedule'
    | 'therapist-bookings'
    | 'therapist-earnings'
    | 'therapist-payment'
    | 'therapist-payment-status'
    | 'therapist-commission-payment'
    | 'therapist-premium-upgrade'
    | 'therapist-menu'
    | 'therapist-chat'
    | 'therapist-notifications'
    | 'therapist-calendar'
    | 'therapist-legal'
    | 'therapist-job-applications'
    | 'facial-place-profile' // Facial place profile page
    | 'profile' // 🎯 NEW: Guest profile page for non-registered users
    | 'qr-code' // QR Code sharing page
    | 'membership-select'
    | 'lead-accept'
    | 'lead-decline'
    | 'membership-terms'
    | 'mobile-terms-and-conditions'
    | 'placeDashboard' 
    | 'therapist-dashboard'
    | 'place-dashboard' 
    | 'serviceTerms' 
    | 'placeTerms' 
    | 'placeDiscountBadge' 
    | 'privacy' 
    | 'terms'
    | 'cookies-policy' 
    | 'membership' 
    | 'packageTerms'
    | 'simpleSignup'
    | 'membershipPayment'
    | 'booking' 
    | 'bookings' 
    | 'notifications' 
    | 'massageTypes' 
    | 'unifiedLogin' 
    | 'therapistLogin' 
    | 'massagePlaceLogin' 
    | 'employerJobPosting' 
    | 'jobPostingPayment' 
    | 'browseJobs' 
    | 'massageJobs' 
    | 'therapistJobs' 
    | 'therapistJobRegistration' 
    | 'jobUnlockPayment' 
    | 'chatList' 
    | 'chat' // Individual chat window
    | 'chat-room' // Specific chat room
    | 'booking-flow' // Booking flow page
    | 'booking-therapist' // Book specific therapist
    | 'booking-place' // Book specific place
    | 'about' 
    | 'about-us'
    | 'how-it-works' 
    | 'massage-bali' 
    | 'blog'
    | 'indastreet-news' 
    | 'blog/bali-spa-industry-trends-2025' 
    | 'blog/top-10-massage-techniques' 
    | 'blog/massage-career-indonesia' 
    | 'blog/benefits-regular-massage-therapy' 
    | 'blog/hiring-massage-therapists-guide' 
    | 'blog/traditional-balinese-massage' 
    | 'blog/spa-tourism-indonesia' 
    | 'blog/aromatherapy-massage-oils' 
    | 'blog/pricing-guide-massage-therapists' 
    | 'blog/deep-tissue-vs-swedish-massage' 
    | 'blog/online-presence-massage-therapist' 
    | 'blog/wellness-tourism-ubud'
    | 'blog-spa-tourism-indonesia'
    | 'blog-aromatherapy-massage-oils'
    | 'blog-pricing-guide-therapists'
    | 'blog-deep-tissue-vs-swedish'
    | 'blog-online-presence-therapist'
    | 'blog-wellness-tourism-ubud'
    | 'blog-wellness-southeast-asia'
    | 'blog-massage-spa-standards-asia-europe'
    | 'blog-skin-clinic-trends-international'
    | 'blog-building-wellness-business-international'
    | 'blog-hiring-massage-therapists'
    | 'blog-traditional-balinese-massage'
    | 'blog-bali-spa-trends-2025'
    | 'blog-top-10-massage-techniques'
    | 'blog-massage-career-indonesia'
    | 'blog-benefits-regular-massage'
    | 'guestAlerts'
    | 'rewardBannersTest'
    | 'todaysDiscounts' 
    | 'faq' 
    | 'indastreet-partners'
    | 'partnership-application'
    | 'balinese-massage' 
    | 'deep-tissue-massage' 
    | 'swedish-massage'
    | 'hot-stone-massage'
    | 'aromatherapy-massage'
    | 'thai-massage'
    | 'reflexology-massage'
    | 'shiatsu-massage'
    | 'sports-massage'
    | 'pregnancy-massage'
    | 'reviews-testimonials'
    | 'contact'
    | 'partner-contact'
    | 'quick-support' 
    | 'partnership-inquiries' 
    | 'press-media' 
    | 'career-opportunities' 
    | 'therapist-info' 
    | 'hotel-info' 
    | 'employer-info' 
    | 'payment-info'
    | 'coin-history' 
    | 'coinHistory' // Added camelCase variant used in navigation handlers
    | 'hotelVillaMenu' // Added live hotel/villa menu page id
    | 'coinSystemTest'
    | 'coin-test' 
    | 'website-management'
    | 'partner-settings-hotel'
    | 'partner-settings-villa'
    | 'join-indastreet-partners'
    | 'todays-discounts'
    | 'hotel-login'
    | 'placeLogin'
    | 'customerAuth'
    | 'adminLogin'
    | 'villaDashboard'
    | 'hotelDashboard'
    | 'customerDashboard'
    | 'adminDashboard'
    | 'agentPortal'
    | 'customerPortal'
    | 'massagePlacePortal'
    | 'termsOfService'
    | 'privacyPolicy'
    | 'agentDashboard'
    | 'therapistDashboard'
    | 'agentTerms'
    | 'accept-booking'
    | 'decline-booking'
    | 'verifiedProBadge'
    | 'sharedProfileStandards'
    | 'mobileTherapistStandards'
    | 'customerProviders'
    | 'customerReviews'
    | 'customerSupport'
    // Additional routes from optimized router
    | 'company'
    | 'massage-types'
    | 'facial-types'
    | 'providers'
    | 'discounts'
    | 'real-chat-test' // 🔗 Real Chat Integration Test
    | 'therapist-login'
    | 'place-login'
    | 'employer-login'
    | 'service-personnel-login'
    | 'therapist-login-for-jobs'
    | 'place-login-for-jobs'
    | 'therapist-signup-for-jobs'
    | 'place-signup-for-jobs'
    | 'therapist-listing-payment'
    | 'facial-portal'
    | 'simple-signup'
    | 'shared-therapist-profile'  // Legacy shared profile URL
    
    // Floating Button Routes
    | 'chat-support'
    | 'booking-quick'
    | 'emergency-contact'
    | 'help'
    | 'feedback'
    | 'share-therapist'            // New simple share URL for therapists
    | 'share-place'                // New simple share URL for places
    | 'share-facial'               // New simple share URL for facial places
    | 'massage-place-profile'
    | 'place-detail'
    | 'privacy-policy'
    | 'service-terms'
    | 'place-terms'
    | 'package-terms'
    | 'press'
    | 'blog-pricing-guide-massage'
    | 'confirm-therapists'
    | 'employer-job-posting'
    | 'guest-profile'
    | 'job-posting-payment'
    | 'apply-for-job'
    | 'browse-jobs'
    | 'massage-jobs'
    | 'therapist-job-registration'
    | 'reviews'
    | 'job-unlock-payment'
    | 'customer-reviews'
    | 'customer-support'
    | 'place-discount-badge'
    | 'verified-pro-badge'
    | 'shared-profile-standards'
    | 'mobile-therapist-standards'
    | 'guest-alerts'
    | 'partner-settings'
    | 'admin-login'
    | 'women-reviews'
    | 'advanced-search'
    | 'help-faq'
    | 'top-therapists'
    | 'special-offers'
    | 'video-center'
    | 'hotels-and-villas'
    | 'hotel-villa-safe-pass'
    | 'safePass'
    | 'send-discount'
    | 'villa-portal'
    | 'sign-in'
    | 'therapist-signup'
    | 'massage-place-signup'
    | 'place-signup'
    | 'facial-place-signup'
    | 'therapist-terms-and-conditions'
    | 'therapist-terms'
    | 'dashboard'
    | 'status'
    | 'earnings'
    | 'legal'
    | 'calendar'
    | 'payment'
    | 'payment-status'
    | 'custom-menu'
    | 'commission-payment'
    | 'therapist-commission'
    | 'schedule'
    | 'therapist-package-terms'
    | 'admin-live-listings'
    | 'massage-place-dashboard'
    | 'facial-place-dashboard'
    // Therapist Routes
    | 'therapist-how-it-works'
    | 'customers'
    | 'therapist-customers'
    | 'more-customers'
    | 'analytics'
    | 'therapist-analytics'
    | 'banner-discount'
    | 'therapist-banner-discount'
    | 'therapist-hotel-villa-safe-pass'
    | 'therapist-safepass-apply'
    | 'place-safepass-apply'
    | 'admin-safepass'
    // Admin Dashboard Routes (MERGED from apps/admin-dashboard)
    | 'admin'
    | 'admin-dashboard'
    | 'admin-therapists'
    | 'admin-bookings'
    | 'admin-chat'
    | 'admin-revenue'
    | 'admin-commissions'
    | 'admin-ktp'
    | 'admin-achievements'
    | 'admin-system-health'
    | 'admin-settings';

export type Language = 'en' | 'id' | 'gb' | 'th' | 'vi' | 'ms' | 'tl' | 'zh' | 'ja' | 'ko' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'ar' | 'hi' | 'nl' | 'tr' | 'pl' | 'sv' | 'da';

export type LoggedInProvider = { 
    id: number | string; 
    type: 'therapist' | 'place' 
};

export type LoggedInUser = { 
    id: string; 
    type: 'admin' | 'hotel' | 'villa' | 'agent' | 'therapist' | 'place' | 'facial-place' | 'user';
    email?: string;
    name?: string;
    data?: any;
};
