import { databases, ID } from '../lib/appwrite.ts';
import { APPWRITE_CONFIG } from '../lib/appwrite.config.ts';

const DATABASE_ID = APPWRITE_CONFIG.databaseId;
const COLLECTION_ID = APPWRITE_CONFIG.collections.employerJobPostings;

const jobPostings = [
    {
        jobTitle: 'Head Massage Therapist',
        jobDescription: 'Lead our team of 10 therapists at Bali\'s premier luxury resort. Requires 5+ years experience in traditional Balinese and deep tissue massage.',
        employmentType: 'full-time',
        location: 'Jimbaran, Bali',
        salaryRangeMin: 8000000,
        salaryRangeMax: 12000000,
        businessName: 'Ayana Resort & Spa Bali',
        businessType: 'hotel',
        numberOfPositions: 1,
        accommodationProvided: true,
        requirements: ['Certified therapist', 'Leadership experience', 'Fluent in English', '5+ years experience'],
        benefits: ['Health insurance', 'Staff accommodation', 'Meals provided', 'Professional development'],
        contactPhone: '6281234567890',
        contactPerson: 'HR Department',
        contactEmail: 'careers@ayanaresort.com',
        country: 'Indonesia',
        city: 'Bali',
        positionTitle: 'Head Massage Therapist',
        salaryMin: '8000000',
        salaryMax: '12000000',
        accommodationDetails: 'Private room with meals included',
        workType: 'full-time',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'Full Body Massage Specialist',
        jobDescription: 'Join our holistic wellness team. Specializing in Swedish, aromatherapy, and hot stone massage.',
        employmentType: 'full-time',
        location: 'Ubud, Bali',
        salaryRangeMin: 6000000,
        salaryRangeMax: 9000000,
        businessName: 'Karma Wellness Ubud',
        businessType: 'wellness-center',
        numberOfPositions: 2,
        accommodationProvided: false,
        requirements: ['3+ years experience', 'Professional certification', 'Multiple massage modalities'],
        benefits: ['Health insurance', 'Staff discounts', 'Training opportunities'],
        contactPhone: '6281345678901',
        contactPerson: 'Maya Sari',
        contactEmail: 'jobs@karmawellness.com',
        country: 'Indonesia',
        city: 'Bali',
        positionTitle: 'Massage Specialist',
        salaryMin: '6000000',
        salaryMax: '9000000',
        accommodationDetails: '',
        workType: 'full-time',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'In-Room Massage Therapist',
        jobDescription: 'Provide exclusive in-room massage services to hotel guests. Evening and weekend shifts available.',
        employmentType: 'part-time',
        location: 'Nusa Dua, Bali',
        salaryRangeMin: 5000000,
        salaryRangeMax: 8000000,
        businessName: 'The Mulia Nusa Dua',
        businessType: 'hotel',
        numberOfPositions: 3,
        accommodationProvided: false,
        requirements: ['Professional certification', 'Excellent customer service', 'Flexible schedule'],
        benefits: ['Tips allowed', 'Flexible hours', 'Premium clientele'],
        contactPhone: '6281456789012',
        contactPerson: 'Guest Services',
        contactEmail: 'spa@themulia.com',
        country: 'Indonesia',
        city: 'Bali',
        positionTitle: 'In-Room Therapist',
        salaryMin: '5000000',
        salaryMax: '8000000',
        accommodationDetails: '',
        workType: 'part-time',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'Sports Massage Therapist',
        jobDescription: 'Work with athletes and active individuals. Deep tissue and sports injury recovery focus.',
        employmentType: 'full-time',
        location: 'Jakarta Selatan',
        salaryRangeMin: 7000000,
        salaryRangeMax: 10000000,
        businessName: 'Jakarta Sports & Wellness Clinic',
        businessType: 'clinic',
        numberOfPositions: 2,
        accommodationProvided: false,
        requirements: ['Sports massage certification', 'Anatomy knowledge', 'Experience with athletes'],
        benefits: ['Health insurance', 'BPJS', 'Professional development', 'Bonuses'],
        contactPhone: '6281567890123',
        contactPerson: 'Dr. Ahmad',
        contactEmail: 'hr@jakartasportsclinic.com',
        country: 'Indonesia',
        city: 'Jakarta',
        positionTitle: 'Sports Massage Therapist',
        salaryMin: '7000000',
        salaryMax: '10000000',
        accommodationDetails: '',
        workType: 'full-time',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'Poolside & Beach Massage Therapist',
        jobDescription: 'Provide relaxing massage services by the pool and beach. Beautiful work environment!',
        employmentType: 'contract',
        location: 'Seminyak, Bali',
        salaryRangeMin: 5500000,
        salaryRangeMax: 7500000,
        businessName: 'Seminyak Beach Resort',
        businessType: 'hotel',
        numberOfPositions: 4,
        accommodationProvided: true,
        requirements: ['2+ years experience', 'Comfortable working outdoors', 'Customer service skills'],
        benefits: ['6-month contract', 'Staff accommodation', 'Beach location', 'Tips'],
        contactPhone: '6281678901234',
        contactPerson: 'Resort Manager',
        contactEmail: 'jobs@seminyakbeach.com',
        country: 'Indonesia',
        city: 'Bali',
        positionTitle: 'Poolside Therapist',
        salaryMin: '5500000',
        salaryMax: '7500000',
        accommodationDetails: 'Shared staff accommodation near beach',
        workType: 'contract',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'Traditional Balinese Massage Therapist',
        jobDescription: 'Authentic Balinese massage techniques. Tourism-focused spa with international clientele.',
        employmentType: 'full-time',
        location: 'Sanur, Bali',
        salaryRangeMin: 6500000,
        salaryRangeMax: 9500000,
        businessName: 'Prana Spa Sanur',
        businessType: 'spa',
        numberOfPositions: 3,
        accommodationProvided: false,
        requirements: ['Expert in traditional Balinese methods', 'English speaking', 'Professional certification'],
        benefits: ['Staff discounts', 'Commission on products', 'Training', 'International clientele'],
        contactPhone: '6281789012345',
        contactPerson: 'Ketut Spa Manager',
        contactEmail: 'careers@pranaspa.com',
        country: 'Indonesia',
        city: 'Bali',
        positionTitle: 'Traditional Therapist',
        salaryMin: '6500000',
        salaryMax: '9500000',
        accommodationDetails: '',
        workType: 'full-time',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'Prenatal Massage Specialist',
        jobDescription: 'Specialize in safe, therapeutic massage for expecting mothers. Compassionate care required.',
        employmentType: 'full-time',
        location: 'Jakarta Pusat',
        salaryRangeMin: 7500000,
        salaryRangeMax: 11000000,
        businessName: 'Mother & Baby Wellness Jakarta',
        businessType: 'wellness-center',
        numberOfPositions: 1,
        accommodationProvided: false,
        requirements: ['Prenatal massage certification', 'Gentle touch expertise', 'Experience with pregnant clients'],
        benefits: ['Health insurance', 'BPJS', 'Maternity leave', 'Professional development'],
        contactPhone: '6281890123456',
        contactPerson: 'Dr. Siti',
        contactEmail: 'info@motherbabywellness.com',
        country: 'Indonesia',
        city: 'Jakarta',
        positionTitle: 'Prenatal Specialist',
        salaryMin: '7500000',
        salaryMax: '11000000',
        accommodationDetails: '',
        workType: 'full-time',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'Mobile Corporate Massage Therapist',
        jobDescription: 'Travel to corporate offices providing chair massage and stress relief services to employees.',
        employmentType: 'freelance',
        location: 'Jakarta (Multiple Locations)',
        salaryRangeMin: 6000000,
        salaryRangeMax: 10000000,
        businessName: 'Office Relief Indonesia',
        businessType: 'wellness-center',
        numberOfPositions: 5,
        accommodationProvided: false,
        requirements: ['Own transportation', 'Flexible schedule', 'Professional appearance', 'Chair massage experience'],
        benefits: ['Flexible hours', 'Travel allowance', 'Corporate clients', 'Growth potential'],
        contactPhone: '6281901234567',
        contactPerson: 'Rina Coordinator',
        contactEmail: 'apply@officerelief.co.id',
        country: 'Indonesia',
        city: 'Jakarta',
        positionTitle: 'Mobile Therapist',
        salaryMin: '6000000',
        salaryMax: '10000000',
        accommodationDetails: '',
        workType: 'full-time',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'Private Villa Massage Therapist',
        jobDescription: 'Serve high-end villa guests with personalized massage experiences. Premium service expected.',
        employmentType: 'part-time',
        location: 'Canggu, Bali',
        salaryRangeMin: 4500000,
        salaryRangeMax: 7000000,
        businessName: 'Canggu Private Villas',
        businessType: 'hotel',
        numberOfPositions: 2,
        accommodationProvided: false,
        requirements: ['Discretion', 'Multiple massage modalities', 'Luxury service experience', 'Flexibility'],
        benefits: ['High-end clientele', 'Premium tips', 'Flexible schedule', 'Exclusive environment'],
        contactPhone: '6282012345678',
        contactPerson: 'Villa Concierge',
        contactEmail: 'concierge@cangguvillas.com',
        country: 'Indonesia',
        city: 'Bali',
        positionTitle: 'Villa Therapist',
        salaryMin: '4500000',
        salaryMax: '7000000',
        accommodationDetails: '',
        workType: 'part-time',
        status: 'active',
        views: 0,
        applications: 0,
    },
    {
        jobTitle: 'Therapeutic/Rehabilitation Massage Therapist',
        jobDescription: 'Work alongside physiotherapists helping patients recover from injuries. Medical knowledge beneficial.',
        employmentType: 'full-time',
        location: 'Surabaya, East Java',
        salaryRangeMin: 6500000,
        salaryRangeMax: 9000000,
        businessName: 'Surabaya Physio & Rehab Center',
        businessType: 'clinic',
        numberOfPositions: 2,
        accommodationProvided: false,
        requirements: ['Therapeutic massage certification', 'Patient care experience', 'Medical knowledge helpful'],
        benefits: ['Health insurance', 'BPJS', 'Professional development', 'Medical team collaboration'],
        contactPhone: '6282123456789',
        contactPerson: 'Dr. Budi',
        contactEmail: 'recruitment@surabayaphysio.com',
        country: 'Indonesia',
        city: 'Surabaya',
        positionTitle: 'Therapeutic Therapist',
        salaryMin: '6500000',
        salaryMax: '9000000',
        accommodationDetails: '',
        workType: 'full-time',
        status: 'active',
        views: 0,
        applications: 0,
    }
];

async function addJobPostings() {
    console.log('Starting to add job postings to Appwrite...\n');
    
    let successCount = 0;
    let errorCount = 0;
    
    const postedDate = new Date().toISOString();

    for (const job of jobPostings) {
        try {
            await databases.createDocument(
                DATABASE_ID,
                COLLECTION_ID,
                ID.unique(),
                {
                    ...job,
                    postedDate
                }
            );
            console.log(`✅ Added: ${job.jobTitle} at ${job.businessName}`);
            successCount++;
        } catch (error) {
            console.error(`❌ Failed to add: ${job.jobTitle} at ${job.businessName}`);
            console.error('Error:', error);
            errorCount++;
        }
    }

    console.log(`\n📊 Summary:`);
    console.log(`   ✅ Success: ${successCount}`);
    console.log(`   ❌ Errors: ${errorCount}`);
    console.log(`   📝 Total: ${jobPostings.length}`);
}

// Run the script
addJobPostings()
    .then(() => {
        console.log('\n✨ Job postings addition completed!');
        process.exit(0);
    })
    .catch((error) => {
        console.error('\n💥 Script failed:', error);
        process.exit(1);
    });
